### ISSUE TITLE
HTML5 Player Enhancement

### ISSUE THREAD

**Issue by zacyu** [zacyu/bilibili-helper#1]
TODO:
- [x] 支持发弹幕
- [x] 网页全屏/浏览器全屏
- [x] 修改样式使符合 B 站风格
- [x] 同步弹幕透明度、音量等设置
- [ ] 分段 mp4 弹幕同步
- [x] 人工读取 m3u8 问题

**Comment by swordfeng** [comment]
发弹幕的部分
http://interface.bilibili.com/dmpost?cid=<cid>&aid=<aid>&pid=<pageid>
POST参数
rnd=375282529<猜测为随机数>&pool=0&color=16711680<16进制颜色的10进制值>&cid=<cid>&fontsize=25<默认为25>&mode=1<应该是方向>&playTime=68%2E989<单位是秒，%2E是小数点转义>&message=<弹幕内容>&date=2014%2D12%2D16%2017%3A13%3A52<2014-12-16 17:13:52>

**Comment by zacyu** [comment]
Feature deprecated. Closing.
