### ISSUE TITLE
mac使用html5播放器后弹幕字体变大，且无法调节大小

### ISSUE THREAD

**Issue by relliky** [zacyu/bilibili-helper#100]
rt

顺便问一下，是不是用个mac播放器的选项，我在首页截图上看到的有，为什么我在看b站的时候没有找到呢

**Comment by relliky** [comment]
不好意思，把鼠标炫富隐藏弹幕图标后，再调整弹幕比例后，解决。顺便还想问问那个“mac播放器”是什么东西，为什么没有看到。

**Comment by zacyu** [comment]
那个是 http://bilimac.eqoe.cn/

**Comment by relliky** [comment]
谢谢
