### ISSUE TITLE
ass弹幕缺少格式信息

### ISSUE THREAD

**Issue by NekoYuuka** [zacyu/bilibili-helper#106]
建议把以下信息添加进并插入到ass信息头：
    [Script Info]
    ScriptType: v4.00+

    [V4+ Styles]
    Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
    Style: Default,Microsoft YaHei,25,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,0,2,10,10,10,1

    [Events]
    Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text

否则播放器可能无法正常挂载。

**Comment by zacyu** [comment]
感谢反馈, 原因是我发布, 压缩代码的时候注释被删除了. @tiansh 你用的那个 funStr 太 hacky 了.

**Comment by tiansh** [comment]
YUI 能认 /*! 注释的……= =

**Comment by zacyu** [comment]
用的是 uglifyjs
