### ISSUE TITLE
SimilarWeb的追踪能提供关闭选项吗？

### ISSUE THREAD

**Issue by XZiar** [zacyu/bilibili-helper#113]
upalytics_ch.js这个应该是SimilarWeb的吧， 隐私协议全英文实在是有心无力，但涉及隐私的功能能不能提供开关呢？
偶然抓包发现的，浏览任何网页都会有base加密的数据包发出去。。。

**Comment by jabbany** [comment]
参考 #33

**Comment by myfreeer** [comment]
just create a fork and remove it yourself,and check background.js for lines including http

**Comment by zacyu** [comment]
Just as @jabbany and @myfreeer said.
