### ISSUE TITLE
HTML5 播放器可以提供字幕屏蔽功能么

### ISSUE THREAD

**Issue by xxtXieTingF** [zacyu/bilibili-helper#117]
如题，还有就是 HTML5  的弹幕的字体都默认很大，希望能改一下。

**Comment by BigPa** [comment]
+1

**Comment by Demodi** [comment]
@xxtXieTingF  @BigPa  在左下角的右四图标，单击时关闭弹幕。点开可调整大小

**Comment by BigPa** [comment]
@Demodi 字幕屏蔽指部分屏蔽
（吵架、秀优越、刷屏、日期等）

**Comment by xxtXieTingF** [comment]
恩恩是的，字幕屏蔽主要是指关键字屏蔽那一类

**Comment by ywwzwb** [comment]
最好能同步官方播放器设定的屏蔽规则
