### ISSUE TITLE
当有消息提示时，播放器会挂掉

### ISSUE THREAD

**Issue by 872517414** [zacyu/bilibili-helper#118]
重新点击暂停和开启也没用

情况：下载文件下载完后的消息提示音，不是渐减后渐加的音量，而是直接死了

360极速浏览器  8.5.0.132
操作系统    Windows 10

**Comment by 872517414** [comment]
好吧，貌似是我网络的锅，那时候挂着 linode jp ss......... 这时间把握的真好。

**Comment by FiveYellowMice** [comment]
😒 360 极速浏览器……
