### ISSUE TITLE
弹幕看不到

### ISSUE THREAD

**Issue by ywwzwb** [zacyu/bilibili-helper#121]
没有弹幕了,拜年祭视频,看不到弹幕av3521416
![image](https://cloud.githubusercontent.com/assets/13915067/13101428/858839d4-d581-11e5-8af3-890245f0d2b4.png)

**Comment by myfreeer** [comment]
遇到过同类问题，一直显示
> 弹幕发送者查询
正在加载全部弹幕, 请稍等…

可以尝试清空缓存，开f12然后刷新

**Comment by myfreeer** [comment]
https://github.com/myfreeer/bilibili-helper
修好了
