### ISSUE TITLE
浏览器不支持flash的话似乎h5播放器也无法工作

### ISSUE THREAD

**Issue by caoli5288** [zacyu/bilibili-helper#126]
无flash插件的chromium在载入封面后无法开始缓冲，分析页面无法得到任何媒体信息。
对于非win党来说没flash似乎很正常呢，这个能解决吗。

**Comment by caoli5288** [comment]
几分钟后我装上了一个flash插件，然而发现h5播放器视频依然无法播放，flash播放器是可以播放的。

**Comment by alloo0o** [comment]
我的 Chromium 也是。貌似是 Chromium 自己的问题 或者助手没兼容？用 Chrome 就没问题...

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新
