### ISSUE TITLE
在 Chromium 上有点问题诶

### ISSUE THREAD

**Issue by alloo0o** [zacyu/bilibili-helper#128]
咦 为什么在我家的 Chromium 上用不起 HTML5 播放器了 不知道是 Chromium 这个版本的 bug 还是助手没更新的缘故    Chromium 50.0.2658.0:377035

**Comment by FiveYellowMice** [comment]
用稳定版、用稳定版、用稳定版！为什么 dev 版要叫 dev ？因为它可能有 bug ！是让有兴趣的人测试和反馈 bug 用的，不是日常使用的！

**Comment by alloo0o** [comment]
噫… 我就是有兴趣帮忙搞 bug 反馈玩的… 你们呐总想弄个大新闻，就把我用 dev 批判一番，噫… 这样是不好的╭(°A°`)╮

**Comment by FiveYellowMice** [comment]
那最好用稳定版再看一下，如果稳定本没有问题那就不是这个插件的问题了。

**Comment by alloo0o** [comment]
今天才看到... 现在知道啦 Chromium 的 dev 版本去掉了有版权的媒体文件的解码（如 mp3、mp4、aac）所以还是老老实实滚回去用稳定版了，当时 Chrome 内存占用奇高所以转投了 Chromium 不知道现在 Chrome 如何 不过也懒得换回来了

**Comment by zacyu** [comment]
@alloo0o 这个改变也会很快在将来迭代到 stable 吗?

**Comment by alloo0o** [comment]
我觉得应该不会，编译 stable 和 dev 的人好像不是同一个，不过不知道为什么 后来 Chromium Dev 并没有加上（或者是去掉了？）这些格式的编码。Chromium 用的人也少，如果以后真的 stable 版也这样了（虽然我不信）只好换回 Chrome 啦。Sigh... 至于想继续用的人，那就自己从源码里把 解码器编译进去吧 233333

**Comment by FiveYellowMice** [comment]
是 Chromium 没有解码器而 Chrome 有。跟 dev 和 stable 没关系吧。
