### ISSUE TITLE
HTML5播放器 视频源加速功能

### ISSUE THREAD

**Issue by Love4Taylor** [zacyu/bilibili-helper#131]
如题，b站官方播放器会有 视频源加速 功能，这样国外看b站会快很多，然而切换到HTML5之后视频基本没法加载

**Comment by myfreeer** [comment]
"http://interface.bilibili.com/playurl?appkey=86385cdc024c0f6c&platform=android&quality=4&cid=" + request.cid + "&otype=json&platform=android&accel=1"
是指这样？
