### ISSUE TITLE
请问能否开发Firefox版？

### ISSUE THREAD

**Issue by jimogsh** [zacyu/bilibili-helper#135]
a.t.t.

**Comment by fenglingdingdang** [comment]
同问，从firefox48开始扩展将从XML切换至WebExtensions API，把chrome版移植到firefox应该不需要大的修改

**Comment by jjj201200** [comment]
0.8.16.21版本已经开始在ff商店审核，审核过后会在助手官网和微博推送通知，请留意

**Comment by doio** [comment]
因为现在 Firefox 已经开始了支持 WebExtensions，所以我今天就在想能不能把 Chrome 上面这很有用的插件移植到 Firefox，结果我还真找到了，以下是方法，亲测可用。

首先，请在 _**Firefox Addons**_ 商店找到以下插件，并安装：
[Chrome Store Foxified](https://addons.mozilla.org/zh-cn/firefox/addon/chrome-store-foxified/)

然后，复制 _**Bilibili Helper: Bilibili.com Auxiliary**_ 的官方 Chrome 插件页面：
[Bilibili Helper](https://chrome.google.com/webstore/detail/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8A%A9%E6%89%8B%EF%BC%9Abilibilicom-%E7%BB%BC%E5%90%88%E8%BE%85%E5%8A%A9%E6%89%A9%E5%B1%95/kpbnombpnpcffllnianjibmpadjolanh?hl=zh-CN)

然后插件会进行提示，先登录 Mozilla Addons 中心，然后插件会自动进行操作。
可以选择保存经过验证的 XPI 文件，拖到火狐里面就可以安装了。
（如果出现文件可能损坏，再试一次即可。）

有图有真相
<img width="668" alt="2017-08-23_12-02-10" src="https://user-images.githubusercontent.com/4461202/29598350-f85ea8a8-87fa-11e7-9551-ee85e109492c.png">

**Comment by zacyu** [comment]
@doio 我们知道扩展可以手动加载, 但是目前我们的项目用到的一些 minified third-party code 需要更好地引用才能符合 Mozilla 的相关 policy, 所以之前提交的几次审核都没有通过. 感谢您的关注, 我们会在完成相关修改并在 Mozilla Add-on 平台发布后在这边给大家更新 （´・ω・｀）

**Comment by mycraftmw** [comment]
作者大大，FF最近更新到57了，希望插件能直接支持到FF57。感谢！

**Comment by jjj201200** [comment]
今天秒过，但是似乎搜不到
https://addons.mozilla.org/zh-CN/firefox/addon/bilihelper/

**Comment by xmcp** [comment]
@jinliming2 因为你勾了这个选项
![image](https://user-images.githubusercontent.com/6646473/36521137-1d5ddd4e-17d0-11e8-87d9-24730c51594d.png)

**Comment by jinliming2** [comment]
。。。 @xmcp 你。。。是不是 at 错人了。。。

**Comment by jjj201200** [comment]
@xmcp 谢谢，已经改掉了

**Comment by Zhang-Siyang** [comment]
呃，看来是已经撤销了Firefox支持

**Comment by Capricornus2003** [comment]
chrome store foxfied那个组件，现在我看了，被下架了，还有没有别的办法。。。
我也想在火狐用助手
