### ISSUE TITLE
助手菜单与充电按钮重合

### ISSUE THREAD

**Issue by IsaacXen** [zacyu/bilibili-helper#136]
某些有充电功能的页面会出现如下图情况(如[这个页面](http://www.bilibili.com/video/av4141253/)):
![2016-03-20 13 08 41](https://cloud.githubusercontent.com/assets/16833681/13902937/15ca5f8e-ee9d-11e5-9c8f-483c4744d6ce.jpg)

**Comment by muzea** [comment]
可以使用Stylish为www.bilibili.com这个域增加一条样式
```
#bilibili_helper{
    float: none;
}
```
使助手显示在硬币的右边

**Comment by IsaacXen** [comment]
Thanks for that.

**Comment by jjj201200** [comment]
此问题以解决:smiley:
