### ISSUE TITLE
你好，兩個問題

### ISSUE THREAD

**Issue by MidoriG** [zacyu/bilibili-helper#137]
1.更換為HTML5播放器後，可否設定彈幕於全螢幕中的大小? 對我而言過大

2.似乎找不到關閉Chrome推放通知的選項?

**Comment by FiveYellowMice** [comment]
![screenshot_20160329_000606](https://cloud.githubusercontent.com/assets/9077203/14078504/0ca2a5b4-f542-11e5-9819-08a5ebc7718d.png)
