### ISSUE TITLE
你的网盘似乎也挂了。没法下载下来crx。

### ISSUE THREAD

**Issue by PureRuins** [zacyu/bilibili-helper#144]
能否上传一个百度云或者其他地址呢？

**Comment by PureRuins** [comment]
苦逼的墙内人员，lantern最近也非常不稳定。

**Comment by KochiyaNoro** [comment]
Why not use [Github](https://github.com/zacyu/bilibili-helper/releases)?

**Comment by PureRuins** [comment]
forget it. Sorry, i have downloaded it. THX
