### ISSUE TITLE
中途开启弹幕会显示之前的所有弹幕

### ISSUE THREAD

**Issue by liuz430524** [zacyu/bilibili-helper#146]
播放之前选择不显示弹幕，在播放中途开启，会把之前所有的弹幕一下子全显示出来，如图。如果弹幕量很大的话会卡住播放器一两秒钟，然后cpu占用飙升，有一点影响使用，希望可以修复一下，辛苦了。
我找了一下issues，貌似没有看到类似问题的反馈？难道大家没碰到相同的问题吗？
chrome 49.0.2623.112 (64-bit) + 哔哩哔哩助手v0.8.4
![2016-04-11 2 41 35](https://cloud.githubusercontent.com/assets/8044101/14418926/ae80cffc-fff4-11e5-96b5-eeeaada912ac.png)

**Comment by jjj201200** [comment]
这不是官方的播放器吗？
是指只有在开启Bili助手时才有这个问题吗？
如果不是的话，反馈到[这里](http://bbs.biligame.com/forum.php?mod=forumdisplay&fid=44)可能更加合适

**Comment by zacyu** [comment]
@jjj201200 这个是我的 HTML5 播放器. 不过这个问题需要 Attn: @jabbany

**Comment by jabbany** [comment]
哦哦，这个估计是目前启动/关闭弹幕的逻辑有BUG（我得检查一下ABP）。CCL的time函数只负责派发弹幕到运行队列，不清除过期的弹幕。要是运行队列一直没start()，就会堆起来一起派发。。。

目前的临时解决方法大概是在显示弹幕（每次从关闭弹幕状态切换到显示弹幕状态）的时候先行clear() 一下，保证没有弹幕在队列里面。

不过CCL应该不久就会增加一个Fix让Runline里面的弹幕在start后自动就位，那样过期的弹幕就不会被显示+打开弹幕的话，正在运行中的弹幕会被摆放到正确的位置，而不是同一个起点。
