### ISSUE TITLE
关于解析tudou源失败的BUG

### ISSUE THREAD

**Issue by Explorare** [zacyu/bilibili-helper#15]
http://www.bilibili.com/video/av1892662/
这个视频是土豆版权，解析失败，无法获取视频地址。望修复。
另外这个视频也有爱奇艺的源，能否设定解析为爱奇艺呢？或者添加手动输入页面地址并解析的功能，方便手动添加源。

**Comment by swordfeng** [comment]
没广告就算了吧。。。我是这么想的

**Comment by swordfeng** [comment]
手动加源……我也这么想
但是B站的播放器只认cid
除非逆向工程（虽然试过但是B站播放器那庞大的代码。。。）或者替换html5播放器，然后手动解析
这也是为什么我想施工一个html5播放器的原因。。。

**Comment by Explorare** [comment]
现在B站的弹幕播放器已经是最复杂的了吧，mukio已经好久不更新了。

**Comment by swordfeng** [comment]
@Explorare 额。。。哪个，我没有添加过……你是说bilibili助手的么，那是助手作者自己修改的ABPlayerHTML5，也不是B站实验项目

**Comment by Explorare** [comment]
哦，下次更新會添加什麼功能呢？什麼時候更新呢？

**Comment by swordfeng** [comment]
撒，问作者去吧……

**Comment by Zhuogu** [comment]
@Explorare 我最近比较忙，有时间就回去更新。土豆源目前无解——只有使用移动端可以播放时我才有办法去替换

**Comment by swordfeng** [comment]
@Zhuogu 如果有土豆本身的解析方案如何

**Comment by zacyu** [comment]
Obsolete now :)
