### ISSUE TITLE
迷之广告劫持

### ISSUE THREAD

**Issue by SkiTiSu** [zacyu/bilibili-helper#150]
![image](https://cloud.githubusercontent.com/assets/8959735/14711235/235f3c28-080b-11e6-9605-2713a06017ea.png)
这到底是个什么情况……为什么里面有bilibili-helper？

**Comment by jjj201200** [comment]
@SkiTiSu 哪里哪里？没看到0.0

**Comment by SkiTiSu** [comment]
@jjj201200 在B站内的任意页面，有一定的几率会出现这个广告，很诡异，但是bilibili-helper的源码里貌似没这玩意啊……

**Comment by SkiTiSu** [comment]
@jjj201200 感觉是运营商的锅，bilibili-helper的class貌似只要装了插件都会显示的，但是别的网站就不会有这个...我再看看吧，跟helper应该无关
