### ISSUE TITLE
部分视频拼接顺序错误

### ISSUE THREAD

**Issue by Elfwarrior** [zacyu/bilibili-helper#152]
发现有一部分视频在拼接过程中发生顺序错误，比如这个：http://www.bilibili.com/video/av415994/ 还有http://www.bilibili.com/video/av59248/ 
这两个视频下载下来发现前后顺序颠倒，希望可以解决这个问题

**Comment by zacyu** [comment]
拼接的操作是 B 站完成的, 请将这个问题转至 B 站客服. 😄
