### ISSUE TITLE
可能会导致蓝屏?

### ISSUE THREAD

**Issue by RenneXV** [zacyu/bilibili-helper#155]
这个视频..http://www.bilibili.com/video/av4508655/  8.40版打开会出现蓝屏..其他视频正常，删除插件后蓝屏消失。浏览器是360极速8.5.0.138 内核45.0.2454.101

**Comment by jjj201200** [comment]
惊了,如果是真的,那真是太厉害了

**Comment by RenneXV** [comment]
- -可能只有我这样..
