### ISSUE TITLE
Google Chrome 报警告：可能和Unblock Youku冲突

### ISSUE THREAD

**Issue by lisanhu** [zacyu/bilibili-helper#156]
RT
![image](https://cloud.githubusercontent.com/assets/3086096/14942528/7cecd898-0f8d-11e6-82c0-794a1e81a581.png)

**Comment by zacyu** [comment]
您好, 实际上是不会印象 Unblock Youku 使用的, 只是会有一个警告: 见 #72

**Comment by lisanhu** [comment]
谢谢
