### ISSUE TITLE
使用助手抽出音频并下载时一直是失败的

### ISSUE THREAD

**Issue by lchen99045** [zacyu/bilibili-helper#157]
这周我使用助手的时候，下载时总会跳出来正在等待排队，等了一两小时他也没下载下来![image](https://cloud.githubusercontent.com/assets/19155535/14964112/dbe5126a-1074-11e6-8758-5b090562978c.png)

**Comment by zacyu** [comment]
感谢反馈 @hanbang-wang 请跟进一下.

**Comment by hanbang-wang** [comment]
@zacyu 抱歉啊……我QQ和你说了这件事了……
