### ISSUE TITLE
弹幕阴影错位

### ISSUE THREAD

**Issue by chenxuuu** [zacyu/bilibili-helper#159]
我观察了下。。弹幕里掺杂数字的会错位
![1](https://cloud.githubusercontent.com/assets/10357394/15116127/a767adde-1634-11e6-87a0-fc425525b576.png)

**Comment by Sam0523** [comment]
+1，弹幕中全角半角字符都有的时候就会错位

**Comment by myfreeer** [comment]
.cmt{text-shadow: rgb(0, 0, 0) 0px 0px 6px !important;}
试试这样？

**Comment by chenxuuu** [comment]
@myfreeer 你测试下呗→_→ 能用的话就push上去

**Comment by myfreeer** [comment]
@chenxuuu 我没遇到过这个问题，那个样式是放到Stylish里面用的
