### ISSUE TITLE
今日Bilibili更新播放器之后无法使用

### ISSUE THREAD

**Issue by iamtwz** [zacyu/bilibili-helper#162]
播放器切换
原始播放器
视频下载
视频地址获取中，请稍等…
弹幕发送者查询
正在加载全部弹幕, 请稍等…
Cid 获取失败
错误-1: app has been blocked.
Cid 获取失败
错误-1: app has been blocked.
哔哩哔哩助手 v0.8.4 by @啾咕咕www

**Comment by liuz430524** [comment]
+1

**Comment by Lin1079** [comment]
+2
B站万年不变的播放器居然更新了

**Comment by cccRaim** [comment]
+3

**Comment by y917059177y** [comment]
+4看来要一番大改了，加油！

**Comment by jjj201200** [comment]
+5

**Comment by myfreeer** [comment]
apikey坏了，换一个就行

**Comment by ngkeanhowe** [comment]
+6

**Comment by jkai** [comment]
+7

**Comment by xinghuolei** [comment]
+8

**Comment by echotrolly** [comment]
确实炸了。。

**Comment by j20120307** [comment]
+9

**Comment by wq2014** [comment]
+10

**Comment by ilufang** [comment]
B站更新个Flash播放器还把HTML5禁了，失望
如果不给API就要想办法破解网页视频解析喽？

**Comment by ly541349042** [comment]
+1  昨天晚上开始发现不能用了. 但是mac不用h5播放器的话就能烤鸡蛋了....所以b站这是闹哪出?

**Comment by returnSky** [comment]
+10086

**Comment by xyx0826** [comment]
+65536 新b站播放器明显比h5卡

**Comment by hellworld** [comment]
＋3.1415926

**Comment by LucasYuNju** [comment]
+1024

**Comment by sunclx** [comment]
+12

**Comment by Jackadminx** [comment]
+1

**Comment by fengyunkkx** [comment]
+12dora

**Comment by QingWei-Li** [comment]
+2333

**Comment by WondermSwift** [comment]
+2333

**Comment by ZCXLLOD** [comment]
B站自己的HTML5播放器：http://www.bilibili.com/html/help.html#p，目前还没有正式加入，具体时间不定，使用方法：http://www.bilibili.com/html/html5player.html?aid=XXXXXXX&page=X，其中aid=视频av号，page=第几P，如果只有1P填1就行。『注意：【使用HTML5播放器会降低视频画质，大概会降低到流畅级别，具体有多清楚还得看个人感觉】&【目前HTML5播放器不能发弹幕】&【经我测试，在IOS系统中UC浏览器不能打开视频，不过UC浏览器HD（ipad版）是可以打开视频的，但不能显示弹幕，，Safari浏览器可以打开视频但也不能显示弹幕】&【刚打开时加载稍慢，请等上一会儿，如果不行请刷新网页，一般都能解决】』。

**Comment by Jackadminx** [comment]
@ZCXLLOD 
bilibili HTML5视频播放器目前使用于bilibili HTML5主站（移动版网页），用于非客户端环境下的移动设备浏览器访问

**Comment by ihatead** [comment]
各位可以看一下 我發的 Pull requests 可以把我修正的自行複製一下就好了. 在開啟chrome的開發者模式
讀取修改的版本. 就好了. 只是 有時沒有抓到彈幕. 但是至少能看.

**Comment by zacyu** [comment]
因为 B 站方面还没有回复, 暂时采用了 #169 的 fix. 之后会考虑 #170 的方案.

**Comment by zmyspc** [comment]
H5比Flash的播放器缓存视频快多了
