### ISSUE TITLE
BILIBILI助手 功能征集 和 意见反馈 ！！！！！！

### ISSUE THREAD

**Issue by jjj201200** [zacyu/bilibili-helper#164]
# 1. 目前已经有的功能：

## 1.1 看番助手
1. 弹幕查询
2. 视频下载
3. HTML5播放器替换
4. 关联视频搜索
5. “我的关注” 桌面提醒
6. 广告屏蔽
7. 右键快速搜索菜单
8. 一键前往首页

## 1.2 直播间助手 - [功能介绍](https://github.com/zacyu/bilibili-helper/wiki/bilibili-helper-live)
1. 自动签到；
2. 竞猜多次预约；
3. 自动领瓜子；
4. 直播间开播推送；
5. 新功能的设置选项；
6. 长弹幕自动分段发送；
7. 聊天界面信息屏蔽选项。

## 1.2.1 待开发功能：
1. 自动领取小电视；
2. **合理地** 自动分段弹幕；
3. 直播间关键字屏蔽功能。

# 2. 其它收到的建议 / 改进 / 功能：
1. 瓜子不足时自动使用免费礼物；
2. 自动领红包；
3. 将直播间的宝箱移出播放器。

# 3. 已反馈问题 / 建议
## 3.1 看番助手
1. 导致页面顶端菜单的弹出框出现滚动条；
2. HTML5播放器的重构和全方位的功能增强：在线解析视频地址，弹幕显示增强，清晰度选择

## 3.2 直播间/直播助手
1. 特别关注的桌面通知，显示后点击“观看”，不自动关系。

还希望添加什么呢？

**Comment by liuz430524** [comment]
弹幕超过字数自动分段延时发送？

**Comment by jjj201200** [comment]
@liuz430524 有趣有趣

**Comment by jjj201200** [comment]
@liuz430524 b站前端将输入栏封装为shadow-root组件，包括事件在内目前没什么思路进行拆分，直接赋值无效

**Comment by liuz430524** [comment]
@jjj201200 要不自己实现？
![image](https://cloud.githubusercontent.com/assets/8044101/15276114/dcb3249c-1b10-11e6-803d-7be7cf9451d8.png)

**Comment by jjj201200** [comment]
@liuz430524 啊我都忘记了还有这个，已经找到rnd了，多谢，一会儿去试试

**Comment by jjj201200** [comment]
@liuz430524 搞定，谢啦
其中碰到一个问题，使用ajax直接提交用户自己的播放器里不会看到自己发的弹幕，找了半天在压缩的代码里找到了那么一句话，问题解决。
```javascript
$("#player_object")[0].sendMsg(danmu, '0xffffff')
```
至于颜色的问题，之后再说吧233

**Comment by zacyu** [comment]
颜色参见我目前 HTML5 播放器发送弹幕部分的实现, 应该是类似的.

**Comment by jjj201200** [comment]
@zacyu 搞定了，是直播间的弹幕颜色233

**Comment by jjj201200** [comment]
@zacyu how to trigger a dom event in a inactive page?

**Comment by ljxfstorm** [comment]
开播推送？

**Comment by jjj201200** [comment]
@liuz430524 官方有直播推送的，只不过不是那种弹窗提醒，而是直播间左边栏的弹出提醒。所以您是觉得有必要做chrome弹窗提醒吗？

**Comment by jjj201200** [comment]
@ljxfstorm 官方有直播推送的，只不过不是那种弹窗提醒，而是直播间左边栏的弹出提醒。所以您是觉得有必要做chrome弹窗提醒吗？

**Comment by ljxfstorm** [comment]
@jjj201200 嗯，毕竟实际上只会看部分Up的直播，并且也不会一直蹲在直播间里。

**Comment by jjj201200** [comment]
@ljxfstorm 是的呢，采纳了~

**Comment by jjj201200** [comment]
@ljxfstorm 功能已经完成~

**Comment by yonjar** [comment]
up直播chrome弹窗提醒  假如关注的主播多的话，可能会有点烦，所以能选择那些up显示通知，那些不显示就好了

**Comment by jjj201200** [comment]
@yonjar 就是说指定特别关注的up进行推送吗？如果不指定的话就全部推送？这样也不错

**Comment by yonjar** [comment]
@jjj201200 嗯嗯，就是這個意思

**Comment by jjj201200** [comment]
@yonjar 搞定了，在关注按钮旁边增加了一个特别关注按钮，被特别关注的会桌面通知，如果没有被特别关注的up，就会全部推送桌面通知

**Comment by lamlam77777** [comment]
自動使用粉丝勋章礼包
自動每天使用硬幣換銀瓜子

**Comment by jjj201200** [comment]
@lamlam77777 额？这是什么需求？

**Comment by jjj201200** [comment]
@lamlam77777 这两个需求暂时放在待考虑列表吧

**Comment by jjj201200** [comment]
@lamlam77777 你的第一个需求我已经反馈给b站了，等待回复吧，第二点需求太小众化了暂不采纳，望理解

**Comment by gu396433839** [comment]
自动分段发送的弹幕颜色可以跟用户设置一样吗？比如本来设置的是橙色弹幕，自动分段发出去的就是白色的，能保持颜色一致么？还有如果超过30字，添加个B站颜文字或者粘帖文件到聊天框，就会回到30字的上限，31字开始要重新打一遍，希望修复下这个bug

**Comment by gu396433839** [comment]
还有一个问题是弹幕长度没有超过30字，按回车发送的话，会弹出请输入弹幕再发送的提示框，关闭弹幕增强功能就不会有了，确定是扩展问题。另外一个建议是，分段弹幕发送完第一段后别马上发第二段，因为第一段弹幕从发送到完全显示需要时间，自己测试过，如果是20字的弹幕，从发送到完全显示需要2秒，如果是30字的弹幕，从发送到完全显示需要3秒，希望设置分段延迟发送，目前发送效果，一定程度上影响阅读

**Comment by jjj201200** [comment]
@gu396433839 谢谢反馈问题

**Comment by mlisry** [comment]
请问可以加一个自动领小电视的功能吗?  另外现有的直播间自动签到和自动领瓜子应该怎么用呢... 我的这3个功能处于打开状态,但是并没有自动领瓜子和签到 ...最后谢谢您的助手^^~

**Comment by jjj201200** [comment]
@mlisry 你好，自动领小电视的功能我已经考虑过，由于只有app才支持socket所以倘若实现的话不太友好，暂不考虑。自动签到和自动领瓜子的功能在助手当前版本存在bug，我已经和助手作者沟通过一段时间后再更新功能。你可以在我的库中找到最新发布的版本，其中对部分bug进行了修复。最后感谢你继续关注辅助在webstore的更新。有什么问题可以随时反馈。

**Comment by jjj201200** [comment]
@mlisry 另外，我所谓的 **自动领小电视** 只是自动参与小电视抽奖。目前需要的核心代码已经准备完毕，倘若有多人要求该功能，我将会在下个版本发布此功能。

**Comment by jjj201200** [comment]
@gu396433839 您好，你反馈的部分功能和界面问题已经全部修正，期待下一次更新。你也可以暂时使用最近提交的库代码在开发者模式下进行安装，来使用最新版本。

**Comment by mlisry** [comment]
@jjj201200 是的是的，我请求的就是 自动参与小电视抽奖 这个功能><.. 抱歉没表达清楚..
无论如何，期待你们闪闪发光的更新！感谢你们☆

**Comment by lzghzr** [comment]
@jjj201200 自动参与小电视其实也是另一种领瓜子方式吧，希望添加(=・ω・=)

**Comment by hzcxdgioa** [comment]
可以做做自动领取直播间红包的功能吗？
另外，我也希望可以增加自动参与小电视抽奖的功能啊，领低保过时不候啊

**Comment by gu396433839** [comment]
能不能把这个“哔哩直播助手 v0.8.6 by @沒事卖萌肉”放到助手的设置页面或者直播网页的侧边栏里去，直接显示在直播间网页上有点不舒服（应该是不习惯吧，或许过几天就适应了呢）。还有能不能恢复显示已输入字数？至少让我知道我输入了多少字。
上面有人说到了小电视的问题，我自己是无所谓的，但如果要是开启这个功能，希望跟其他功能一样有个开关，可以选择把这个功能关闭掉，我自己只用通知和弹幕增强，其他的我自有途径更加完善的实现

**Comment by jjj201200** [comment]
@hzcxdgioa 自动参与小电视抽奖在之后的版本会推出，直播间红包是指什么？？比如这次端午活动的“鼓棒”？

**Comment by jjj201200** [comment]
@gu396433839 关于弹幕增强的改进意见已经收到了，谢谢你的反馈，我们将在后续版本进行更新，敬请期待。关于左侧菜单的功能关闭问题也已经记下。

**Comment by hzcxdgioa** [comment]
直播间红包就是每周六2333房间暴走吧的红包啊。发条弹幕就领一千瓜子到手啊。方便做的话希望可以考虑下。
另外询问下，关于小电视的通告是通过什么方式获取到的啊，是与弹幕相同的链接中实时推送的吗？
我自己写了一些b站的挂机脚本，可以完全不开网页的，目前就是无法获取到小电视的通告，需要人工监视输入房间号来参与抽奖。
不知道能否告知有关小电视通告的相关细节呢?
其他脚本我并不会，只会win的batch标本。

**Comment by jjj201200** [comment]
@hzcxdgioa 桌面上和浏览器里的实现方式可以不一样。桌面上的思路是链接弹幕服务器监控推送弹幕，然后用指定的api和数据进行请求。但是由于extension不能够使用socket，所以只能用其他方法。具体的api你可以在我推送更新后查看

**Comment by jjj201200** [comment]
=、=关于红包，我最近没有看直播随意并不知道，谢谢反馈

**Comment by hzcxdgioa** [comment]
win的批处理好像做不到弹幕服务器的监视，也就是无法建立即时通讯的链接，似乎是不可能实现的了。
另外，关于红包的脚本，如果你看得懂win的批处理，你可以参考下我的脚本。
https://github.com/hzcxdgioa/bilibili-XiaoDianSiCouJiang/blob/master/%E7%9B%B4%E6%92%AD%E9%97%B4%E7%BA%A2%E5%8C%85%E9%A2%86%E5%8F%96.bat
里面有红包的一些链接命令。

**Comment by jjj201200** [comment]
@hzcxdgioa 嗯，不过api具体的数据结构不清楚，等什么时候去看看就知道了

**Comment by hzcxdgioa** [comment]
echo.id:%%i,type:%%j,pwd:*******,countdown:%%l,status:%%m,isUserGet:%%n
貌似这个就是格式
pwd就是要求发送的弹幕内容，
status是倒计时，在等于5的时候就可以发送弹幕了，具体的 你可以再测试

**Comment by hzcxdgioa** [comment]
countdown才是倒计时，status说错了

**Comment by gu396433839** [comment]
遇到个问题，如果连接B站服务器不畅，速度比较慢，弹幕增强功能会获取用户权限失败，结果是本来能发30字分段的，发送20字就分段了，能不能手动指定分段长度？避免获取用户权限失败。而且分段发送其中一部分实际发送会失败或者分段发送顺序不对，弹幕姬里不显示不全（后面这个是网络问题连接不畅，要是没办法解决就算了，算是海外党的日常bug了）

**Comment by jjj201200** [comment]
@gu396433839 已经更新，应该不会出问题了

**Comment by gu396433839** [comment]
0.88版本严重bug，按回车发送弹幕后就无法发生任何弹幕，刷新网页才能发送，关闭弹幕增强功能就没事了，0.87版本无此问题

**Comment by mlisry** [comment]
发现已经更新过了~~ 但是选项页没有发现小电视开关，请问是整合在领瓜子里了吗？还是暂时还没有实现？

**Comment by jjj201200** [comment]
@gu396433839 并不是bug，无法发送是因为弹幕发出去之后需要等待几秒才能发新弹幕，以免被吃掉

**Comment by jjj201200** [comment]
@mlisry 没有实现

**Comment by gu396433839** [comment]
看到你说“无法发送是因为弹幕发出去之后需要等待几秒才能发新弹幕，以免被吃掉“，虽然被你自己删除了，但我并不希望添加这个功能，前几天是容易被吃掉，自从前天B站优化了弹幕发送后就几乎不会吃掉了，之前弹幕丢失最严重的时候丢失率超过60%，现在基本能维持在丢失率1%以下，就算我发快了，一样不会被吃。另外附上0.88版本无法发弹幕bug的[演示视频](http://puu.sh/pwxAd/f8409b0d24.mp4)（6.77MB）

**Comment by jjj201200** [comment]
@gu396433839 正在修复，之后采用新策略。

**Comment by airhiki** [comment]
添加一个消息提示？回复啊，私信什么的……

**Comment by jjj201200** [comment]
@airhiki 关于问题反馈之类的功能有在我的考虑中。谢谢你的意见:smile:请期待重构后的助手

**Comment by liuz430524** [comment]
弹幕显示增强是指支持特殊弹幕？:clap::clap:
另外，这两天看到一个在html5的canvas上绘制弹幕的项目，测试了一下，比css动画要节省cpu，即使是满屏的弹幕cpu还是低频运行，挺不错的，不知道是否可以考虑考虑

**Comment by hzcxdgioa** [comment]
@liuz430524 弹幕增强只是超过限制长度会帮你自动截断发送而已。
如果他可以做到支持特殊弹幕，那就超神了。至少需要有能力骇入主张服务器才行。。。。。

**Comment by liuz430524** [comment]
@hzcxdgioa 我说的是上面的建议/反馈3.1看番助手里的弹幕显示增强，不是弹幕发送增强，麻烦看清楚，而且我说的是支持显示特殊弹幕，为什么就和牛逼哄哄的骇入服务器有关了呢，你了解什么是特殊弹幕吗？而且只不过是mode7的特殊弹幕，并没有什么复杂的：
![image](https://cloud.githubusercontent.com/assets/8044101/16459434/53238132-3e55-11e6-938d-66cd0e255097.png)
方括号扩起来的那些就是，再对应一下这些属性，从零开始写一个也不是什么问题：
![image](https://cloud.githubusercontent.com/assets/8044101/16459267/cdeac570-3e54-11e6-830f-31ae6ac53382.png)
_[0,0,"1-1",4.5,"请使用电脑观看",0,0,862,0,3000,0,true,"黑体",1]_

何况这里有项目已经实现了 https://github.com/jabbany/ABPlayerHTML5 ，这里有示例 http://jabbany.me/ABPlayerHTML5/build/ 。
要说是解析显示mode8的高级弹幕才算麻烦，但和什么骇入服务器也没关系。

**Comment by hzcxdgioa** [comment]
@liuz430524 是我误解了。以为你说的是开发新的弹幕类型，可以发送出一些官方没有的弹幕样式，你这样说明白了，只是一个新的弹幕显示引擎而已。这样说应该没错吧。

**Comment by jjj201200** [comment]
@hzcxdgioa 新的弹幕形式，就算做出来也只有使用助手的人才能看到，也意味着助手需要开发自己的弹幕服务器，这目前来说是不可能的。

**Comment by jjj201200** [comment]
@liuz430524 看番助手的弹幕显示增强，相对于现在的显示问题进行增强。

**Comment by hzcxdgioa** [comment]
@jjj201200 所以我才说需要有骇入服务器的能力。不然拿着真没意义

**Comment by zacyu** [comment]
@jjj201200 @hzcxdgioa 我认为你们理解错了, @liuz430524 说的应该是官方本身就支持的 mode 7 高级弹幕. 弹幕显示使用的库本身就支持这类高级弹幕的, 发送的话其实应该也不是非常难做, 可以考虑一下. 另外我还是建议针对每个问题单开 issue, 而不是这样把一个 issue 作为讨论版用.

**Comment by jjj201200** [comment]
@zacyu 并没有啊，知道他说的什么额。另外这个issue是想告知一些目前的状况的，可以加入readme里吧，问题反馈依然是用单独issue
