### ISSUE TITLE
关于在乐视网看视频的时候会由于插件跳转播放器导致视频无法播放的问题

### ISSUE THREAD

**Issue by Satoshi-t** [zacyu/bilibili-helper#17]
对比IE和chrome做了测试，目测是由于乐视播放器跳转的问题。。。
IE下显示的是新版的播放器，但chrome下却是旧版的能在下面加弹幕框的那种。。。
广告屏蔽插件已关闭

**Comment by swordfeng** [comment]
乐视各种不服的。。。话说新版旧版是什么意思

**Comment by Satoshi-t** [comment]
新旧版是指乐视的播放器。。。就是说我正常在乐视网看视频的时候也会被跳转成乐视的旧版播放器，导致某些视频无法播放

**Comment by swordfeng** [comment]
意思是在乐视主站也起作用了？

- 发送自我的Sony Xperia™智能手机

---- Satoshi Takahashi 编写 ----

新旧版是指乐视的播放器。。。就是说我正常在乐视网看视频的时候也会被跳转成乐视的旧版播放器，导致某些视频无法播放

---
