### ISSUE TITLE
建议：在线获取解析地址

### ISSUE THREAD

**Issue by typcn** [zacyu/bilibili-helper#170]
建议将播放地址 URL 的 sign 放到服务端，客户端发送 cid ，服务器将最终拼接好的 URL 返回客户端，客户端访问该 URL 进行解析，防止换 key 被封造成潜在的问题，由于服务器不会给 B 站服务器发送任何请求，不会影响 CDN 分配，也可以防止服务器 IP 被封等情况

**Comment by Willian-Zhang** [comment]
這個請求會導致等待和第三方服務器的訪問性問題？

**Comment by ihatead** [comment]
這個實際上不難阿. 分析一下B站iOS客戶端. 基本上就有東西了.

**Comment by cccRaim** [comment]
可以使用定时检查的方式，可以加一个选项按钮是否参加这个方式

**Comment by Willian-Zhang** [comment]
@cccRaim 也可以考慮 push event？

**Comment by typcn** [comment]
你想多了，B站经常会无视key，根据别的参数把你 block 掉，甚至解析成功与否与参数的顺序都有关系。

还有生成 sign 用的参数和实际参数内容不一样

**Comment by typcn** [comment]
因为 Web 的限制实在是太多，你没法在客户端进行反编译/模拟执行 来同步，很多东西做不了
个人认为由服务器来签名播放地址是目前而言最好的方式

**Comment by typcn** [comment]
当然也有一个办法：
加个“更新解析”的按钮，点了之后从服务器上下载一段JS，存到 localStorage 里面，以后每次用这个解析

**Comment by cccRaim** [comment]
第三方服务器问题可以用CORS方案解决，等待倒不是问题，毕竟只是间歇性检查

**Comment by Willian-Zhang** [comment]
既然要「對 server 更新」那與「對 client 更新」沒有差別？

**Comment by typcn** [comment]
我刚刚的意思是说不能 push appkey  这样局限性还是太大， 直接 push 代码比较好
至于安全性。。加上 https ，起码比某站本体全程 http 安全

**Comment by cccRaim** [comment]
client更新需要等待chrome审核加上其他步骤，程序员的从简生活来看，应该是不喜欢这种频繁编译更新的方式

**Comment by typcn** [comment]
而且国内用户也并不能成功连接 chrome webstore ，自然无法更新咯。。

单独动态更新是最好的

**Comment by cccRaim** [comment]
类似支付宝远程获取代码的形式好像可行

**Comment by Willian-Zhang** [comment]
支持 JS 動態更新

**Comment by Willian-Zhang** [comment]
不過依然無法規避「需要手工 fo 官方的算法更新」的問題

**Comment by typcn** [comment]
这个当然。。
不过我做了一套自动的，必要的时候再拿出来吧
![image](https://cloud.githubusercontent.com/assets/8022103/15314446/6438dbe4-1c44-11e6-9dd7-856b97ed1e7d.png)

**Comment by ihatead** [comment]
但是你說封鎖key, 總不會頻繁到把自己的手持裝置客戶端的key也封了吧!

**Comment by typcn** [comment]
当然会，他们手机客户端的 key 都是装在 lua 里面的，客户端每次启动都从服务器上下载新的解析代码，所以换 key 是非常容易的，而且他们还没对代码做校验，一个 http 劫持就能在用户的手机上任意执行代码
