### ISSUE TITLE
前阵子B站大改播放器后..插件的所有功能就失效了

### ISSUE THREAD

**Issue by SummerSir666** [zacyu/bilibili-helper#173]
视频下载
视频地址获取中，请稍等…
弹幕发送者查询
正在加载全部弹幕, 请稍等…
Cid 获取失败
错误-1: app has been blocked.
Cid 获取失败
错误-1: app has been blocked.
(呐就是上面那一段...什么情况咧，插件是最新的)

**Comment by jjj201200** [comment]
见#162

**Comment by SummerSir666** [comment]
已经正常可用啦~

**Comment by jjj201200** [comment]
@SummerSir666 请关闭issue
