### ISSUE TITLE
请问一下自动签到和领瓜子的正确运行需要什么条件？

### ISSUE THREAD

**Issue by DaphnisNerii** [zacyu/bilibili-helper#175]
如题，
游览器版本Chrome 51.0.2704.79 m (64-bit)
页面缩放175%

不管是否停留在直播页面均不能自动签到&领瓜子
想问一下正确的使用姿势……

**Comment by nadokakun** [comment]
同問，昨天有意外搓出來一次過，還以為是老爺權限呢...
今天刷新好多次都沒辦法弄出自動領瓜子了

**Comment by jjj201200** [comment]
@DaphnisNerii @nadokakun 请加我qq：408523429，以方便进一步沟通确认导致问题的原因。

**Comment by jjj201200** [comment]
@nadokakun 请下载最新版本的库并构建crx文件来进行安装。

**Comment by ZCXLLOD** [comment]
@jjj201200 @nadokakun @DaphnisNerii 经测试，在同一直播间；不关闭浏览器重开；不切换到其他直播间；不清除浏览器缓存、痕迹；不重新登录；不切换到其他浏览器的前提下，需要点一下此书签（得添加到收藏夹中）：http://s.0w0.be/bsc/才能“激活”助手的自动领取瓜子的功能，但自动签到功能仍无法使用，由于助手的相关功能和那个书签的功能相冲突所以要刷新一下网页，刷新网页后书签的功能失效，刷新网页后助手自动领瓜子的功能还是可以用的。其他功能如何“激活”我还没发现，其他情况我也没有进行测试。

**Comment by jjj201200** [comment]
@ZCXLLOD 你好，对你遇到的问题感到十分抱歉，我们暂时还没有更新webstore上的版本，请下载master并用开发者模式载入最新的版本。之前的版本存在bug，之后我们已经进行修复是不需要其它任何操作或者工具来辅助。如果碰到问题，可以加我qq：408523429，我们详谈

**Comment by ZCXLLOD** [comment]
@jjj201200 非常感谢，使用最新的库后所有问题都解决了，辛苦了！其实360安全浏览器也是可以加载已解压的扩展程序的，输入：chrome://extensions-frame/，然后开启开发者模式即可。

**Comment by jjj201200** [comment]
@ZCXLLOD 好的，谢谢告知*smile*

**Comment by ZCXLLOD** [comment]
@jjj201200 You're welcome!
