### ISSUE TITLE
html5模式下的视频不是高清

### ISSUE THREAD

**Issue by troyliu0105** [zacyu/bilibili-helper#178]
html5终于可以用了，谢谢开发者。。。mac又凉快起来了
不过发现html5没有flash那么清晰，ai

**Comment by myfreeer** [comment]
#174
api的锅

**Comment by troyliu0105** [comment]
哎。。。是因为api的改动么？以前都还不错的。。。。。。真是囧

**Comment by abcfy2** [comment]
+1 如果这个问题有办法解决就太完美了

**Comment by zacyu** [comment]
Duplicate of #174.
