### ISSUE TITLE
v0.8.6关闭直播间开播推送功能无效

### ISSUE THREAD

**Issue by cccc7777** [zacyu/bilibili-helper#181]
关闭直播间开播推送功能，还是会接收到桌面推送通知。

**Comment by jjj201200** [comment]
@cccc7777 请问你使用的浏览器类型和版本

**Comment by jjj201200** [comment]
我已经检查过代码并明确问题所在，谢谢你的反馈，我们讲将会尽快修复

**Comment by ikamal** [comment]
修改设置后，停用再启用扩展，才停掉了心跳请求。
浏览器一直开着自动更新，所以扩展和chrome都是当时的最新版。

**Comment by jjj201200** [comment]
@ikamal 了解了，谢谢反馈
