### ISSUE TITLE
啥时候HTML5播放器能选择清晰度啊

### ISSUE THREAD

**Issue by qw4096** [zacyu/bilibili-helper#185]

**Comment by zacyu** [comment]
这个大概要等一段时间, 下一个里程碑更新的时候播放器会改版并加入这些选项.

**Comment by jjj201200** [comment]
@zacyu 我找到了一个可用的貌似是android客户端上的appkey，可以暂时解决这个问题，不过动态算sign可能才是根本解决办法。。等你出马:smile:

**Comment by qw4096** [comment]
@zacyu 好期待，对了，替换搜狐播放器以后会解决吗

**Comment by ihatead** [comment]
從playurl中可以看到有backup_url就是xxxhd(高清)了.
avPlaybackLink.durl[0].url = avPlaybackLink.durl[0].backup_url[0] ? avPlaybackLink.durl[0].backup_url[0] : avPlaybackLink.durl[0].url;
