### ISSUE TITLE
0.88 版本无法绕过地区限制

### ISSUE THREAD

**Issue by xupefei** [zacyu/bilibili-helper#187]
如题。升级 0.88 版本以后，国外看不了 BILIBILI 买的新番了。手动装回 0.87 版本后正常。

0.88 版本的表现是：无限停留在尝试替换播放器画面。如果不替换播放器，则出现黑屏白字的标准报错：非常抱歉本视频由于一下原因blablabla。

**Comment by jjj201200** [comment]
@xupefei 正在修复此问题

**Comment by zacyu** [comment]
找到原因之后大致说一下吧.

**Comment by jjj201200** [comment]
@zacyu 恩嗯

**Comment by zacyu** [comment]
@jjj201200 Ref: https://github.com/zacyu/bilibili-helper/blob/078964a96802f7f27fba57c8596e12ec091778c7/src/background.js#L864

**Comment by jjj201200** [comment]
@zacyu 这儿我已经加了的呀，但是有时有效有事没效果我不知道到怎么回事Orz
