### ISSUE TITLE
直播间好想要正则屏蔽0.0

### ISSUE THREAD

**Issue by maizhenying09** [zacyu/bilibili-helper#189]
https://greasyfork.org/zh-CN/scripts/14374-bilibili%E7%9B%B4%E6%92%AD%E5%87%80%E5%8C%96 之前用过这个直播间净化的脚本，如果助手也能加上正则屏蔽和左下角宝箱移出播放器就更吼了，嘻嘻。[嘻嘻]

**Comment by jjj201200** [comment]
呕天哪，一直不知道有这么强大的插件网站的存在诶，谢谢告知。也谢谢您的反馈，目前屏蔽功能刚刚推出，还存在一些问题和值得改进的地方。关于正则屏蔽，绝大多数用户都不会使用的吧，我们会将功能做得使用起来比较简单易懂。

**Comment by jjj201200** [comment]
宝箱移除播放器这个功能，我暂时加入"建议列表"，如果您是使用过哔哩哔哩助手的自动领瓜子功能的话，是会自动隐藏没有自动领取瓜子直播间的宝箱的，只有开启了该功能的直播间才会有宝箱，而且用户只需要点击宝箱右上角的叉号就可以缩小了，所以暂时不考虑这个功能，抱歉。

**Comment by maizhenying09** [comment]
噢，原来还有这种小细节~
屏蔽功能如果能有导入功能就好了，我的屏蔽列表都700多条了233
对了，特别关注的直播通知点击了“观看”之后通知不自动关闭~
还有下面这种情况，不清楚是不是我自己的问题(´･_･`)
http://7xrn7f.com1.z0.glb.clouddn.com/16-6-20/30072943.jpg
http://7xrn7f.com1.z0.glb.clouddn.com/16-6-20/30072943.jpg
辛苦了~

**Comment by jjj201200** [comment]
好的，谢谢反馈

**Comment by jjj201200** [comment]
@maizhenying09 我看了下，确实是助手导致的问题，我们会在下个版本进行修复。

**Comment by maizhenying09** [comment]
好的，辛苦啦~
