### ISSUE TITLE
助手的自动领取瓜子的功能有时候会失效

### ISSUE THREAD

**Issue by ZCXLLOD** [zacyu/bilibili-helper#190]
如题。具体是这样：有时候时间到了助手没有自动打开输入验证码的窗口，导致无法自动领取瓜子，手动打开后会自动输入验证码并确定。是什么原因导致的目前还没发现，360安全浏览器、360极速浏览器都出现过此问题，谷歌浏览器我这边用不了，一打开网页就卡住了，所以没法测试，我这边这个问题出现的概率很大，不得不用原来的那个书签，有时候还会出现网页提示领奖信息错误（概率较小），刷新网页才行，还有，建议加个开始领取和领取失败的提示。助手版本：v0.8.6，浏览器均为最新版。

**Comment by jjj201200** [comment]
你好现在版本0.8.8，请更新๛ก(ｰ̀ωｰ́ก)

**Comment by jjj201200** [comment]
不过0.8.8存在一个bug，请暂时在助手设置界面将弹幕增强功能去掉

**Comment by ZCXLLOD** [comment]
@jjj201200 .谢了&360浏览器里的助手还是0.8.6的，我挂VPN去谷歌应用商店才是0.8.8的。.。。0.8.8的出现问题的概率小多了，就是开弹幕增强后发一次弹幕再发就不行了。

**Comment by jjj201200** [comment]
是的，所以建议暂时关闭有问题的功能，非常抱歉
