### ISSUE TITLE
直播间瓜子自动领取失败

### ISSUE THREAD

**Issue by 1296548696** [zacyu/bilibili-helper#194]
最小化宝箱可以自动领取，但不这样做需要再点一下宝箱才能自动领取。360安全浏览器

**Comment by jjj201200** [comment]
@1296548696 请问您的助手版本是多少？

**Comment by 1296548696** [comment]
嗯，昨天刚更新的v.8.10，这个问题在v0.8.8的时候就出现了。然后还有问题就是如果有一次领取失败以后，即使手动（点宝箱）领取，提示的领取瓜子数量和失败前一致。我已经更新过浏览器，清空过缓存cookie。

**Comment by jjj201200** [comment]
@1296548696 万一出了问题，请刷新浏览器，然后重新等待
