### ISSUE TITLE
弹幕增强功能会导致无法选择下面的弹幕热词

### ISSUE THREAD

**Issue by feise** [zacyu/bilibili-helper#195]
弹幕热词那里，只要开启了弹幕增强以后就没办法下拉了，关闭了就可以了。
是冲突吗？不知道别人那里如何，在我这里只要开启了就没有了右侧下拉线了

[http://ww3.sinaimg.cn/large/0060lm7Tgw1f543ag8firj3062084mxj.jpg](http://ww3.sinaimg.cn/large/0060lm7Tgw1f543ag8firj3062084mxj.jpg)

**Comment by jjj201200** [comment]
@feise 谢谢反馈，这b站又给更新了，我们下个版本见23333
