### ISSUE TITLE
播放合集选集无效

### ISSUE THREAD

**Issue by Ouroboros** [zacyu/bilibili-helper#197]
http://bangumi.bilibili.com/anime/v/43422

比如这个, 无论选哪个都是第一集

**Comment by zacyu** [comment]
@jjj201200 I wouldn't recommend replacing player on pages like this. Instead, we might consider redirecting the user to actual (standard) playback page when one clicks on the button.

**Comment by jjj201200** [comment]
@zacyu after 7.6, i'll begin to recode/reform the project.

**Comment by jjj201200** [comment]
@Ouroboros b站已经把第二季的内容给屏蔽了？看不到集数

**Comment by Ouroboros** [comment]
@jjj201200 集数在下面

**Comment by jjj201200** [comment]
@Ouroboros 请问你是海外党吗？我这里昨天看下面都没有选项，今天就看到了，然后就是我这里倒是可以换集，我们也并没有对此进行什么改动，不知为何会这样

**Comment by Ouroboros** [comment]
@jjj201200 不是啊, 我在国内
试了下开不开代理都选不了

**Comment by jjj201200** [comment]
@Ouroboros 只有开助手的时候这样吗？

**Comment by Ouroboros** [comment]
对, 开启"HTML5优先"就100%重现, 关闭就正常

那天切换原版播放器也会失败, 就是播放器消失了, 原版的也没有出现, 得关掉HTML5优先才行
不过刚刚试了又能切换了

**Comment by jjj201200** [comment]
@Ouroboros =、=。那。。。先就这样吧。。
