### ISSUE TITLE
弹幕量过大ass无法下载

### ISSUE THREAD

**Issue by sftt** [zacyu/bilibili-helper#199]
- http://bangumi.bilibili.com/anime/v/85276
- http://www.bilibili.com/video/av4492528/

上面两个是同一个视频投稿，弹幕池8000/8000

> 弹幕发送者查询
> 正在加载全部弹幕, 请稍等…
> 弹幕下载
> 下载 XML 格式弹幕

XML可以下载，ASS下载按钮不显示。
或者是否有工具可以把XML转成ASS/SRT？
谢谢

**Comment by myfreeer** [comment]
尝试延迟加载ass
https://github.com/myfreeer/bilibili-helper/commit/f8d5b117f54d1465ac2797946dd9440a35ad00c7

**Comment by jjj201200** [comment]
谢谢反馈，这些问题7月中重构的时候一并解决

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新
