### ISSUE TITLE
有优酷视频替换播放器不成功

### ISSUE THREAD

**Issue by SilverBut** [zacyu/bilibili-helper#20]
av838670，优酷视频源，替换失败，表现是刚开始替换成b站播放器，然后就闪成了优酷播放器
助手版本0.6.9，chrome版本40.0.2214.115（官方版），Flash应该是自带的16.0.0.305

**Comment by siriulx** [comment]
我也一直有这个问题，关闭播放器切换无效，只能整体禁用插件

**Comment by zacyu** [comment]
@SilverBut av838670 是新浪源啊?

**Comment by zacyu** [comment]
@siriulx 麻烦提供一下出问题的视频的 av 号.

**Comment by siriulx** [comment]
比如av1436642 av1731191 视频信息能读取，视频地址读取失败

**Comment by zacyu** [comment]
@siriulx 我这边测试并没有遇到问题. 你发一下你访问 http://interface.bilibili.com/player?id=cid:2644075&aid=1731191 和 http://interface.bilibili.com/playurl?platform=bilihelper&otype=json&appkey=95acd7f6cc3392f3&cid=2644075&quality=4&type=flv 的结果?

**Comment by siriulx** [comment]
好吧，是我没好好测试，应该是B站的问题，我禁用了插件，还是无法正常播放。

    <ip>130.127.255.220</ip>
    <zoneid>402915328</zoneid>
    <country>美国</country>
    <isp></isp>
    <login>true</login>
    <name>siriulx [美国]</name>
    <user>235926</user>
    <scores>15255</scores>
    <money>518.7</money>
    <face>http://i0.hdslb.com/user/2359/235926/myface.jpg</face>
    <pwd>undefined</pwd>
    <isadmin>false</isadmin>
    <permission>10000,1001</permission>
    <time>1439888758</time>
    <rank>10000</rank>
    <level>正式会员</level>
    <shot>false</shot>
    <suggest_comment>false</suggest_comment>
    <maxlimit>3000</maxlimit>
    <chatid>2644075</chatid>
    <server>chat.bilibili.com</server>
    <vtype>youku</vtype>
    <oriurl>http://v.youku.com/v_show/id_XODMxMjQ4Mjg4.html</oriurl>
    <aid>1731191</aid>
    <typeid>63</typeid>
    <pid>1</pid>
    <click>4240</click>
    <favourites>11</favourites>
    <credits>0</credits>
    <coins>14</coins>
    <fw_click>1824</fw_click>
    <duration>17:50</duration>
    <arctype>Original</arctype>
    <danmu>235</danmu>
    <bottom>0</bottom>
    <sinapi>1</sinapi>
    <acceptguest>true</acceptguest>
    <acceptaccel>true</acceptaccel>
    <cache>true</cache>
    <rgg img="http://acg.tv/uDc" rggnum="1" url="http://acg.tv/uDb" c="1" />
    <honor d="1416585600" t="coins">392</honor>
    <honor d="1416585600" t="click">912</honor>
====
    {"error_code":"E101","error_text":"API调用失败.HTTP_TIMEOUT218.95.101.94"}

**Comment by zacyu** [comment]
@siriulx 嗯, 我这边也是时不时 timeout, 应该是 B 站或者优酷的无误, 我先关了.
