### ISSUE TITLE
可否适当格式化一下消息通知，或者增长显示时间

### ISSUE THREAD

**Issue by hzcxdgioa** [zacyu/bilibili-helper#200]
如果chrome的通知可以自定义进行格式化的 话，
希望可以将消息尽可能显示关键信息，做一下格式整理。
如果通知不能够自定义的话，也可以稍微加长一下显示时长。
我就只希望通知显示
是由谁发送的，
是什么视频名称
就可以了，
一大段话看起来显得有些没有效率。

**Comment by jjj201200** [comment]
啊你的建议挺不错的，我们在之后的重构中会考虑一下。:smile:
