### ISSUE TITLE
助手不能替换SWF播放器了

### ISSUE THREAD

**Issue by ZCXLLOD** [zacyu/bilibili-helper#202]
如题，好像B站把原来的播放器给取了，能不能加上呢？浏览器：350安全浏览器和360极速浏览器，助手版本：v0.8.10

**Comment by jjj201200** [comment]
@ZCXLLOD swf。。不是早就不能用了么？不是很懂。。

**Comment by ZCXLLOD** [comment]
@jjj201200 怎么我上个星期还能用的？那时候B站还没有彻底取消旧版的播放器。现在不能用能不能加上呢？
