### ISSUE TITLE
助手会屏蔽腾讯统计 tajs.qq.com

### ISSUE THREAD

**Issue by nagatoyk** [zacyu/bilibili-helper#205]
RT
不晓得为什么要屏蔽

**Comment by myfreeer** [comment]
https://github.com/zacyu/bilibili-helper/blob/master/src/background.js
第840-846行，自行去除即可

**Comment by myfreeer** [comment]
Solved in https://github.com/zacyu/bilibili-helper/commit/ea94fd709a6622843e19fbeacbdf26d67aed0cd4

**Comment by jjj201200** [comment]
。。。。诶昨晚真是被那个https搞混了，有个地方忘记去掉了
