### ISSUE TITLE
播放某些视频只能低清

### ISSUE THREAD

**Issue by Ouroboros** [zacyu/bilibili-helper#209]
比如
http://www.bilibili.com/video/av1608918/index_11.html

**Comment by myfreeer** [comment]
h5: 167.62MB
swf（超清）: 168.33MB
似乎未能复现

**Comment by Ouroboros** [comment]
http://cn-gdjm2-dx.acgvideo.com/vg6/e/26/2445695.mp4?expires=1468215900&ssig=FGJkC9CMlU1a4hN_Nc2x2Q&oi=244858954&appkey=86385cdc024c0f6c&or=2061576138&rate=0

复制视频链接是这个

**Comment by myfreeer** [comment]
试试取消注释https://github.com/zacyu/bilibili-helper/blob/master/src/background.js#L251-L258

**Comment by Ouroboros** [comment]
我现在改用官方的HTML5的播放器了
