### ISSUE TITLE
自动领瓜子 显示跨域是什么鬼

### ISSUE THREAD

**Issue by pzwl** [zacyu/bilibili-helper#212]
bilibili_live.min.js:formatted:815 Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.img.onload.img.onload 

Live.treasure.question = Live.treasure.correctQuestion(OCRAD(Live.treasure.context.getImageData(0, 0, 120, 40))),

**Comment by jjj201200** [comment]
人家改了域名呗，貌似昨晚8-9点改的
