### ISSUE TITLE
【助手的直播间自动领瓜子功能失效】

### ISSUE THREAD

**Issue by ZCXLLOD** [zacyu/bilibili-helper#213]
如题，经测试，今天360浏览器和360极速浏览器都是这样，昨天晚上还是可以的，谷歌浏览器因为打开网页就卡所以没有测试，具体情况就是到了时间自动打开输入验证码的窗口但没有自动输入验证码，清除浏览器缓存、痕迹无效。助手版本：v0.8.10。

**Comment by jjj201200** [comment]
谢谢你的反馈，昨晚已经发现问题，原因是b站方面导致的，目前正在尝试修复。由于b站方面最近更新频繁，我们会尽可能在该问题得到充分解决后进行新版本推送，请等待更新，谢谢

**Comment by ZCXLLOD** [comment]
@jjj201200 恩，感谢回复，辛苦了！PS：You're welcome!
