### ISSUE TITLE
多账号参与抽奖，希望在消息中追加用户名便于区分。

### ISSUE THREAD

**Issue by hzcxdgioa** [zacyu/bilibili-helper#214]
冰雹雨抽奖太频繁了，我自己写的脚本手动输入太累人了，果然自动化操作就是省心啊，还能一个不漏，。
不过现在就是必须要多开网页才能维持多个账号，
但是看下面通知却只显示一个，一开始根本搞不清有没有成功参与抽奖，所以希望可以兼容一下多开账号的情况。

**Comment by jjj201200** [comment]
@hzcxdgioa 请问你是如何实现一个浏览器同时登录多账号的嘛

**Comment by hzcxdgioa** [comment]
@jjj201200  隐身模式，建用户都可以，追加显示用户名就可以区别了。
目前发现多开有点不稳定的样子，
为什么显示的提示不一样啊，一个显示是在该房间已开启监控功能，一个显示是监控功能在xx的直播间启动。这个有什么区别啊。

**Comment by hzcxdgioa** [comment]
@jjj201200 确实不能兼容多用户，点进去，只有一个是已抽奖状态。
而且，点进去后的提示用户名已经变了。隐身模式会窜用户。

**Comment by jjj201200** [comment]
@hzcxdgioa 请使用多个浏览器分别登陆不同账号来实现你的想法。我并不打算也不能实现一个浏览器多个账号同时登陆的功能。
