### ISSUE TITLE
直播夏季活动弹出试试我的手气

### ISSUE THREAD

**Issue by jackiejtr** [zacyu/bilibili-helper#215]
突然无法彻底后台领取刨冰活动了 还有希望向助推器一样增加替换视频源的功能 这样可以直接放无修 结合B站弹幕 感谢作者！！！

**Comment by jjj201200** [comment]
把后台错误信息发上来

**Comment by jjj201200** [comment]
咕咕的实习比较忙，看番播放器暂时不会更新。
