### ISSUE TITLE
海外观看“仅限港澳台/台湾”等区域限制视频失效

### ISSUE THREAD

**Issue by Yuuon** [zacyu/bilibili-helper#216]
上一更新前：部分视频会出现替换播放器框架后，播放器本身却没有载入的问题
本次更新后：所有港澳台区域限制视频无法进行替换页面，进入没有找到视频提示页后即结束，助手插件未能正常工作
已确认并无其他代理类插件干扰

**Comment by jjj201200** [comment]
能给一下出问题了的视频地址吗

**Comment by zacyu** [comment]
@Yuuon 非常抱歉, 我们在压缩代码时一个错误的配置导致了不能正确地加载替换页. 请等待我们下一个版本的更新, 谢谢.
