### ISSUE TITLE
转换的页面不能加载

### ISSUE THREAD

**Issue by sviivs1** [zacyu/bilibili-helper#217]
比如av643053
原本只要bilibili-helper 自动转换页面就能看，但在"需要新权限"后就全部类似的视频的页面都不能转换了.
是"新权限"的问题吗?

**Comment by jjj201200** [comment]
你好，我看了下，这好像是需要跳转到其他页面进行观看的。下次碰到这种问题你可以暂时在助手设置页面，把播放器切换功能关闭，然后等待我们的修复，抱歉。

**Comment by zacyu** [comment]
@jjj201200 please see #218

**Comment by zacyu** [comment]
@sviivs1 非常抱歉, 我们在压缩代码时一个错误的配置导致了不能正确地加载替换页. 请等待我们下一个版本的更新, 谢谢.
