### ISSUE TITLE
最近直播间自动领瓜子好像不能用了，不知道是我电脑问题，还是B站更新过之类的

### ISSUE THREAD

**Issue by Railgun0502** [zacyu/bilibili-helper#220]
最近直播间自动领瓜子好像不能用了，不知道是我电脑问题，还是B站更新过之类的..

**Comment by jjj201200** [comment]
抱歉由于设计上的缺陷，目前需要在开启助手的直播间监控功能后，自动领瓜子功能才能正常工作。

**Comment by pengxingjun** [comment]
我前几天还能自动领的，这几天突然不行了，问下这个“直播间监控”是怎么开的？

**Comment by jjj201200** [comment]
@pengxingjun 在助手设置页面里有选项
