### ISSUE TITLE
能否增加开关控制隐藏抽奖/抽奖结果通知

### ISSUE THREAD

**Issue by quericy** [zacyu/bilibili-helper#221]
抽奖通知还是略频繁的,
但是又不想通过chrome统一控制,因为关注通知还是想展示的
所以是否能增加设置开关,控制隐藏/现实抽奖相关的通知

**Comment by jjj201200** [comment]
请看 #220

**Comment by quericy** [comment]
可能表述上有偏差。
我的意思是在**开启直播间监控**选项的前提下，
添加一个**抽奖结果不弹窗**选项。参与抽奖，但是不显示下面的弹窗:
![如图](http://i.imgur.com/XfaJj2b.png)

似乎和[#220](https://github.com/zacyu/bilibili-helper/issues/220)没有太大的关联?

Please reopen this issue.Thanks~

**Comment by jjj201200** [comment]
@quericy = =诶好奇怪啊。。我可能在同时回复几个issue时搞混了吧。。你的建议很好，我会考虑添整合一下助手里所有通知功能的统一选项设置
