### ISSUE TITLE
希望添加日志功能，统计小电视抽奖获得多少瓜子，谢谢

### ISSUE THREAD

**Issue by 294007813** [zacyu/bilibili-helper#222]

**Comment by jjj201200** [comment]
@294007813 这个问题我已经在考虑了。只是直播间太乱东西太多了，我在想要不要自己出一个直播间风格。你觉得呢

**Comment by 294007813** [comment]
现在直播间确实眼花缭乱的
直播间目前貌似没有关灯功能，如果加上这个功能，界面应该会一下子干净了

**Comment by neroc7** [comment]
我也同意，更喜欢干净的直播间

**Comment by Blackdogman** [comment]
能够优化一下直播的发热么？现在笔记本都不敢看直播。。

**Comment by jjj201200** [comment]
@Blackdogman 你好，电脑散热的问题还请就硬件上寻找解决途径，谢谢
