### ISSUE TITLE
无法在直播间自动领瓜子

### ISSUE THREAD

**Issue by ForeverLive** [zacyu/bilibili-helper#224]
只会自动弹出填数字领瓜子的框 不会自动填写数字...

**Comment by jjj201200** [comment]
@ForeverLive 请开始直播间的监控功能能

**Comment by ForeverLive** [comment]
@jjj201200 都开了 这一周以来都是这样子的

**Comment by jjj201200** [comment]
@ForeverLive 助手版本是最新的0.8.12吗

**Comment by Railgun0502** [comment]
0.8.12在哪里下载？我是0.8.10- -找不到更新

**Comment by jjj201200** [comment]
我微博里找

**Comment by Railgun0502** [comment]
@jjj201200 好的谢谢

**Comment by ForeverLive** [comment]
@jjj201200 0.8.11的 我更新下12试试

**Comment by AnnAngela** [comment]
@jjj201200 我也是，更新到0.8.12还是，报错信息【bilibili_live.min.js:2 Uncaught SecurityError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.】

**Comment by gu396433839** [comment]
同楼上，貌似是昨天才刚改的，修复一下

**Comment by Seraphli** [comment]
我也是同样的问题,应该是这次直播间更新之后瓜子的箱子会自动隐藏了,然后导致助手领瓜子的时候少一个步骤了.

**Comment by cccRaim** [comment]
![image](https://cloud.githubusercontent.com/assets/7681138/17277222/2da92608-5770-11e6-8981-0a234a1271eb.png)

**Comment by jjj201200** [comment]
@cccRaim 更新到最新版，打开直播监控功能，我上面不是说过了么

**Comment by cccRaim** [comment]
居然又多出个选项- -关键没提示啊，在直播间也没提示已关闭这个监控功能，直播间上还提示已开启自动领瓜子功能，我还以为是正常开启的
