### ISSUE TITLE
自动领瓜子组别识别错误

### ISSUE THREAD

**Issue by FYPetro** [zacyu/bilibili-helper#226]
在目前的版本中：

- 3分钟宝箱结束后实领30瓜子却显示领取190瓜子；
- 6分钟宝箱结束后实领80瓜子却显示领取30瓜子；
- 10分钟宝箱结束后实领190瓜子却显示领取80瓜子；
- 最后一组中的10分钟宝箱无法自动领取。

**Comment by jjj201200** [comment]
这个问题我也发现了

**Comment by jjj201200** [comment]
谢谢反馈啦ヾ(=ﾟ･ﾟ=)ﾉ

**Comment by FYPetro** [comment]
嗯，辛苦啦
