### ISSUE TITLE
360极速浏览器上有助手扩展 不知道是不是官方放上去的……

### ISSUE THREAD

**Issue by lzh77** [zacyu/bilibili-helper#227]
如果是官方提交的，麻烦可以更新吗……现在不是最新版并不能自动领瓜子

https://ext.chrome.360.cn/webstore/detail/kpbnombpnpcffllnianjibmpadjolanh

**Comment by jjj201200** [comment]
请去翻我微博，找一条发了离线版本下载链接的微博，下载并安装，如何安装请百度或者谷歌查一下谢谢
