### ISSUE TITLE
自动抽奖不知道什么原因会有些不稳定，有时会有遗漏。

### ISSUE THREAD

**Issue by hzcxdgioa** [zacyu/bilibili-helper#229]

**Comment by jjj201200** [comment]
连击目前只能抽第一次（貌似）

**Comment by hzcxdgioa** [comment]
是不知道连击的数据结构吗还是什么情况？
另外获取房间非短号号码，可否换一种方式，会在后台会打开一次网页的。

**Comment by hzcxdgioa** [comment]
但是我是有一个账号能够参与到，另一个账号的就错过了。不是很稳定啊，感觉

**Comment by jjj201200** [comment]
获取页面是为了得到roomId，这个版本中连击只能领取第一个，之后会修复。至于你说的获取roomId的方法，有什么建议的嘛？按理说后台获取页面并不会影响用户，只有没有存储得才会获取。

**Comment by jjj201200** [comment]
@hzcxdgioa 另外一个浏览器同时登录多个账号，数据会混乱出错。建议使用不同浏览器登录不同账号

**Comment by hzcxdgioa** [comment]
chrome可以切换用户的

**Comment by jjj201200** [comment]
你切换账户之后他数据不会互串吗？我没试过，按理说是会的吧

**Comment by hzcxdgioa** [comment]
不会，设置里的其他人中可以添加用户。都是独立的

**Comment by jjj201200** [comment]
你说的我都知道，但是你怎么知道数据不会互串那？我这里单个账号从来没有出过问题，你用过个浏览器试试看问题还有没有吧

**Comment by FYPetro** [comment]
今天出现了一个340连抽的刨冰，结果只抽了1次。_(:3」∠)_

**Comment by hzcxdgioa** [comment]
100个才一次抽奖吧，你怎么算的啊
