### ISSUE TITLE
开启扩展后无法正常全屏

### ISSUE THREAD

**Issue by lich13** [zacyu/bilibili-helper#230]
开启和未开启对比 注意左上边框 chrome和扩展版本都是最新
![default](https://cloud.githubusercontent.com/assets/10644698/17133580/418fc872-5359-11e6-8bcb-9ed33f63df47.PNG)
![2](https://cloud.githubusercontent.com/assets/10644698/17133591/5202ee28-5359-11e6-81a2-321b589d70ca.PNG)

**Comment by jjj201200** [comment]
请问现在还有这个问题吗
