### ISSUE TITLE
宝箱經常倒數時間顯示 NaN:NaN

### ISSUE THREAD

**Issue by brina60602** [zacyu/bilibili-helper#232]
如:  宝箱倒计时 (｀･ω･´) 距离本次领取剩余 NaN:NaN 本次宝箱收益

**Comment by jjj201200** [comment]
这个问题和b站前端的异常处理有关了，助手只是一种模拟点击模拟填写答案的作用，其他都不是助手能够左右的

**Comment by hzcxdgioa** [comment]
计时不能继续进行是什么问题？
每次都要重刷新，
领取一次后不进行下一次计时，而且想手动输入都无解

**Comment by brina60602** [comment]
今天發現倒數計時正常了，但到00:00時並沒有自動領，自己按時寶箱跳出3秒就自己縮回去了，這根本是在練手速(╯°口°)╯(┴—┴
(換ie倒是可以領)

**Comment by brina60602** [comment]
流覽器清已經資料了，難道要刪掉重裝ヽ(´･д･｀)ﾉ？

**Comment by hzcxdgioa** [comment]
看来b站是在反外挂

**Comment by jjj201200** [comment]
不是反外挂，他们在更改规则而已，感觉像是换了人做这件事。

**Comment by ZCXLLOD** [comment]
规则确实改了，之前开两个直播间只有一个直播间能领瓜子，这样可以开多个直播间还不用担心瓜子领不到，但今天又给改回来了。。。。
