### ISSUE TITLE
自动领瓜子的功能突然又抽风了....

### ISSUE THREAD

**Issue by ForeverLive** [zacyu/bilibili-helper#233]
刚才开始就一直处于时间到00：00 不会自动领瓜子 自己点开如果几秒内没填答案小窗口会收回去 填了点确定会没反应....然后只能关了领瓜子功能自己领

**Comment by jjj201200** [comment]
谢谢您的反馈，请耐心等待更新

**Comment by ZCXLLOD** [comment]
今天我这边也是这样，昨天还行的说。

**Comment by RainInFall** [comment]
倒计时div的class变动，.count-down-node.count-down。

**Comment by jjj201200** [comment]
改动没那么简单，我已经解决好，请等待推送更新

**Comment by JACKFIRST** [comment]
+10086 刚刚也发现了
