### ISSUE TITLE
直播间右方聊天窗口被挡住

### ISSUE THREAD

**Issue by RuioWolf** [zacyu/bilibili-helper#234]
![qq 20160804021643](https://cloud.githubusercontent.com/assets/15277799/17376794/af10c9b4-59e9-11e6-9268-e1fa264df45e.png)
就是有时候有些字会被那个上下拖的条挡住

**Comment by jjj201200** [comment]
恩恩，看来得改的稍微窄一些，谢谢反馈:smile:
