### ISSUE TITLE
希望兼容Firefox 48+的WebExtensions和新版Edge

### ISSUE THREAD

**Issue by SquallATF** [zacyu/bilibili-helper#235]
Firefox开始支持WebExtensions了，但是部分api还未实现，我尝试用Firefox的Chrome Store Foxified插件安装helper发现并无法使用～
目前发现的一些问题是由于chrome里一些被废弃的api在Firefox中不被支持引起的
比如
[chrome.tabs.getSelected](https://developer.chrome.com/extensions/tabs#method-getSelected) 从chrome 33开始标记为废弃
建议替换成[chrome.tabs.query](https://developer.chrome.com/extensions/tabs#method-query) 从chrome 16开始支持

**Comment by Love4Taylor** [comment]
刚尝试转制成EDGE扩展，直播有些问题，其他还没试

![](http://ww4.sinaimg.cn/large/005GmrUUgw1f6jzh7gdemj311y0kg49b.jpg)
![](http://ww4.sinaimg.cn/large/005GmrUUgw1f6jzhi7qm3j311y0kgq8g.jpg)
![](http://ww1.sinaimg.cn/large/005GmrUUgw1f6jzhqsh3jj311y0kgq4z.jpg)

**Comment by SquallATF** [comment]
firefox改了代码也能用，不过港澳台无法播放

**Comment by quericy** [comment]
同希望增加对Edge的支持

**Comment by jjj201200** [comment]
欢迎移植

**Comment by fanthos** [comment]
能不能把修改后的扩展的代码传到github上看看？

**Comment by jjj201200** [comment]
0.8.16.20开始兼容firefox
