### ISSUE TITLE
直播间无法自动领瓜子

### ISSUE THREAD

**Issue by IkarosScarlet** [zacyu/bilibili-helper#236]
开启自动领瓜子后无法领取瓜子，甚至手动领瓜子也会受到影响

**Comment by jjj201200** [comment]
0.8.12版本因为b站队宝箱模块重新写了一个版本导致失效，0.8.14版本中可以自动领了

**Comment by gu396433839** [comment]
0.8.14版本有一定机率也会这样，我看了下应该是验证码计算错误（或者说是识别错误），然后就一直卡在领取中，没法领下一波（其实就算不开助手，手动领，验证码正确，有时候也会报错），希望改进下，避免领取失败后要重新刷新网页才重新计时，可以设置下领取超时自动重试，再不行就自动重新计时宝箱

**Comment by jjj201200** [comment]
不是验证码错误，助手的验证码计算几乎都是正确的。我昨晚一直在检查导致这个问题的原因。至今没有找到，唯一能做的就是在错误发生的时候重新再走一边流程，重新获取验证码并计算提交。目前没有碰到问题

**Comment by jjj201200** [comment]
@gu396433839 昨晚已经排除了验证码错误的情况，只是单纯地b站对请求返回了一个领取失败的消息，我这里是挪用他们自己的处理代码，竟然卡住了。b站前端的锅

**Comment by gu396433839** [comment]
@jjj201200 目前不会自动重走流程，要是你开着直播间后台挂机，不一定就第一时间发现卡住的问题，最好可以加入自动重走流程的功能，还有，其实有个宝箱bug，怕被官方知道，我就不说了

**Comment by jjj201200** [comment]
@gu396433839 我现在本地改进了

**Comment by jjj201200** [comment]
@gu396433839 说啊。。。

**Comment by gu396433839** [comment]
@jjj201200 就是重置5轮宝箱后（老爷），手机端打开下直播间，刷新PC端，宝箱会重新恢复计时（领完一轮后要重新用手机端触发），从而实现PC端领取手机端才能享受的+2轮奖励

**Comment by jjj201200** [comment]
@gu396433839 这样啊，那也不算是bug了
