### ISSUE TITLE
哔哩哔哩助手和其他扩展起冲突。

### ISSUE THREAD

**Issue by Neillll** [zacyu/bilibili-helper#237]
Stealth Mode是个保护隐私的扩展
https://chrome.google.com/webstore/detail/stealth-mode/hfkpddhkjcbfmnclailpehabmekgphfh?utm_source=chrome-app-launcher-info-dialog
chrome提示和它起冲突，提示以下。 
警告：
此扩展程序无法修改网络请求的请求标头“X-Forwarded-For”，因为这一修改与另一个扩展程序（Stealth Mode）产生了冲突。

**Comment by mmliar** [comment]
请求标头这个冲突与很多插件都有冲突，最常用的要数海外的Unblockyouku了。在这个问题解决之前，建议使用Disconnected Me (https://chrome.google.com/webstore/detail/jeoacafpbcihiomhlakheieifhpjdfeo) + Https everywhere (https://www.eff.org/https-everywhere) 并在 ABP 里添加 Easy Privacy 以达到最好的效果。

**Comment by myfreeer** [comment]
Seems to be solved in https://github.com/zacyu/bilibili-helper/commit/3c22447bc90c58fb6c25f046dbfe65355765f3cb

**Comment by jjj201200** [comment]
重新上传了，昨晚回溯的时候忘记改了，0.8.16.17应该没有这个问题了

**Comment by Neillll** [comment]
请问0.8.16.17版会更新到Chrome web store吗？

**Comment by jjj201200** [comment]
@Neillll 不会，之后会直接跳到0.9版本，在此之前所有都为测试版本，不会出现在商店。而0.9将以ng2重构整个项目，带来更多功能（不包括已经声明不再维护的功能）
