### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by evrmji** [zacyu/bilibili-helper#238]
能不能把“该房间已开启监控功能”这一列移动到直播间的右边，不然小屏的电脑用户的“该房间已开启监控功能”这列字会被B站的侧边栏挡住...........对强迫症不友好，希望优化一下

**Comment by jjj201200** [comment]
@evrmji 恩，很中肯的建议。

**Comment by evrmji** [comment]
@jjj201200 好像特别关注还有点问题，有时候会不显示已经特别关注（在直播间页面上，但是助手的相关功能还是正常的，从助手的设置界面里也可以看到已经关注（如果点的特别关注））。然后如果单独点特别关注，B站系统不会显示已关注（应该不需要管吧，就当作悄悄关注~）

**Comment by jjj201200** [comment]
@evrmji 并不是，需要用户关注之后特别关注才有效
