### ISSUE TITLE
海外党无法看番

### ISSUE THREAD

**Issue by wingwinder** [zacyu/bilibili-helper#239]
打开页面时播放器会闪三四次，应该是在替换播放器，然后就看不到了……刷出来过一次，然后又因为更换播放器就刷不出来了。

**Comment by wingwinder** [comment]
然后刷出来了……？感觉不稳定，不知道为什么……

**Comment by IkarosScarlet** [comment]
去加个unblock bilibili 或是unblock youku扩展程序就行了

**Comment by wingwinder** [comment]
研究了一下，发现unblock bilibili和播放器自动替换有冲突所以刷不出来……谢谢
