### ISSUE TITLE
从昨晚开始，小电视和刨冰无法自动领取了。。

### ISSUE THREAD

**Issue by mlisry** [zacyu/bilibili-helper#241]
大概7，8点左右的样子。。 瓜子也一直显示[领取中...] 不会自动领取
重新装过插件也重启过浏览器了。。一直不领取，今天打开之后还是不行T.T，不过瓜子又可以自动领了~\(^0^)/

**Comment by jjj201200** [comment]
http://pan.baidu.com/s/1mi4LLG0
试试这个，之后留言一下使用结果。

**Comment by mlisry** [comment]
@jjj201200 抱歉回晚了... 可以了！！刨冰/小电视/签到/领瓜子都可以自动了~\(^0^)/ 
就是那包[去污粉]的图标不显示了... 不过点击原本[去污粉]的位置还是可以弹出来屏蔽选项卡2333

另外我昨天中午升级了win10，之后就不可以了...虽然不知道有没有关系..不过还是提一下啦><

**Comment by jjj201200** [comment]
http://pan.baidu.com/s/1eRCPt30
这个版本应该能解决你的问题，记得反馈哦~

**Comment by RuioWolf** [comment]
用了t2以后我这边似乎问题解决了，求推送更新

**Comment by mlisry** [comment]
嗯嗯~~ 用这个之后领瓜子大成功(^0^)/ ~~
