### ISSUE TITLE
跨地区观看替换浏览器后经常失败？

### ISSUE THREAD

**Issue by nixgnot** [zacyu/bilibili-helper#243]
具体表现是替换浏览器，加载完成后，整个播放器都消失了
![qq 20160805225907](https://cloud.githubusercontent.com/assets/20860979/17440702/42cb7c9a-5b60-11e6-9efb-2df6e5c3fa9c.jpg)

**Comment by zacyu** [comment]
Thanks for your input. Duplicate of #240.
