### ISSUE TITLE
0.8.14更新后所有新番全部看不了

### ISSUE THREAD

**Issue by aabccd** [zacyu/bilibili-helper#245]
海外党，最新版助手存在以下问题：
1、新番全部无法播放，无论是替换播放器还是刷新都没用
2、无法加载下载地址
3、更换播放器会出现自动返回原播放器的情况

**Comment by zacyu** [comment]
Thanks for your input. Duplicate of #240.

**Comment by deletearly** [comment]
以前的版本也存在这个问题，我是因为这个 去升级到了0.814也没有任何改善
