### ISSUE TITLE
自动领瓜子不行了欸

### ISSUE THREAD

**Issue by Cansll** [zacyu/bilibili-helper#248]
自动领瓜子的按钮一直卡在领取中，然后发现验证码（计算结果）那里数是错的。。。

**Comment by Cansll** [comment]
好吧换个直播间就没这个问题了。。。

**Comment by jjj201200** [comment]
关注我的微博@没睡醒的肉啊 看置顶微博 下载并安装 这是测试版本 解决了这个问题，测试版反馈没问题之后我将推送更新

**Comment by jjj201200** [comment]
@Cansll 你的问题是由于b站改了宝箱的规则

**Comment by Cansll** [comment]
哦哦，我试试
