### ISSUE TITLE
希望支持一键下载同一AV号下的多P视频

### ISSUE THREAD

**Issue by yfr199209** [zacyu/bilibili-helper#251]
RT，方便补番时快速下载多个视频

**Comment by myfreeer** [comment]
just use [you-get](https://github.com/soimort/you-get)
`set max=(Maximum page number here)`
`set av=avXXXXXXXX`
`for /l %i in (1,1,%max%) do you-get http://www.bilibili.com/%av%/index_%i.html`

**Comment by yfr199209** [comment]
Thanks, but I am no programmer, and I am not clear how to apply what you told me, sorry.

________________________________

**Comment by myfreeer** [comment]
@yfr199209 
https://github.com/soimort/you-get/releases/latest
https://github.com/soimort/you-get/releases/download/v0.4.523/you-get-0.4.523-win32-full.7z
![youget](https://cloud.githubusercontent.com/assets/17702502/17580554/125fc63a-5fd2-11e6-92a2-357094b14da8.PNG)

**Comment by jjj201200** [comment]
该功能已经有了~
