### ISSUE TITLE
在github里下载的压缩包解压后无法被加载

### ISSUE THREAD

**Issue by RuioWolf** [zacyu/bilibili-helper#255]
![sp160808_210925](https://cloud.githubusercontent.com/assets/15277799/17480827/6a1a84be-5dac-11e6-9627-d1514576e924.png)
每次关了Chrome再开他就会禁用掉0.8.15。。好麻烦的。。。不知道直接加载已解压拓展程序有没有用。。

**Comment by jjj201200** [comment]
见 #256

**Comment by myfreeer** [comment]
将src\xxx.js改名为src\xxx.min.js
或者使用[白名单工具](https://github.com/myfreeer/enableallExtensions)
