### ISSUE TITLE
直播间突然不能参与小电视等抽奖活动了

### ISSUE THREAD

**Issue by evrmji** [zacyu/bilibili-helper#256]
RT，不知道是我电脑/浏览器的问题还是
![qq 20160808213051](https://cloud.githubusercontent.com/assets/20814857/17481384/84ee7158-5daf-11e6-847d-067669d3c5c4.png)
B站又改动了什么还是我的账号出问题了....
![qq 20160808213252](https://cloud.githubusercontent.com/assets/20814857/17481409/b1c9c830-5daf-11e6-8e62-fe829cd0b5ca.png)
电脑重启过，但没用，cookie，缓存清理过，插件重装过，就差换系统...
求解...

**Comment by jjj201200** [comment]
助手是什么版本？

**Comment by jjj201200** [comment]
http://pan.baidu.com/s/1jIsELkM 试试这个版本，该版本为测试版，未在chrome商店商家，如果可以用或者不可以用，都请反馈一下谢谢

**Comment by evrmji** [comment]
@jjj201200 
![233](https://cloud.githubusercontent.com/assets/20814857/17502394/06f3dc50-5e1a-11e6-873d-f3d8c1a88bdf.png)

**Comment by jjj201200** [comment]
http://pan.baidu.com/s/1c2JVy96

**Comment by evrmji** [comment]
谢谢，正常了

**Comment by ChowhaoHQD** [comment]
0.8.15.3在chrome dev 54.0.2824.0 dev-m (64-bit) win10 安装后闪退 提示损坏 无法修复

**Comment by jjj201200** [comment]
请不要使用开发版或测试版浏览器，用稳定版chrome

**Comment by ChowhaoHQD** [comment]
@jjj201200 谢谢耐心解答
