### ISSUE TITLE
会跟Tampermonkey里的自动宽屏插件冲突，造成失效

### ISSUE THREAD

**Issue by jkingben** [zacyu/bilibili-helper#258]
哔哩助手什么时候能自带一个自动宽屏呢？
目前用了助手就没法用Tampermonkey里的宽屏插件

**Comment by myfreeer** [comment]
请给出"自动宽屏插件"的有效链接

2016-08-12 19:49 GMT+08:00 jkingben <notifications@github.com>:

**Comment by jkingben** [comment]
https://greasyfork.org/zh-CN/scripts/21284-%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9-bilibili-com-%E6%92%AD%E6%94%BE%E5%99%A8%E8%B0%83%E6%95%B4

**Comment by jjj201200** [comment]
下个版本将添加自动宽屏功能

**Comment by jjj201200** [comment]
this feature is added in 0.8.16.25
