### ISSUE TITLE
HTML5播放器部分番剧无法播放

### ISSUE THREAD

**Issue by eveouyang** [zacyu/bilibili-helper#259]
点击播放后播放按键变成正在播放的样子，但不会缓冲，也不会播放

软件版本：
chromium 52.0.2743.85-2
Bilibili Helperv0.8.14

下面链接为其中一个
http://bangumi.bilibili.com/anime/v/90824

**Comment by myfreeer** [comment]
跳转到av号链接试试
http://www.bilibili.com/video/av5254114/

2016-08-13 11:38 GMT+08:00 eve_ouyang <notifications@github.com>:

**Comment by eveouyang** [comment]
都一样
我试了下，有部分是没有问题的，如下面的链接是没有问题的
http://bangumi.bilibili.com/anime/v/91316
