### ISSUE TITLE
“新番承包计划视频”播放器替换失败

### ISSUE THREAD

**Issue by enerai** [zacyu/bilibili-helper#26]
反馈问题： B 站绝大多数页面的视频都可以成功替换HTML5播放器，但是某些页面替换不成功。推测和承包系统有关。

测试链接：http://www.bilibili.com/video/av2182645/index_2.html

**Comment by Zhuogu** [comment]
我这边测试并没有遇到替换失败的问题, 麻烦详细描述一下.

**Comment by zacyu** [comment]
问题已经修复.
