### ISSUE TITLE
那啥节奏风暴

### ISSUE THREAD

**Issue by evrmji** [zacyu/bilibili-helper#262]
RT,节奏风暴,看起来很难自动抽奖,估计你们做了自动参与节奏风暴的js后就可以崩站了

**Comment by evrmji** [comment]
观察了下，就是要捕捉节奏风暴传递的一组文字（那实在太快，看不到代码），然后用post发送弹幕。（前面的几乎是猜测，那东西实在是太快了，2~4秒就完了）

**Comment by jjj201200** [comment]
谢谢你的建议，但是暂时不考虑这个功能 :santa:

**Comment by yemaobumei** [comment]
可以用MutationObserver检测页面dom结构变化，这样就可以找到增加的弹幕。测试了一下反应还是很快的。节奏风暴发送前会有一个弹幕提示，某某赠送了一个节奏风暴,在发送一组弹幕 。观众只要发送相同弹幕即可抽奖。不过感觉还是直接建立websocket接受弹幕 更靠谱一些。

**Comment by jjj201200** [comment]
@yemaobumei 你好，请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F)
