### ISSUE TITLE
怎么老是崩溃？

### ISSUE THREAD

**Issue by hsyscq** [zacyu/bilibili-helper#265]
文件已损坏

**Comment by jjj201200** [comment]
你的安装方法不正确，看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E5%92%8C%E5%AE%89%E8%A3%85%EF%BC%9F#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85)
