### ISSUE TITLE
(国内)下载地址显示：“视频地址获取中，请稍等…”

### ISSUE THREAD

**Issue by ApolloZhu** [zacyu/bilibili-helper#267]
确认不是网速的问题，`0.8.14`，`0.8.15.4`，`0.8.15.5` 都试过了，经过多次装卸重启
请问什么原因？

**Comment by myfreeer** [comment]
#266 
`interface.bilibili.com`似乎有所调整，强制要求带sign了
试试这个链接内容是不是{"code":-5003,"result":"checksum error"}
` http://interface.bilibili.com/playurl?platform=android&otype=json&appkey=86385cdc024c0f6c&cid=6281450&quality=2&type=mp4`

**Comment by ApolloZhu** [comment]
嗯，好吧

**Comment by koushuiji** [comment]
最近老是卡在视频地址获取中，请稍等而且一直在更换播放器，

**Comment by 13415038454** [comment]
卡在"视频地址获取中...."还有播放器只能显示原始播放器,没有其他选项

**Comment by sHacOer** [comment]
@myfreeer 我的也是这个情况，试了你给的链接，返回值是{"code":-5003,"result":"checksum error"}

**Comment by betaY** [comment]
b站现在下载需要sign验证 暂时应该是下不了了

**Comment by myfreeer** [comment]
> 低清接口：http://www.bilibili.com/m/html5?aid=5865702&page=1
低清接口仍然可以解析，但想要其他清晰度似乎只能用第三方接口了

**Comment by steven7851** [comment]
```javascript
var params='appkey=85eb6835b0a1034e&cid=' + cid + '&otype=json&platform=android&quality=3&type=mp4';
var sign=hex_md5(params + '2ad42749773c441109bdc0191257a664');
var url = 'http://interface.bilibili.com/playurl?'+params+'&sign='+sign;
```

**Comment by ApolloZhu** [comment]
以上方法确实可行，不过
- cid 的获取方法需要更改，没有找到 id `av_source`
- hex_md5 需要 [这个文件](http://static.hdslb.com/js/md5.js)

## json 文件
```
{  
   省略,
   "durl":[  
      {  
         省略,
         "url":高清晰度,
         "backup_url":[  
            "低清晰度"
         ]
      }
   ]
}
```

**Comment by myfreeer** [comment]
在 #20 有一个`appkey=95acd7f6cc3392f3`

**Comment by myfreeer** [comment]
新接口`http://api.bilibili.com/playurl?&aid=5523650&page=1&platform=html5`

**Comment by jjj201200** [comment]
@zacyu Please have a look. Can we use this solution?

**Comment by jjj201200** [comment]
@myfreeer 试了下好像不行啊 :s

**Comment by myfreeer** [comment]
@jjj201200 是指哪个？目前`http://api.bilibili.com/playurl?&aid=5523650&page=1&platform=html5`和`http://interface.bilibili.com/playurl?platform=bilihelper&otype=json&appkey=95acd7f6cc3392f3&cid=123456&quality=3`都可用

**Comment by jjj201200** [comment]
清晰度很低啊

**Comment by myfreeer** [comment]
在`backup_url`里面能找到`hd.mp4`和`flv`格式的链接
 >https://github.com/zacyu/bilibili-helper/blob/master/src/background.js#L251-L258

**Comment by jjj201200** [comment]
用了appkey的就是checksum error 不然就都是低清的，没有hdmp4和flv

**Comment by jjj201200** [comment]
@myfreeer 恩第二个我试了下可以的，只是这个platform=bilihelper不是早就不能用了么。。。？第一个html5源是低清的

**Comment by myfreeer** [comment]
低清接口再次改动：
```js
var token = document.body.innerHTML.match(/token[ =]+[\'\"]([0-9a-f]+)[\'\"\;]+/)[1];
var page = location.href.match(/video\/av(\d+)\/index_(\d+).html/) ? "1" : location.href.match(/video\/av(\d+)\/index_(\d+).html/)[2];
var url = 'http://api.bilibili.com/playurl?&aid=' + location.href.match(/video\/av(\d+)/)[1] + '&page=' + request.pg + '&platform=html5&token=' + token
```

**Comment by jjj201200** [comment]
目前0.8.16.17版本可以正常使用，请更新至该版本

**Comment by S-H-Y-GitHub** [comment]
@jjj201200 已经更新到最新版，但还是无法获取地址
![](https://s-h-y-github.github.io/img/Image%20Hosting/TIM%E6%88%AA%E5%9B%BE20170309125457.jpg)

**Comment by jjj201200** [comment]
@S-H-Y-GitHub 请确认您的网络是否存在问题

**Comment by jjj201200** [comment]
@S-H-Y-GitHub 你好，已经找到问题所在，请暂时切换到flash播放器使用这些功能。目前项目重构中，在此之前，我们会尽快推出0.8.16.*的后续测试版本。
