### ISSUE TITLE
区域限制的番无法观看

### ISSUE THREAD

**Issue by sjmr** [zacyu/bilibili-helper#271]
不知是不是我的个人问题 [僅限台灣地區] 的番无论如何也看不了

扩展更新到最新版了 0.8.15

**Comment by WalterMa** [comment]
#272

**Comment by zx35728** [comment]
同上

**Comment by kayen0422** [comment]
顶顶

**Comment by tommyZZM** [comment]
👍 +1 同上

**Comment by alicezhaojh** [comment]
在美国所有番剧都不能看了，无论是不是区域限定都一样，全部都是您所在区域不能观看，用的是最新的0.8.15

**Comment by jjj201200** [comment]
请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F)
