### ISSUE TITLE
0.8.15反区域彻底阵亡

### ISSUE THREAD

**Issue by aabccd** [zacyu/bilibili-helper#272]
所有限制区域的番都显示不出来了，海外党已哭瞎

**Comment by betaY** [comment]
B站好像又改了...
试了一下 开unblock youku的标准模式还是可以继续看的

**Comment by jjj201200** [comment]
请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F#%E5%88%A0%E9%99%A4%E4%BA%86-%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6%E8%A7%A3%E9%94%81%E5%8A%9F%E8%83%BD)
