### ISSUE TITLE
建议添加一个不提示领取瓜子之类的功能。

### ISSUE THREAD

**Issue by Angelovery** [zacyu/bilibili-helper#273]
建议添加一个不提示领取瓜子之类的功能。
右下提示虽然不怎么烦人。但是有时候并不合适_(:з」∠)_
比如只是挂着领瓜子而已。然而正在做一些其他的事情，比如打游戏啊。全屏看视频。或者浏览一些其它的网站什么的。虽然可以自己点掉。但是感觉还是出一个不提示的好╮(╯▽╰)╭

**Comment by jjj201200** [comment]
恩恩，谢谢你的建议

**Comment by jjj201200** [comment]
十分抱歉，由于b站方面要求去除挂机功能，已经不再维护自动领瓜子功能了。
