### ISSUE TITLE
提示已停用未在google商店上传的应用

### ISSUE THREAD

**Issue by loveless6trq** [zacyu/bilibili-helper#276]
昨天到今早还用的好好的，中午突然发现不能用了……打开扩展程序页面说已停用未在商店上传的应用
移除掉重新安装又可以用了，但是没一会又提示已被停用……这个有什么办法吗？

**Comment by jjj201200** [comment]
首先，你用的是什么版本，然后，你可以将扩展名改为rar，解压到文件夹，最后在开发者模式下加载压缩出来的文件夹。

**Comment by loveless6trq** [comment]
我用的是0.8.16.5，一直是在开发者模式下安装插件的……昨天重新还装还能用……刚刚重新安装也没用了，直接被停用了

**Comment by jjj201200** [comment]
@loveless6trq 请问你是从哪里获取到的16.5版本？

**Comment by ApolloZhu** [comment]
估计是这里吧：http://blackbili.nmzh.net/archives/bilibilihelper.html

**Comment by loveless6trq** [comment]
是的…………这个版本有问题吗……？
