### ISSUE TITLE
无法使用，卡在替换播放器

### ISSUE THREAD

**Issue by Cathgao** [zacyu/bilibili-helper#277]
如果HTML5优先，所有视频都停留在正在替换播放器，无法播放

**Comment by sino1641** [comment]
参见[#270](https://github.com/zacyu/bilibili-helper/issues/270)
解决办法：关闭助手中H5优先，再自行切换UA，如safari

**Comment by myfreeer** [comment]
ref : #266 #267

**Comment by jjj201200** [comment]
请使用官方的播放器，助手的swf和html5播放器替换功能将不再维护
