### ISSUE TITLE
解锁海外区域限制无效

### ISSUE THREAD

**Issue by dl0ne** [zacyu/bilibili-helper#278]
解锁区域限制无效，且与unblock bilibili冲突

**Comment by jjj201200** [comment]
[请看这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F)
