### ISSUE TITLE
有几种情况会狂跑CPU, 页面卡死

### ISSUE THREAD

**Issue by fleetingoo** [zacyu/bilibili-helper#279]
1. 进入的直播间被锁定, 卡死且原有页面的跳转失效
2. 直播间领取瓜子时无网络连接

**Comment by Jieck2002** [comment]
卡死卡死

**Comment by jjj201200** [comment]
请使用最新的测试版本，卡死的情况在新版本已经修复。测试版本请使用开发者模式安装。本插件重构工作正在展开，更多直播区功能即将推出。

**Comment by jjj201200** [comment]
0.8.15存在该问题。请更新到0.8.16.20。
