### ISSUE TITLE
无法解析出下载地址啊 http://www.bilibili.com/video/av5902368

### ISSUE THREAD

**Issue by pendave** [zacyu/bilibili-helper#280]
http://www.bilibili.com/video/av5902368

5555 这个我无法解析出来啊
ibilibili 加了i 的下载网站看到说api变了。。

于是去装了个插件 bilibili HTML5播放器
https://greasyfork.org/zh-CN/scripts/22441-bilibili-html5%E6%92%AD%E6%94%BE%E5%99%A8

用IDM 居然抓到了清晰度高的MP4

**Comment by myfreeer** [comment]
ref : #266 #267

**Comment by jjj201200** [comment]
0.8.16.16版本可以使用，请更新
