### ISSUE TITLE
0.8.15似乎视频下载不了了?

### ISSUE THREAD

**Issue by wwwzwt** [zacyu/bilibili-helper#281]
各种获取地址中
{"code":-5003,"result":"checksum error"}
我有一个不能选清晰度的扩展可以下载视频  还有一个可以提取缓存的本地视频   能不能从这些方面解决
不能下载好难受

**Comment by myfreeer** [comment]
ref : #266 #267

**Comment by jjj201200** [comment]
请更新助手版本到0.8.16.20

**Comment by wwwzwt** [comment]
哇  感动
