### ISSUE TITLE
监控抽到实物奖品能否添加提示

### ISSUE THREAD

**Issue by quericy** [zacyu/bilibili-helper#283]
这是一个悲伤的故事:

![图片](https://i.imgur.com/tzos1JI.png)

b站抽到实物奖品连个提醒和私信都没有,道具包裹也没显示

只有这里和插件的抽奖监控弹层里有

然后就悲剧了......等我发现的时候,小电视已经过期了 !!!

所以能不能添加个抽到实物奖品在页面有显眼的提示呢?虽然我觉得自己已经不可能再欧了....

**Comment by evrmji** [comment]
同上..........

**Comment by quericy** [comment]
@evrmji  噗,原来不是我一个人,握爪~~~~

**Comment by evrmji** [comment]
感谢作者
![qq 20160917160308](https://cloud.githubusercontent.com/assets/20814857/18606931/3f8978c8-7cf0-11e6-886c-b62add9a0482.jpg)

**Comment by quericy** [comment]
@evrmji  欧吃矛~

**Comment by quericy** [comment]
@evrmji  我也欧了23333
![](http://i.imgur.com/5xtocrs.png)

感谢作者~~~

**Comment by jjj201200** [comment]
欧吃矛~
![1](https://cloud.githubusercontent.com/assets/3397549/18721594/c1631266-8063-11e6-840a-c1914b261ab0.png)

**Comment by jjj201200** [comment]
这个功能我先记下，正式版本应该会有

**Comment by jjj201200** [comment]
十分抱歉，由于b站方面要求去除挂机功能，已经不再维护自动领瓜子功能了。

**Comment by quericy** [comment]
这真是个悲伤的消息...😱️
