### ISSUE TITLE
B站直播赠送礼物数量无法自定义

### ISSUE THREAD

**Issue by mmliar** [zacyu/bilibili-helper#284]
问题：在开启助手的情况下，修改赠送礼物的数量会无效。
具体表现：赠送礼物（例如辣条）时，无论在文本框内输入的数字为何，赠送时只会赠送一个（例如一包辣条）。
例外：道具包裹内的道具不受影响。

环境：
操作系统： Windows 10 Home 64-bit 1607 （OS Build 14393.105）（Locale 1033 - en_US）
浏览器：    原生 Google Chrome 53.0.2785.101 m (64-bit)
助手版本： V0.8.15 （Chrome Web Store 发行版本）（en_US）

**Comment by jjj201200** [comment]
目前最新的测试版本为0.8.16.9，请加群后下载
