### ISSUE TITLE
点击图标我的关注和我的收藏后跳转的旧版关注和收藏页面

### ISSUE THREAD

**Issue by chuxubank** [zacyu/bilibili-helper#285]
希望能替换成新版【已经设置了：一键前往首页版本 新版首页 但依旧转到旧版

**Comment by myfreeer** [comment]
新版关注页面是指这个？`http://member.bilibili.com/#main`

**Comment by MoeHero** [comment]
新版关注页面`http://www.bilibili.com/account/dynamic`

**Comment by myfreeer** [comment]
关注页面已经是新版了
https://github.com/zacyu/bilibili-helper/blob/master/src/popup.js#L61

**Comment by chuxubank** [comment]
啊后来发现了 希望收藏界面也能改成新版🙂就是那个有分类的界面 
程序很棒w

发自我的 iPhone

**Comment by myfreeer** [comment]
那么你需要把[这一行](https://github.com/zacyu/bilibili-helper/blob/master/src/popup.js#L67)改成[这样](https://github.com/myfreeer/bilibili-helper/blob/hd/popup.js#L75)
