### ISSUE TITLE
html5播放器无法切换

### ISSUE THREAD

**Issue by unlimitwhitenight** [zacyu/bilibili-helper#286]
卡在尝试替换播放器上面了，怎么解决？或者是我之前把chrome://flags的某些东西关掉的原因？chrome版本号 49.0.2623.87 m

**Comment by myfreeer** [comment]
参见 #267 
Duplicate of #266 #267 #268 #269 #277 #280 #281

**Comment by jjj201200** [comment]
请使用官方HTML5播放器
