### ISSUE TITLE
0.8.15东京不能看

### ISSUE THREAD

**Issue by k1ngsley** [zacyu/bilibili-helper#288]
这问题能否解决，不能解决的话我就卸载插件了。另外，这个问题解决方法建议与MAC OSX端的工程师讨论，他完美解决了这个海外使用问题。谢谢

**Comment by myfreeer** [comment]
Duplicate of #282 #278 #271 #272 #240
可以尝试[Unblock-Youku](https://github.com/uku/Unblock-Youku)

**Comment by jjj201200** [comment]
请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F)
