### ISSUE TITLE
无法自动领瓜子

### ISSUE THREAD

**Issue by duskmoon314** [zacyu/bilibili-helper#289]
助手相关功能开启时，直播间的领瓜子自动隐藏了

助手版本v0.8.15

**Comment by ZCXLLOD** [comment]
请使用最新版本：[http://blackbili.nmzh.net/archives/bilibilihelper.html](url)

**Comment by duskmoon314** [comment]
已经是最新的了

**Comment by duskmoon314** [comment]
不知怎么又可以了……
