### ISSUE TITLE
直播中奖收货地址填写相关

### ISSUE THREAD

**Issue by evrmji** [zacyu/bilibili-helper#290]
这个是截取的信息，可以考虑做一个自动填写的............
token=(不知道是什么的md5编码，40位)&id=160*_&user_name=(收件人)&user_phone=(收件人电话)&user_province=%E5%B9%BF%E4%B8%9C%E7%9C%81(省)&user_city=%E5%B9%BF%E5%B7%9E%E5%B8%82(市)&user_area=(区)&user_address=(地址)&user_post_code=(邮政编码)
Host: live.bilibili.com
Connection: keep-alive
Content-Length: 340
Accept: application/json, text/javascript, */_; q=0.01
Origin: http://live.bilibili.com
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
DNT: 1
Referer: http://live.bilibili.com/i/awards
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8
Cookie:

**Comment by jjj201200** [comment]
谢谢你，这个功能可能会在今后的更新中添加进去，但是目前还没有这个想法

**Comment by mengbingrock** [comment]
@carltonf 上周发现自己中的小电视没有及时填写地址已经过期了，无意中点击“抽奖监控”才发现大号小电视的我啊。

**Comment by jjj201200** [comment]
由于抽奖功能已经删除，故该功能将不再推出
