### ISSUE TITLE
1366X768分辨率下替换播放器之后弹幕过大影响观看

### ISSUE THREAD

**Issue by qw237384459** [zacyu/bilibili-helper#293]
![1](https://cloud.githubusercontent.com/assets/22609780/19064717/a159a4c0-8a41-11e6-954e-44f6167be5ab.jpg)

**Comment by myfreeer** [comment]
![1111111111111](https://cloud.githubusercontent.com/assets/17702502/19099065/69e8e664-8ae5-11e6-9a2d-71065284986d.PNG)
在找这个？

**Comment by qw237384459** [comment]
![1](https://cloud.githubusercontent.com/assets/22609780/19102614/3c29f7c6-8b04-11e6-9ba2-aaefcf6bf09b.jpg)
0.0噫。。为啥我没有这个。。。家里那台台式机也没看见过这个播放器样式
都开了播放器切换啊。。。。这是最新版本是0.8.15么？

**Comment by myfreeer** [comment]
![1](https://cloud.githubusercontent.com/assets/17702502/19103200/0172ecf6-8b08-11e6-9380-b2929bf6b4c9.PNG)
![2](https://cloud.githubusercontent.com/assets/17702502/19103204/0b8631bc-8b08-11e6-87d7-e032cd99707a.PNG)

**Comment by qw237384459** [comment]
OK了~O(∩_∩)O谢谢。。0.0话说这个播放器怎么跟我的区别这么大呢？

**Comment by myfreeer** [comment]
我的是ABPlayerHTML5-bilibili-ver
<https://github.com/zacyu/ABPlayerHTML5-bilibili-ver> 播放器

2016-10-05 14:33 GMT+08:00 樱雪丶冰蕊 <notifications@github.com>:
