### ISSUE TITLE
最近几天，直播抽奖监控会崩溃。

### ISSUE THREAD

**Issue by a321633** [zacyu/bilibili-helper#294]
平时就打开这一个没有直播或轮播的页面，挂着机。
自动抽奖自动领取。。。
。。。
然而最近几天失灵了，挂一段时间会失灵，然后试着刷新页面，抽奖监控会显示黄色，但其显示已经在这个房间打开过自动抽奖。。。
必须关闭CHORME后重新打开才能解决，问题是连什么时候会崩溃都不清楚。。。

**Comment by ZCXLLOD** [comment]
咱这边没有出现这样的情况，试试使用最新非测试版：https://yunpan.cn/cvZ48K6nQpAvw，提取码：7698。我这边的相关环境：助手版本：v0.8.16.9，浏览器：360安全浏览器最新版，系统：WIN7 64位 旗舰版，DNS：223.5.5.5、223.6.6.6，网络服务商：中国电信。

**Comment by jjj201200** [comment]
请问你使用的是什么版本的助手？

**Comment by a321633** [comment]
0.8.16.5

**Comment by jjj201200** [comment]
十分抱歉，由于b站方面要求去除挂机功能，已经不再维护自动领瓜子功能了。
