### ISSUE TITLE
新BUG,关于礼物显示

### ISSUE THREAD

**Issue by evrmji** [zacyu/bilibili-helper#296]
RT
助手显示的
![12](https://cloud.githubusercontent.com/assets/20814857/19160301/f048176a-8c21-11e6-90e2-6fa516370c30.jpg)
B站显示的
![22](https://cloud.githubusercontent.com/assets/20814857/19176319/2a2f0462-8c71-11e6-888d-7414d37c88ba.jpg)

**Comment by jjj201200** [comment]
=、=这不是一样吗。小电视就是大号小电视，客服说的。
