### ISSUE TITLE
提问:不停闪跳 载不出播放器

### ISSUE THREAD

**Issue by kasaiarata** [zacyu/bilibili-helper#297]
海外用户+1
版权番比如夏目..打开就不停的闪跳..载不出播放器orz
尝试过开关自动替换播放器功能 
HTML功能是关着的  (B站自己的HTML5也是关掉的)
chrome +最新版本的 是否bug获取不到地址所以最近不能用?

**Comment by myfreeer** [comment]
Duplicate of #278 #271 #272 #240 #282 #292 #288

**Comment by jjj201200** [comment]
@myfreeer 话说。。来维护主站的功能吧【跪下了

**Comment by myfreeer** [comment]
@jjj201200 区域限制问题我也没有更好的方法，除了设置代理

**Comment by myfreeer** [comment]
@jjj201200 考虑用第三方解析吗？
```js
getFileData("http://www.flvcd.com/parse.php?kw=" + encodeURIComponent(location.href) + "&format=high", function(data) {
    var parser = new DOMParser();
    var htmlres = parser.parseFromString(res, 'text/html'),
        array = [],
        a = htmlres.getElementsByTagName('a');
    for (var i in a)
        if (a[i].href && a[i].href.match(/acgvideo\.com.+rate=[0-9]+/) && array.indexOf(a.href) < 0) array.push(a[i].href);
    callback(array);
});
```

**Comment by jjj201200** [comment]
代理问题暂时无法解决，见[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F#%E5%88%A0%E9%99%A4%E4%BA%86-%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6%E8%A7%A3%E9%94%81%E5%8A%9F%E8%83%BD)
