### ISSUE TITLE
希望主站能添加一个每天自动投5个硬币的功能

### ISSUE THREAD

**Issue by a546109781** [zacyu/bilibili-helper#299]
至于投币的视频就无所谓了，比如给排行榜前5一人一个之类的。
我不要硬币……我只要每天50点经验
几千个硬币饥渴难耐，我要升6级啊

**Comment by a321633** [comment]
现在有几个人硬币会多得能随便投。

**Comment by jjj201200** [comment]
你好，像这种小需求量的功能暂时不考虑添加。
