### ISSUE TITLE
海外党已阵亡

### ISSUE THREAD

**Issue by hanyzhou** [zacyu/bilibili-helper#302]
Bilibili助手关于海外党看不了锁区番剧问题已经很久了，一直只能靠Unblock youku标准模式来解决这个问题。最新京吹第二季被锁为台湾可看，在NGA论坛上有帖子说用助手可以观看。但重新尝试发现海外党仍然不能观看的，希望早日可以修复这个问题，你们的功能选项已经增加了两排之多，可最初让我使用助手的最关键的功能如今已经不在了，FFS。

**Comment by myfreeer** [comment]
你需要一台国内服务器为海外用户解析视频地址（反向代理）

**Comment by alicezhaojh** [comment]
不只是锁区番剧看不了，我现在所有番剧都不行了，用的是最新的扩展版本0.8.15

**Comment by jjj201200** [comment]
请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F)

**Comment by hanyzhou** [comment]
1

Envoyé de mon iPhone
