### ISSUE TITLE
小电视抽奖改进建议

### ISSUE THREAD

**Issue by yxok200** [zacyu/bilibili-helper#304]
通过和官方沟通已经确认，使用插件进行小电视抽奖，将无法获得实物奖励
1、抽奖前被判定出使用插件的，无法抽中实物
2、抽中实物后备判定使用插件的，官方拒绝发货
PS：最近插件经常无故自动禁用，不知道是不是官方原因
        我的大号貌似被判定出使用插件了，前面抽1000次中了2个实物，后面4000次什么都没有

建议收到小电视抽奖推送以后，随机延迟1-100秒进行抽奖
如果有其他更好的办法，就最好不过了

**Comment by jjj201200** [comment]
先谢谢你的反馈
小电视中奖概率未知，不能说1000次中2次后4000次未中就是可能被判定为使用插件
在不知道他们如何检测之前不建议进行任何猜测。
另我10月1日还中了，货也发了，上万次也就中了那么一次，还是看运气。
至于说是否有必要延迟抽奖，这种做法也只是在猜测他们可能的监测机制，没有什么有价值的参考和试验价值，毕竟无从考证这个猜测的准确性。

**Comment by yxok200** [comment]
也是，我只是随口说说举个栗子，唯一确认的是官方有所行动了

**Comment by jjj201200** [comment]
那我们拭目以待吧，这个issue先关掉咯
