### ISSUE TITLE
bilibili直播也出现海外限制了，不知道能否追加观看直播限制解除的更新？

### ISSUE THREAD

**Issue by KazamaSion** [zacyu/bilibili-helper#305]
![image](https://cloud.githubusercontent.com/assets/13185633/19846744/d4754620-9f7c-11e6-8f7f-807cf3cc24df.png)

**Comment by jjj201200** [comment]
天啦撸。。

**Comment by ApolloZhu** [comment]
美国正常，ping 出来英国服务器

**Comment by jjj201200** [comment]
有些海外地区无法正常使用b站的服务。请通过其他途径解决这些问题。
关于此问题的态度请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F#%E5%88%A0%E9%99%A4%E4%BA%86-%E5%8C%BA%E5%9F%9F%E9%99%90%E5%88%B6%E8%A7%A3%E9%94%81%E5%8A%9F%E8%83%BD)
