### ISSUE TITLE
用法呢？

### ISSUE THREAD

**Issue by annder** [zacyu/bilibili-helper#306]
MEDME，怎么用呢？

**Comment by jiangeel** [comment]
chrome搜索这个插件就能安装了把

**Comment by annder** [comment]
chrome不能stroe....如何暴力安装?

**Comment by jiangeel** [comment]
[0.8.15_0.zip](https://github.com/zacyu/bilibili-helper/files/573007/0.8.15_0.zip)
在拓展界面打开开发者模式,把.crx拖进去试试

**Comment by annder** [comment]
谢谢，如果有问题的话，我会及时反馈。
