### ISSUE TITLE
我想能不能添加一个直达的功能

### ISSUE THREAD

**Issue by sweetasaki** [zacyu/bilibili-helper#307]
添加一个一键直达直播间的功能，现在每天都会看直播，但是每次都要到个人动态里才能进直播间，步骤挺繁琐的。
就像助手的第一个功能，一键前往bilibili.com。

**Comment by myfreeer** [comment]
建议使用“书签栏”功能
参考：https://support.google.com/chrome/answer/95745?hl=zh-Hans

**Comment by jjj201200** [comment]
可以有，以后会加，一定会加

**Comment by jjj201200** [comment]
该功能在0.8.16.17中添加
