### ISSUE TITLE
遇到5刷小电视，抽奖监控里面的小电视数会加16

### ISSUE THREAD

**Issue by 4321qasdfv** [zacyu/bilibili-helper#310]
遇到5刷小电视，抽奖监控里面的小电视数会加16
目前暂时好像观察到有这样的现象。。。。。

**Comment by jjj201200** [comment]
由于b站不允许挂机功能的存在，抽奖功能不再维护，以后的版本，包括测试版本，也会取消的这些功能。其中包括全自动的领瓜子和各种抽奖功能。望理解
