### ISSUE TITLE
此扩展程序无法修改网络请求的请求标头“X-Forwarded-For”

### ISSUE THREAD

**Issue by Pandadada9** [zacyu/bilibili-helper#311]
警告：
此扩展程序无法修改网络请求的请求标头“X-Forwarded-For”，因为这一修改与另一个扩展程序（Unblock Youku）产生了冲突。

**Comment by myfreeer** [comment]
Duplicate of #275 #237 
这是反区域限制功能（已失效），可自行去除[background.js#L964-L981](https://github.com/zacyu/bilibili-helper/blob/master/src/background.js#L964-L981)

**Comment by Pandadada9** [comment]
我仿佛一个智障，没在源代码里找到说的可以自行去除的

**Comment by myfreeer** [comment]
@Pandadada9 

- 这可能是因为你安装的是压缩过代码的版本，可以考虑用[此处](https://github.com/zacyu/bilibili-helper/blob/master/src/background.js#L964-L981)的代码去除对应行后替换本地的`background..min.js`

- 原版chrome默认不允许修改扩展，可考虑以下任意一条（第三方壳一般无此限制）
  - 删除`_metadata\verified_contents.json`
  - 重新打包后[加入白名单](https://github.com/myfreeer/enableallExtensions/blob/master/enableallExtensions.cmd)
  - 使用开发者模式加载并[禁用开发者模式警告](https://github.com/myfreeer/enableallExtensions/blob/master/DevWarningPatch.bat)

**Comment by jjj201200** [comment]
在0.8.16.17版本中解决了该问题
