### ISSUE TITLE
0.8.15版本，美国无法观看所有番剧

### ISSUE THREAD

**Issue by alicezhaojh** [zacyu/bilibili-helper#312]
根本不能绕过区域限制了，我现在在美国所有的番剧都看不了，全部都是您所在区域无法观看，晕死

**Comment by fatfishwen** [comment]
Unblock Youku貌似可以解决（速度很慢就是了），但是Chrome会报和bilibili helper有冲突，虽然貌似没啥实际影响。

**Comment by jjj201200** [comment]
非常抱歉，由于该功能成本太高，我们决定不再继续维护这个“绕过区域限制”的功能，请使用针对此问题的扩展如Unblock Youku，我们后续会修复部分冲突问题。
