### ISSUE TITLE
无法自动参加直播小电视抽奖了

### ISSUE THREAD

**Issue by Leila77** [zacyu/bilibili-helper#313]
应该是B站这两天更新了代码之类的，不会自动参加小电视抽奖了，还有自动签到也失效了。
浏览器是chrome，确定更新到最新版本了。

**Comment by jjj201200** [comment]
你好，根据b站直播区10月24日公告，不再允许使用直播间助手挂机功能。我们已经从测试版本（0.8.16.12）开始去除所有全自动挂机功能，其中包括自动领瓜子和自动参与抽奖功能。
