### ISSUE TITLE
0.8.15版本报错

### ISSUE THREAD

**Issue by AnnAngela** [zacyu/bilibili-helper#316]
打开视频页面后报：
```bilibili_injected.min.js:2 Uncaught TypeError: Cannot read property 'indexOf' of undefined```
对应代码：
```$("#bofqi iframe").attr("src").indexOf("bilibili.com")<0```
$("#bofqi iframe")并没有src属性_(:зゝ∠)_，导致无法下载视频和弹幕文件

个人猜测是使用H5播放器后不需要用iframe插入flash播放器

**Comment by jjj201200** [comment]
官方已经推出足够靠谱的html5播放器，请使用官方播放器，我们将不再维护自己的此项功能
