### ISSUE TITLE
我的谷歌浏览器用了助手之后，直播弹幕不动了

### ISSUE THREAD

**Issue by shiroringo** [zacyu/bilibili-helper#318]
右边对话框只有我进入时候的弹幕，不会实时刷新……要刷新网页才刷新，然后又不动了……是我浏览器的问题吗？

**Comment by jjj201200** [comment]
请问你的浏览器类型和版本，使用的助手版本。

**Comment by shiroringo** [comment]
Google Chrome 版本 55.0.2883.87 m，助手版本v0.8.15

**Comment by jjj201200** [comment]
先确保你没有锁定弹幕，不行换成最新的测试版本试试

**Comment by chestnutt233** [comment]
我也是这个问题 而且我试了用safari也是不刷新

**Comment by jjj201200** [comment]
@shiroringo 请问新版本还有这种问题吗？

**Comment by gonejack** [comment]
@jjj201200 借地问一下助手可以强行调出B站直播的h5播放器吗，Chrome关掉了Flash，但B站直播的h5的出现判断貌似有问题，没有flash时并不会自己切换成h5。

**Comment by jjj201200** [comment]
@gonejack 是的他不会自己出来，这很不好。你可以在[这里](http://live.bilibili.com/help/#uh5)开启他，另外，下次请单独开issue，我们好保留这个问题，给其他人提供明确的参考和帮助

**Comment by shiroringo** [comment]
助手会自动更新，这点还是挺好的，目前只有弹幕不动和不显示在线人数的问题。我怀疑有网络问题，九月底的时候我换其他网络试一下。
