### ISSUE TITLE
最新版bilihelper V0.8.15 推送不准确

### ISSUE THREAD

**Issue by wuhan890809** [zacyu/bilibili-helper#320]
如题，使用的浏览器是基于chromium的CentBrowser（Chrome 55内核） 操作系统是win10 64位 10240
所有功能均能正常使用，唯有右下角更新推送偶尔会推送一些我从未关注的UP主的新投稿。但是通过点击插件图标弹出菜单中的“我的关注”进入B站后，网页的更新动态是正常的

**Comment by jjj201200** [comment]
谢谢反馈
