### ISSUE TITLE
GitHub上下载的怎么用

### ISSUE THREAD

**Issue by OldYogurt** [zacyu/bilibili-helper#321]

**Comment by myfreeer** [comment]
去安装nodejs，然后
```shell
npm install
npm install -g gulp
gulp release
```

**Comment by OldYogurt** [comment]
@myfreeer 能说的详细点吗。。谢谢。。

**Comment by jjj201200** [comment]
噗。去这里下载https://github.com/zacyu/bilibili-helper/releases/download/0.8.16.16/bilibilihelper_0.8.16.16.crx

**Comment by OldYogurt** [comment]
@jjj201200 啊，谢谢，但是为什么安装后显示“此扩展程序可能已损坏。”。。

**Comment by jjj201200** [comment]
@OldYogurt 测试版本使用开发者模式安装
