### ISSUE TITLE
0.8.16.16 怎么启用

### ISSUE THREAD

**Issue by ShuLingH** [zacyu/bilibili-helper#322]
载入chrome扩充功能后显示:
"这个扩充功能可能已经毁损"
<a href="http://imgur.com/m0zaVa2"><img src="http://i.imgur.com/m0zaVa2.png" title="source: imgur.com" /></a>
试着按修复也没反应，请问这要怎么解?
chrome 55.0.2883.87 m (64-bit)

**Comment by jjj201200** [comment]
请使用[开发者模式](https://github.com/zacyu/bilibili-helper/wiki/%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E5%92%8C%E5%AE%89%E8%A3%85%EF%BC%9F#%E4%BB%A5%E5%BC%80%E5%8F%91%E8%80%85%E6%A8%A1%E5%BC%8F%E5%AE%89%E8%A3%85)安装

**Comment by ShuLingH** [comment]
啊 不好意思，没仔细翻说明就问了个蠢问题
