### ISSUE TITLE
抽奖监控图标已黄，无法领取小电视等的奖励

### ISSUE THREAD

**Issue by blueds** [zacyu/bilibili-helper#323]
无法领取小电视奖励，前两天还正常

**Comment by jjj201200** [comment]
你好，我从0.8.16.13版本开始去掉了小电视的功能，并且不再维护此类抽奖功能。我不是很清楚是否是因为b站改了部分代码而导致以前的版本不能用。非常抱歉，由于b站方面的一再要求和明确态度，我们无法为你解决这个问题。
