### ISSUE TITLE
0.8.16.16和0.8.16.10在使用过程中一直出现文件损坏

### ISSUE THREAD

**Issue by FuYang001** [zacyu/bilibili-helper#325]
=-只有0.8.15的没有损坏 就是安装之后用了一会 图标消失-=在“拓展程序“查看发现提示“该文件可能以损坏”
QWQ结果新版本的功能一直无法使用 有办法解决嘛QWQ

**Comment by myfreeer** [comment]
chrome://flags/#extension-content-verification，尝试改为引导模式（可获得期望的哈希值，但不强制实施）

在 2017年2月6日 下午12:21，FuYang001 <notifications@github.com>写道：

**Comment by jjj201200** [comment]
楼上正解
