### ISSUE TITLE
希望增加对海外党的支持

### ISSUE THREAD

**Issue by fatfishwen** [zacyu/bilibili-helper#326]
作为海外党，无法看新番是一件很痛苦的事情。相信很多有同样问题的人都是通过unblock Youku之类的其他插件解决这一问题的，但是这些插件和bilibili-helper有冲突（Chrome会提示，虽然貌似不会造成什么影响）。两个小建议：1，希望bilibili-helper能为海外党提供类似功能；2，如果不行，至少希望能够看看是不是代码规避掉unblock youku会用的地方让Chrome不要再提示有问题……

**Comment by myfreeer** [comment]
冲突部分代码
https://github.com/zacyu/bilibili-helper/blob/master/src/background.js#L964-L981

**Comment by jjj201200** [comment]
0.8.16.7版本已经解决冲突问题
另外请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F)
