### ISSUE TITLE
直播间进不去了

### ISSUE THREAD

**Issue by 0oshowero0** [zacyu/bilibili-helper#327]
开着助手的话进直播页面会卡死而且关不掉，如果继续等谷歌会说啊呦内存不够了

**Comment by jjj201200** [comment]
0.8.15版本存在这个问题，已经在之后的版本修复，请更新你的版本到0.8.16.16，下载地址在[这里](https://github.com/zacyu/bilibili-helper/releases/download/0.8.16.16/bilibilihelper_0.8.16.16.crx)。0.8.16.*为测试版本，请按照[这里](https://github.com/zacyu/bilibili-helper/wiki/%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E5%92%8C%E5%AE%89%E8%A3%85%EF%BC%9F#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85)的方法进行安装
