### ISSUE TITLE
增加对 https 的支持

### ISSUE THREAD

**Issue by Misaka-11037** [zacyu/bilibili-helper#328]
现在使用 https 播放视频时，会出现

>Mixed Content: The page at 'https://www.bilibili.com/video/$ID/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://comment.bilibili.com/$ID.xml'. This request has been blocked; the content must be served over HTTPS.
send @ chrome-extension://kpbnombpnpcffllnianjibmpadjolanh/jq.bilibili.min.js:1

希望能将 http 改成 https。

**Comment by yonjar** [comment]
我补充一个:
直播间也开了https  现在不能自动领瓜子了

**Comment by myfreeer** [comment]
See #324

**Comment by jjj201200** [comment]
该项改进会在重构过程中进行，不会出现在目前的版本中。
