### ISSUE TITLE
我现在打开QQ浏览器出现我的关注一千多条

### ISSUE THREAD

**Issue by a499738100** [zacyu/bilibili-helper#329]
![qq 20170223160829](https://cloud.githubusercontent.com/assets/25808805/23250110/aad75ef0-f9e2-11e6-9e59-ef0e5086eed6.png)

**Comment by jjj201200** [comment]
=、=谢谢反馈哈，我去看下怎么回事。。。

**Comment by zacyu** [comment]
Any update? Is it still reproducible? @a499738100 @jjj201200

**Comment by jjj201200** [comment]
no

**Comment by zacyu** [comment]
Closing (Obsolete).
