### ISSUE TITLE
建议绕过区域限制功能只对B站生效

### ISSUE THREAD

**Issue by S-H-Y-GitHub** [zacyu/bilibili-helper#331]
我使用的是0.8.16.18版本的bilibili-helper，似乎该拓展会对用户访问的所有网页加上

```
x-forwarded-for:220.181.111.149
client-ip:220.181.111.149
```

这样的请求头，导致某些网站错误识别用户IP，产生拒绝访问等一些很不方便的情况，希望可以修复一下。

**Comment by jjj201200** [comment]
@S-H-Y-GitHub 刚推完，谢谢提醒，该功能实际上已经关闭部分代码还留着。
