### ISSUE TITLE
你们是不是不能用来自动领瓜子了？

### ISSUE THREAD

**Issue by ustgii** [zacyu/bilibili-helper#333]

**Comment by jjj201200** [comment]
请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F#%E5%88%A0%E9%99%A4%E4%BA%86-%E8%87%AA%E5%8A%A8%E6%8A%BD%E5%A5%96%E5%8A%9F%E8%83%BD)
