### ISSUE TITLE
迷之卡死在切换播放器

### ISSUE THREAD

**Issue by DimitriSun** [zacyu/bilibili-helper#334]
![default](https://cloud.githubusercontent.com/assets/26372609/23841291/29e87b22-07e7-11e7-95b2-74735c4a03ef.JPG)

版本 56.0.2924.87
Flash 24_0_0_227

**Comment by jjj201200** [comment]
你好，请关闭该功能，使用官方提供的播放器。由于哔哩哔哩已经上线了html5播放器，我们已经不再维护此项功能。
