### ISSUE TITLE
新版不支持番剧吗，还有为什么下载视频都是分段的啊，

### ISSUE THREAD

**Issue by 1608637229** [zacyu/bilibili-helper#335]
都是5到6分钟一段，以前的插件能下完整的我记得，

**Comment by 1608637229** [comment]
原作者弃坑了？？

**Comment by myfreeer** [comment]
设置里`获取视频下载地址格式`选mp4

**Comment by jjj201200** [comment]
没有弃坑，咕咕很忙，我在重构，也是时不时的，所以还请见谅。番剧的页面的功能支持随着浏览器切换功能和绕区域限制功能取消而暂时不能用了。至于下载，本来有的视频就是分段的，有的是完整的一个。

**Comment by 1608637229** [comment]
试了好几个视频都是分段，设置了MP4格式但是只有flv的格式

**Comment by jjj201200** [comment]
米错米错大多数是分多段的，由于下载接口的关系，高清的就只有flv的低清的才是mp4的
