### ISSUE TITLE
360急速浏览器0.8.16.16使用不能

### ISSUE THREAD

**Issue by FreeXJX2012** [zacyu/bilibili-helper#338]
用他拓展商店里的0.8.15能用  后面版本都用不了···
已经正确安装了

**Comment by jjj201200** [comment]
今天刚刚推送的0.8.16.18。你要么去[这里](https://github.com/zacyu/bilibili-helper/wiki/%E5%A6%82%E4%BD%95%E4%B8%8B%E8%BD%BD%E5%92%8C%E5%AE%89%E8%A3%85%EF%BC%9F)看看怎么通过其他方法安装，要么就等360应用商店更新，要么就换谷歌浏览器

**Comment by jjj201200** [comment]
另外建议留意我微博的任何通知和说明

**Comment by FreeXJX2012** [comment]
好的 谢谢
