### ISSUE TITLE
无法安装最新的0.8.16.18

### ISSUE THREAD

**Issue by WindsCloudy** [zacyu/bilibili-helper#339]
如题 安装完后显示扩展已损坏  只能用chrome store的0.8.15   但是礼物包裹和领取瓜子功能已失效

chrome版本   57.0.2987.98 (64-bit)

**Comment by WindsCloudy** [comment]
0.8.16.17和16  也不行 试过了 是不是需要关闭CHROME实验室功能里的一些东西？

**Comment by jjj201200** [comment]
0.8.16.18已经推送到google应用商店了，直接去安装就可以了，不需要关闭实验室功能
