### ISSUE TITLE
重新装了一下

### ISSUE THREAD

**Issue by FreeXJX2012** [zacyu/bilibili-helper#340]
发现 是直播间功能没用  其他的功能都可以用

**Comment by jjj201200** [comment]
什么功能？有什么错误信息提示信息吗？笼统的描述并不知道该如何帮助你

**Comment by FreeXJX2012** [comment]
就直播间设置下的功能都不生效，正常的话不是在直播视频画面下面有版本号跟你们的微博ID嘛，这边就没有。 浏览器是 360急速浏览器 。
        现在已经换了360安全浏览器，能用。

**Comment by FreeXJX2012** [comment]
没有提示错误。

**Comment by FreeXJX2012** [comment]
然后 还有就是 领瓜子的功能 似乎用不了··   它弹出了输入框，手动输入后点确定没反应，也不会自动答题。

**Comment by jjj201200** [comment]
看一下地址栏的网址是不是https://开头的。如果是的话改成http://就好了

**Comment by FreeXJX2012** [comment]
吼吧  解决了·····
