### ISSUE TITLE
B站助手0.8.15直播打开第二个直播间就直接卡死崩溃

### ISSUE THREAD

**Issue by jmjun** [zacyu/bilibili-helper#342]
最近就发现B站助手0.8.15直播打开第二个直播间就直接卡死崩溃，例如自动抽奖功能就开始失效了，我使用的是谷歌浏览器，请麻烦尽快修复！！

**Comment by jjj201200** [comment]
你好啊，你的问题并不是最近发生的，早在去年就已经在新版本中修复这个问题。
昨天已经将0.8.16.18版本推送至商店，请及时更新
