### ISSUE TITLE
v0.8.16.18 所有选项无法更改

### ISSUE THREAD

**Issue by CyanTailwinds** [zacyu/bilibili-helper#347]
更新之后，点击工具栏上的扩展按钮，出现几个没有文字的按钮，以前用于输入AV号快速进入的功能也失效。进入扩展设置页面，所有功能显示正常，但是所有按钮处于无法被按下的状态
Chrome版本 57.0.2987.110 (64-bit)
![4417e352ly1fdpplw1tsrj21hc0u0arc](https://cloud.githubusercontent.com/assets/26496027/24068233/7d22d612-0bc4-11e7-81cd-7c78041d5d38.jpg)

**Comment by jjj201200** [comment]
请问是从商店更新的吗？

**Comment by jjj201200** [comment]
怕不是你下错了安装文件，你的情况可能是由于没有编译工程导致脚本没有成功载入。商店版本是不会有这个问题的。

**Comment by CyanTailwinds** [comment]
应该当初应该是自动更新的吧，出问题之后我从商店和官网都重新安装过，现在更新了19版本后已经正常了
