### ISSUE TITLE
更新後完全無法使用

### ISSUE THREAD

**Issue by i9602097** [zacyu/bilibili-helper#348]
前幾天更新後圖示由bili變成了貓的樣子
然後所有功能都不能用
爬文後雖然發現有近似問題
但是我肯定原因絕不相同
因為我肯定沒用HTTPS上Bilibili
而且我的助手還出現以下問題
首先按下圖示出現的選單變成這個樣子
![sshot-1](https://cloud.githubusercontent.com/assets/18757629/24068579/6b6be11c-0bcd-11e7-8dec-53ce7eb1a0e8.png)
當中所有按鈕都沒作用
而按右鍵選擇"檢查彈出式視窗"打開Console只有出現以下錯誤
![sshot-2](https://cloud.githubusercontent.com/assets/18757629/24068628/aabe85f8-0bce-11e7-8717-b2ec6f69c5f2.png)
按右鍵選擇"選項"打開選項頁
則出現以下奇怪畫面
![sshot-3](https://cloud.githubusercontent.com/assets/18757629/24068642/e07e5f7e-0bce-11e7-9191-2a366780f1a9.png)
第一是左上角沒有版本號
第二是沒有一個選項被選上
也沒有一個選項能選上
我試過移除重裝也沒法修復
這問題我已經不知道如何解決所以上來請教
助手版本是0.8.16.18從Chrome Web Store上安裝
Chrome版本是57.0.2987.98 (正式版本) (64 位元)

**Comment by 8qwe24657913** [comment]
同上，CSP要加self啊……

**Comment by jjj201200** [comment]
啊csp必然是加了的，只是不清楚为何有的人没有问题有的人有问题，还在排查中。抱歉。

**Comment by jjj201200** [comment]
@i9602097 如果方便的话，可以远程调试一下，teamviewer或者别的途径。

**Comment by 8qwe24657913** [comment]
@jjj201200 把`"content_security_policy": "script-src 'unsafe-eval'; object-src 'self'"`改成`"content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"`

**Comment by i9602097** [comment]
對不起，因為電腦有公司的文件不太方便
但我電腦的認識不淺
雖然網頁開發不是我專業
但是複雜的操作還可以
方便可以說一下

**Comment by i9602097** [comment]
傳一下chrome://flags上來
怕有些設定會令助手出錯
![default](https://cloud.githubusercontent.com/assets/18757629/24069500/57e188a6-0be4-11e7-8d0d-242541dc6934.png)

**Comment by jjj201200** [comment]
推送了0.8.16.19版本，等更新看看问题解决没

**Comment by i9602097** [comment]
了解
等收到0.8.16.19再來回報

**Comment by 8qwe24657913** [comment]
@jjj201200 ……我认为你要把version改成0.8.16.19我们才能收到更新……

**Comment by i9602097** [comment]
只是待審吧
不會犯這種低級錯誤吧

**Comment by jjj201200** [comment]
@8qwe24657913 我确定已经改了，并且谢谢你的提醒

**Comment by 8qwe24657913** [comment]
@jjj201200 https://github.com/zacyu/bilibili-helper/blob/master/src/manifest.json#L35

**Comment by jjj201200** [comment]
啊呀，github还没推嘛。。。先推的商店

**Comment by i9602097** [comment]
已經更新到0.8.16.19並能再次正常使用了
感謝各位幫忙
