### ISSUE TITLE
自动抽奖提示若干次宝箱过期

### ISSUE THREAD

**Issue by linzyjx** [zacyu/bilibili-helper#349]
提示过期，但还是能够抽奖（怀疑是多动作了几下）
（别在意内容QAQ）
![qq 20170318234526](https://cloud.githubusercontent.com/assets/8017477/24073638/8e4ccbe8-0c35-11e7-9501-2d69f8864b00.png)
Chrome版本：56.0.2924.87 (64-bit)
插件版本：v0.8.16.19

**Comment by jjj201200** [comment]
啊这个问题暂时就这样吧233，能用就不管他了，宝箱代码实在是太麻烦了，0.9版本我保证没这个问题【滑稽】

**Comment by linzyjx** [comment]
简直了233333
