### ISSUE TITLE
这次问题的描述

### ISSUE THREAD

**Issue by imba97** [zacyu/bilibili-helper#350]
我只是路过的一个用户，同时也是只并不会啥的程序猿。大家不要催嘛，说什么用不了了删了算了，先弄清原因不好么，这次估计是B站网页更新了，使用了HTTPS传输协议，至于具体什么我也不清楚，反正是个安全协议。这导致插件不能正常加载外部脚本，所以不能用了。并不是因为插件更新而不能用的别乱甩锅啊。看到好多人抱怨甚至说什么还是删了吧，我只想说正是因为这插件一直做得很好，中途突然出现一点问题（而且并不是插件的问题）很多人就瞬间失望了。别人敲几万行代码免费让你用这么多方便的功能都不知，后面就不说了。如果这插件是我的，让我碰到那种人，我发现是你ID登录的B站直接给你弹个界面“求你把我的插件删了”。以上只是猜想、自己的看法。

**Comment by sweetasaki** [comment]
我说今天怎么插件老加载不出来，看你的问题描述就懂了，原来是B站启用了https，希望作者尽快修复一下吧

**Comment by jjj201200** [comment]
2333其实https修复的push之前是有的，但是那次改的太暴力了。我会尽快解决这个问题，0.9版本还需要段时日才能上线

**Comment by linzyjx** [comment]
等吧，领瓜子什么的可以了
其实现在B站那边的全站https都还没好，可以先改成http
