### ISSUE TITLE
直播页面的助手的小问题

### ISSUE THREAD

**Issue by juju326** [zacyu/bilibili-helper#351]
直播页面的助手必须要是”live.bilibili.com/”开头的网址开会启用，但这段时间从我的关注里打开的链接都是”http://live.bilibili.com/”开头的，多了一个“http://  ”小助手就不启动了，手动删除“http:// ”之后小助手才恢复，求解决啊

**Comment by linzyjx** [comment]
没办法，B站那边的问题，全站https还没弄好
然后这边可能要到0.9才能解决
（我自己也只能这样弄）

**Comment by zacyu** [comment]
已修复. 将包括在下个发新版中.
