### ISSUE TITLE
X-Forwarded-For请求头的问题

### ISSUE THREAD

**Issue by HaoBingo** [zacyu/bilibili-helper#352]
插件版本 0.8.16.18，插件开启后，对于每个http请求都添加了 X-Forwarded-For与Client-IP 这两个http请求头，建议只针对*.bilibili.com添加。

有时候使用起来，会对访问其他网站造成影响，希望能改进下。

**Comment by myfreeer** [comment]
都删了三次了，怎么还有？
相关commit:
* https://github.com/zacyu/bilibili-helper/commit/3c22447bc90c58fb6c25f046dbfe65355765f3cb 
* https://github.com/zacyu/bilibili-helper/commit/7649796daa248dfdb06dc106bb8dca001ccfbcb4
* https://github.com/zacyu/bilibili-helper/commit/8e88a883ae30ea875cb7ff1ede9c80dcc84d72e8

相关issue: #331 #326 #312 #311 #302  #282 #278 #271 #272 #237 #240

**Comment by zacyu** [comment]
Fixed in 8e88a883ae30ea875cb7ff1ede9c80dcc84d72e8 (v0.8.16.19). Cannot replicate in latest release. @HaoBingo 请更新最新版.
