### ISSUE TITLE
暂时无法自动签到

### ISSUE THREAD

**Issue by Thinkjia** [zacyu/bilibili-helper#354]
## Feedback 问题反馈
Before submitting your issue, please check to make sure of the following:
在您提交问题前, 请检查以下项目:
- [x] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage. 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it. 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated). 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] You have filled out your system environment info. 您已填写了系统环境信息.

### Environment Info 环境信息
Please fill out the following:
请填写以下信息:
1. Operating System 操作系统 (Windows/macOS/Linux):
Windows 10 企业版
2. Chrome Version 浏览器版本:
You can check this under [Menu/Help/About]. 您可以在 [菜单/帮助/关于] 下查看.
Chrome 版本 57.0.2987.110 (64-bit)
3. Extension Version 扩展版本:
You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.
0.8.16.19
### Steps to Reproduce / Attempted solution 重现步骤/尝试的解决方案
Please be specific here, thanks :)
请具体描述, 谢谢 :)
连续好几天发现无法自动签到= =然而可以手工签到= =

**Comment by shxhmy** [comment]
Win 10 Pro x64 Build 14393
Chrome x64 57.0.2987.98
bilibili助手 v0.8.16.19
设置页面功能全开，但实际功能全部消失，包括自动签到抽奖领瓜子，重新安装插件无效，重启系统或浏览器均无效。求解决~

**Comment by jjj201200** [comment]
多半是https问题导致的，确认一下地址栏里网址是否是https开头的，如果是的话将https改为http并再按下回车

**Comment by zacyu** [comment]
已修复. 将包括在下个发新版中.
