### ISSUE TITLE
番劇無法下載

### ISSUE THREAD

**Issue by NichVong** [zacyu/bilibili-helper#355]
新的番劇播放頁面下“助手”按鈕消失了，無法下載。番劇www.bilibili.com/video/avxxxxxx會被重定向到bangumi.bilibili.com/anime/xxxx/play#xxxxx。

**Comment by NichVong** [comment]
剛發現有人提過了…… #335

**Comment by zacyu** [comment]
这个和上面提到的 issue 还是有些区别的. 感谢提出, 之后我看一下解决方案.
