### ISSUE TITLE
助手與官方html5直播姬衝突

### ISSUE THREAD

**Issue by i9602097** [zacyu/bilibili-helper#356]
## Feedback 问题反馈
Before submitting your issue, please check to make sure of the following:
在您提交问题前, 请检查以下项目:
- [x] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage. 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it. 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated). 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] You have filled out your system environment info. 您已填写了系统环境信息.

### Environment Info 环境信息
Please fill out the following:
请填写以下信息:
1. Operating System 操作系统 (Windows/macOS/Linux):
Windows 10
2. Chrome Version 浏览器版本:
You can check this under [Menu/Help/About]. 您可以在 [菜单/帮助/关于] 下查看.
Chrome 版本 57.0.2987.110 (正式版本) (64 位元)
3. Extension Version 扩展版本:v0.8.16.19
You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### Steps to Reproduce / Attempted solution 重现步骤/尝试的解决方案
Please be specific here, thanks :)
请具体描述, 谢谢 :)
現在B站直播推出了html5播放器
可以在這裡打開
http://live.bilibili.com/help/#uh5
但是在打開助手時是不能發彈幕的
只有停用助手才可以
flash版沒這問題但是我希望用html5版本
我是用Windows 64位元版Chrome 57
助手版本是v0.8.16.19
希望能修正這問題
補充：助手設定頁
![sshot-1](https://cloud.githubusercontent.com/assets/18757629/24319763/65284a64-1160-11e7-9042-fa1ebaa98556.png)

**Comment by jjj201200** [comment]
好的，谢谢。终于直播也开始公测了。我们会尽快跟进

**Comment by i9602097** [comment]
經過我的測試問題應是出在彈幕發送增強上
把彈幕發送增強關掉就可以
問一下彈幕發送增強有什麼用
如果對我沒用就長期關掉了

**Comment by jjj201200** [comment]
用来自动分段发送弹幕，允许你发送超过长度限制的弹幕。可以关了，并无大碍

**Comment by i9602097** [comment]
OK，那我先關了待修bug
修好了close了這個issue我再打開
這個issue在bug未修復前我不會close的
確保開發組能注意這bug

**Comment by jjj201200** [comment]
@i9602097 该问题会在0.8.16.20版本中得到修复，请关注商店和github released推送

**Comment by i9602097** [comment]
晚了看見回覆
經測試後已經成功在0.8.16.20版本下打開彈幕發送增強及HTML5播放器下發送彈幕
感謝開發組支持
