### ISSUE TITLE
HTTPS 域直播脚本加载问题

### ISSUE THREAD

**Issue by zacyu** [zacyu/bilibili-helper#357]
## Feedback 问题反馈
Before submitting your issue, please check to make sure of the following:
在您提交问题前, 请检查以下项目:
- [x] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage. 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it. 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated). 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] You have filled out your system environment info. 您已填写了系统环境信息.

### Environment Info 环境信息
Please fill out the following:
请填写以下信息:
1. Operating System 操作系统 (Windows/macOS/Linux):
macOS Version 10.12.3 (16D32)
2. Chrome Version 浏览器版本:
You can check this under [Menu/Help/About]. 您可以在 [菜单/帮助/关于] 下查看.
Version 57.0.2987.110 (64-bit)
3. Extension Version 扩展版本:
You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.
b15fa4ffe80aa171b50a5bb6c28bedffea16030e

### Steps to Reproduce / Attempted solution 重现步骤/尝试的解决方案
Please be specific here, thanks :)
请具体描述, 谢谢 :)

目前 #354 #351 #350 等 issues 都提到了因为 HTTPS 域直播脚本加载的问题. 鉴于此, 有关影响和在此处统一讨论. @jjj201200 我不是很清楚具体的情况, 麻烦你这边先来描述一下问题和可能的解决方案.

**Comment by jjj201200** [comment]
b站现在有些事https的有些不是，解决方法是可以先暂时全部重定向到http，不知道他们什么时候全部改完我们再改

**Comment by zacyu** [comment]
@jjj201200 主要需要修改的地方是什么呢? 我没有了解具体遇到的问题是什么, 跨域权限吗?

**Comment by jjj201200** [comment]
@zacyu "此网页正试图从未经验证的来源加载脚本"
