### ISSUE TITLE
0.8.16.19分段视频不能合并成一个视频下载了？

### ISSUE THREAD

**Issue by liu870825yi** [zacyu/bilibili-helper#359]
我记得以前下载视频能将分段视频合并成一个视频下载的，现在不行了？

**Comment by zacyu** [comment]
请仅使用问题反馈报告 bug 或者提交功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.

**Comment by zacyu** [comment]
Bilibili 助手没有提供视频合并的功能, 出现分段可能是因为视频源变化. 如果优先 MP4 格式下载通常会下载到单一文件.
