### ISSUE TITLE
领瓜子在第四轮最后一个出线bug，不能自动领完，需要刷新继续

### ISSUE THREAD

**Issue by LeecGitHub** [zacyu/bilibili-helper#360]
操作环境：chrome57.0.2987.98   助手版本 0.8.16.19

**Comment by jjj201200** [comment]
你好，这不是bug 哦，之前的“自动领瓜子”功能和“自动参与抽奖”功能被B站叫停。
我们根据他们的要求做了调整，直接删除了抽奖功能，并把自动领瓜子功能改为1小时自动领取，而后手动才做以后再重新自动领取，以此类推的设定。还望见谅。具体请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F#%E5%88%A0%E9%99%A4%E4%BA%86-%E8%87%AA%E5%8A%A8%E6%8A%BD%E5%A5%96%E5%8A%9F%E8%83%BD)

**Comment by jjj201200** [comment]
你好，这不是bug 哦，之前的“自动领瓜子”功能和“自动参与抽奖”功能被B站叫停。
我们根据他们的要求做了调整，直接删除了抽奖功能，并把自动领瓜子功能改为1小时自动领取，而后手动才做以后再重新自动领取，以此类推的设定。还望见谅。具体请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F#%E5%88%A0%E9%99%A4%E4%BA%86-%E8%87%AA%E5%8A%A8%E6%8A%BD%E5%A5%96%E5%8A%9F%E8%83%BD)

**Comment by jjj201200** [comment]
具体是这样的：每轮3次，分别是3，6，9分钟，一轮18分钟后开始新的一轮。3轮一共需要54分钟，之后开始第四轮，第四轮第一次从第54分钟开始，第四轮第二次从第57分钟开始，而最后一轮超过了1小时则按照设定自动停止。

**Comment by LeecGitHub** [comment]
可以设置为90分钟嘛，正好领完关闭。

在 2017年3月31日 上午10:37，jjj201200 <notifications@github.com>写道：

**Comment by jjj201200** [comment]
@LeecGitHub 本来这个功能要和自动抽奖功能一起完全删除的。我是为了尽可能的争取方便才设定时限，也只是希望b站方面别太针对。还望你能理解，60分钟一般用户可以领完3轮，已经不错了

**Comment by LeecGitHub** [comment]
好的~谢谢开发

在 2017年4月2日 上午11:27，jjj201200 <notifications@github.com>写道：
