### ISSUE TITLE
请问有计划支持edge吗？

### ISSUE THREAD

**Issue by ChanglongWANG** [zacyu/bilibili-helper#361]
如题，希望作者或者其他朋友能够支持edge。

**Comment by jjj201200** [comment]
@ChanglongWANG 目前没有哦，有能力的用户可以自行移植~

**Comment by Fangsiyu** [comment]
微软的浏览器简直了，不推荐用，哈哈哈
![image](https://cloud.githubusercontent.com/assets/15528193/24733780/4d4d560a-1aac-11e7-939b-e89ac0a8418d.png)
