### ISSUE TITLE
请问不能自动抽取小电视了吗？

### ISSUE THREAD

**Issue by mylongdays** [zacyu/bilibili-helper#362]
大概20天前还是能够自动抽奖的，但是有一天我在看直播的时候发现当前直播间的抽奖没参与我才留意到的，然后我发现了新版本，但是更新了后还是不行，是把这个功能取消了吗？我用的是chrome浏览器，win10系统，家里3台电脑都是，都不能自动抽奖了。另外有个小问题，偶尔会出现一个瓜子宝箱多次领取的问题，一直弹出宝箱已领取的消息，大部分时间能自己停下，有时要刷新才能恢复，但是不常见，这10天只有2次

**Comment by jjj201200** [comment]
@mylongdays 你好，请看这篇文章：https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F

**Comment by mylongdays** [comment]
好的，明白了，谢谢
