### ISSUE TITLE
一个样式上的小问题，分享层被遮住了

### ISSUE THREAD

**Issue by yhs-APerson** [zacyu/bilibili-helper#363]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. win10 x64:
2. Chrome 57.0.2987.110 (64-bit):
3. v0.8.16.20:

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
层的z-index改一下

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by jjj201200** [comment]
你好，请问是直播间的共享弹出窗口吗？并没有问题的样子啊
