### ISSUE TITLE
无法自动领瓜子

### ISSUE THREAD

**Issue by iwoorst** [zacyu/bilibili-helper#364]
![snipaste_20170418_185814](https://cloud.githubusercontent.com/assets/21360958/25127643/30150b98-2469-11e7-9ce4-65973ccab496.png)
![snipaste_20170418_185926](https://cloud.githubusercontent.com/assets/21360958/25127642/3010fd64-2469-11e7-846f-573c362dde7d.png)

请填写以下信息:
1. 操作系统 Windows8.1
2. 浏览器版本版本 chrome59.0.3067.6（正式版本）dev （64 位）
3. 扩展版本: v0.8.16.20

一直显示正在初始化

**Comment by iwoorst** [comment]
浏览器重启了好了- -orz

**Comment by jjj201200** [comment]
直播间的脚本加载有一个初始化过程的，如果多个直播间几乎同时点开或者浏览器一下卡顿，可能导致这个过程卡住，以后先打开一个就好了
