### ISSUE TITLE
頁面替換在某些條件下會強制執行，而且沒有開關選項

### ISSUE THREAD

**Issue by i9602097** [zacyu/bilibili-helper#365]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
3. 扩展版本:

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

## Feedback
Before submitting your issue, please check to make sure of the following:
- [x] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [x] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [x] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [x] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

按慣例先報一報自己的系統
1. 操作系统 (Windows/macOS/Linux):Windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Google Chrome 版本 57.0.2987.133 (正式版本) (64 位元)
3. 扩展版本:嗶哩嗶哩助手v0.8.16.20(Chrome WebStore版)
我先前在主站的評論區已經[詢問過一次](http://disq.us/p/1hugqmh)
因為我本來認為這應是一般性幫助而不是bug
但是在回應卻說現版本已經不支持這功能無法作出設定
而我先前已經清過一遍助手資料而在看見回應後也清過B站相關資料但依舊會出現頁面替換
我開始懷疑這不是我不懂用的問題而是bug
所以我嘗試在源碼找出問題
長話短說如何找就不說了直接上結論
負責替換的應是bilibili_injected.js
而在我這邊因為某些原因在某種情況下打開某個頁面
會符合第565行`if (typeof videoInfo.cid === 'number' && $('.b-page-body .viewbox').length === 0 && $('.main-inner .viewbox').length === 0)`的情況
從而執行第566行把biliHelper.genPage設為true
而biliHelper.genPage設為true會觸發第724行及以下負責替換頁面的代碼
而當中所有設定值都沒參與決定
換句話說無論緩存和設定是如何
只要能打開符合第565行的頁面
該頁面一定被替換
這與任何設定無關是代碼問題
所以過來回報
而且我建議是一併移除由biliHelper.genPage觸發的頁面替換
因為頁面替換在新版B站已經沒用
沒權限的投稿已經不能用這方法再打開
而且替換的頁面是flash播放器對於我這種不開flash的人更是沒用
而且替換頁面中的說明打開原頁面按鈕我硬是找不到
即是打開助手後遇上這些頁面只能白白看著被替換又不能跳回去
在替換頁面下不能看片只能查看評論區
如果不能移除請務必給開關這功能的選項
現在除非我修改腳本否則無法關閉這令我困擾的功能
但是Chrome不容許自行修改套件的
變相我只能選擇是否啟用助手
請給一個能關閉頁面替換的方法

**Comment by zacyu** [comment]
Thanks. Will look into it :)

**Comment by myfreeer** [comment]
大概要改成这样
```js
if (typeof videoInfo.cid === 'number' && biliHelper.replaceEnabled && $('.b-page-body .viewbox').length === 0 && $('.main-inner .viewbox').length === 0) {
```

**Comment by jjj201200** [comment]
谢谢反馈，该文件的代码会被彻底清理。

**Comment by jjj201200** [comment]
be fixed in 0.8.16.25

**Comment by i9602097** [comment]
更新到0.8.16.25測試後確實正常了
感謝修復
