### ISSUE TITLE
港澳台限定番剧不能播放

### ISSUE THREAD

**Issue by asdfghjk1213415** [zacyu/bilibili-helper#366]
我用百度浏览器，打开限定番剧，不能播放

**Comment by jjj201200** [comment]
你好，区域限制解锁功能已经被删除，具体原因请看[这里](https://github.com/zacyu/bilibili-helper/wiki/%E4%B8%BA%E4%BB%80%E4%B9%88%E5%88%A0%E9%99%A4%E4%BA%86%E4%B8%80%E4%BA%9B%E5%8A%9F%E8%83%BD%EF%BC%9F)
