### ISSUE TITLE
发现新版本却只能下载旧版本

### ISSUE THREAD

**Issue by 335869741** [zacyu/bilibili-helper#368]
发现新版本
最新版本: 0.8.16.25 (发布于: 2017-04-03 17:24:09)
更新内容: 1.增加自动设置番剧播放器宽屏的功能
 2.增加自动设置番剧播放器合适位置的功能
 3.增加直播区小电视抽奖提醒功能（以屏幕右下角弹出框的形式）
 4.增加MAC客户端下播放器切换的功能
 5.修改了设置界面的界面布局和说明文本
 6.修复主站视频页面仍旧存在的页面替换问题
 7.修复多P视频换P后，助手视频下载地址和弹幕查询功能不同步的问题
 8.修复“去污粉”功能中，“粉丝勋章”和“礼物连击”屏蔽失效的问题
 9.将直播间SAN值项目移动到“更多”按钮中
 10.更新广告屏蔽功能，现在会直接屏蔽并包含直播区的广告，Flash播放器内的除外
然而给的链接https://bilihelper.guguke.net/只有0.8.16.20是当前本

**Comment by yoonhakcher** [comment]
卸载之后重新安装可破

**Comment by myfreeer** [comment]
https://github.com/zacyu/bilibili-helper/releases/tag/0.8.16.25

**Comment by jjj201200** [comment]
。官网我已经改了，但是由于dns缓存的缘故要等一段时间，十分抱歉。
