### ISSUE TITLE
助手启动后，无法发送弹幕的问题

### ISSUE THREAD

**Issue by davidan106** [zacyu/bilibili-helper#369]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):windows 10 enterprise ver.
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): 59.0.3071.47（正式版本）beta （64 位）
3. 扩展版本:v0.8.16.26

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
直播间发弹幕的时候，弹幕发送框显示“弹幕增强功能正在启动“ 之后就不能正常发弹幕了。

**Comment by chen2547** [comment]
你试试把弹幕增强功能关闭。

**Comment by jjj201200** [comment]
@davidan106 你好。我们的工作仅仅在维护正式的稳定的浏览器版本上，目前为：58.0.3029.110 (64-bit)。如果功能无法使用，请在设置页面关闭该功能，或者使用正式稳定版本。

**Comment by davidan106** [comment]
@chen2547 关闭之后可以用了。

**Comment by shiroringo** [comment]
这个我也有。一般是狂刷新，刷新到可以发弹幕为止
