### ISSUE TITLE
开启弹幕后CPU占用率太高

### ISSUE THREAD

**Issue by liuz430524** [zacyu/bilibili-helper#37]
0.7.0版本，弹幕效果和flash版一致了，很好用，非常感谢，但是开启弹幕后cpu占用30%左右，超过了flash，也比上个版本高，且弹幕滚动不算太流畅。稍微的看了下，弹幕是用div实现的，可否有其他的实现方法，降低一点浏览器的压力呢

**Comment by Zhuogu** [comment]
我认为 CPU 占用的增加可能和新换用的描边方式有关. 我在下一个版本中会加入弹幕阴影/描边方式的选择.

**Comment by jabbany** [comment]
感兴趣的话CCL有一个dev-cssonly分支采用css动画代替dom动画。在chrome上和移动端似乎有显著的速度优势（弹幕移动会平滑很多，CPU占用也会降低很多）缺点是兼容性不好加上在没有硬件加速的情况下会比dom操作更坑，因此不在主分支上。

**Comment by Zhuogu** [comment]
@jabbany 谢谢指出, 我之后有时间去测试一下.

**Comment by zacyu** [comment]
Obsolete now. Closing.
