### ISSUE TITLE
广告过滤误杀

### ISSUE THREAD

**Issue by daofeng2015** [zacyu/bilibili-helper#372]
![qq 20170514135913](https://cloud.githubusercontent.com/assets/14891398/26031650/f87dcdce-38ad-11e7-91d1-731a36e6aa74.png)
![default](https://cloud.githubusercontent.com/assets/14891398/26031651/f87fd8f8-38ad-11e7-8f97-a411eda92762.png)
![default](https://cloud.githubusercontent.com/assets/14891398/26031652/f899e996-38ad-11e7-9a75-e77778fe2320.png)
![default](https://cloud.githubusercontent.com/assets/14891398/26031653/f8cf5afe-38ad-11e7-83c4-9d3aafe0ecb1.png)
![default](https://cloud.githubusercontent.com/assets/14891398/26031654/f8cfab08-38ad-11e7-957c-b6ee7d1df699.png)
插件的去除广告功能会把'在线人数'和'最新投稿'误杀,请解决！！

**Comment by jjj201200** [comment]
谢谢反馈

**Comment by jjj201200** [comment]
@daofeng2015 请加测试QQ群：548321019，已经发布了新的版本，其中修复了你遇到的问题。
