### ISSUE TITLE
猎豹浏览器上宽屏失效

### ISSUE THREAD

**Issue by zg12345** [zacyu/bilibili-helper#373]
插件中开启自动宽屏，在猎豹浏览器上打开还是普通状态。系统win8.1
![image](https://cloud.githubusercontent.com/assets/28682594/26031710/fb2ab472-38af-11e7-88b5-b1416f9bf6df.png)
![image](https://cloud.githubusercontent.com/assets/28682594/26031713/0a9d94f6-38b0-11e7-8903-ee18ae56fee2.png)
![image](https://cloud.githubusercontent.com/assets/28682594/26031719/13c66c74-38b0-11e7-8a3f-8d8f6f8d8bd0.png)

**Comment by jjj201200** [comment]
谢谢反馈，你可以先切换到html5播放器，测试了一下html5播放器似乎没问题

**Comment by jjj201200** [comment]
@zg12345 请加测试QQ群：548321019，已经发布了新的版本，其中修复了你遇到的问题。
