### ISSUE TITLE
侧边「播放器设置」等被屏蔽

### ISSUE THREAD

**Issue by bonjourcs** [zacyu/bilibili-helper#374]
## 问题反馈
启用哔哩哔哩助手后，侧边栏的播放器设置等被屏蔽掉

### 环境信息:
1. 操作系统 (Windows/macOS/Linux): Win10 14393
2. 浏览器版本: Chrome 58.0.3029.81
3. 扩展版本:  0.8.16.28

### 重现步骤/尝试的解决方案
在打开哔哩哔哩助手的情况下，播放界面侧边的「播放器设置」等被屏蔽
![bilibili-helper2](https://cloud.githubusercontent.com/assets/18501114/26134451/5fdd5522-3ae1-11e7-8070-b78ff9382fc7.jpg)
禁用哔哩哔哩助手后，恢复正常
![bilibili-helper1](https://cloud.githubusercontent.com/assets/18501114/26134444/5588ea50-3ae1-11e7-81e3-e100b5d3e308.jpg)
以下是哔哩哔哩助手版本
![bilibili-helper3](https://cloud.githubusercontent.com/assets/18501114/26134463/73b167dc-3ae1-11e7-9e71-5fa4c55c2d38.jpg)

**Comment by ApolloZhu** [comment]
这是新功能...
![screen shot 2017-05-16 at 21 30 47](https://cloud.githubusercontent.com/assets/10842684/26134765/0266cd68-3a7f-11e7-8c76-bd6afdbe6565.png)

**Comment by bonjourcs** [comment]
👍 , issue close here.
