### ISSUE TITLE
卡巴斯基报告telize.guguke.net这个请求既不在黑名单，又不在白名单

### ISSUE THREAD

**Issue by vipcxj** [zacyu/bilibili-helper#375]
如题，弹出个框，说这个网址身份不明，问我要不要拦截，之前都栏掉了，毕竟这个域名太非主流，鬼知道是什么玩意，这次百度了一下才发现貌似是bilibili-helper的。不过我相信如果不百度，基本都能拦截掉。

**Comment by zacyu** [comment]
感谢反馈. 这个域名本来是为了判断用户所在地区以提供相应的绕过地区限制服务的. 然而因为疏忽, 在相关功能去除后没有及时移除初始化时的请求. 我之前已发现问题并在 45efd6c8 中移除了相关代码.
