### ISSUE TITLE
似乎28版本抽奖提示失效了？

### ISSUE THREAD

**Issue by cyiande** [zacyu/bilibili-helper#376]
明明有小电视抽奖，但是没有提示了，不知道是浏览器的原因还是什么，，，，25版本是可以的，中间几个版本没注意

**Comment by jjj201200** [comment]
谢谢你的反馈，问了一下，我的测试用户反馈说3小时前确认有效，请尝试自行排除问题，我这边将继续观察这个问题。

**Comment by jjj201200** [comment]
@cyiande 请更新到最新版本， 如果仍旧有这个问题存在，请再次开启该issue，将继续跟踪这个问题
