### ISSUE TITLE
建议增加弹幕发送回执

### ISSUE THREAD

**Issue by hfzgvxldnmvs** [zacyu/bilibili-helper#378]
b站的弹幕发送，有些情况下，服务器会抛弃发送的弹幕，
验证方法就是，开双页面，在其中一个页面下发送弹幕，在弹幕多的时候，你的弹幕会有几率被服务器抛弃，也就是另一个页面下根本就不会显示你的弹幕，
还有就是被禁言了，他也不会有提示，还一直法弹幕而不自知，
希望可以增加一个弹幕回执状态的功能，b站的弹幕状态真的太迷了，

**Comment by jjj201200** [comment]
一定程度上可以做到，b站会在播放器内自动屏蔽1s内重复发送的弹幕
