### ISSUE TITLE
建议使用https

### ISSUE THREAD

**Issue by Misachu-rail** [zacyu/bilibili-helper#379]
b站启用https已经有一段时间了，而助手目前打开的页面依然为http更易遭到运营商劫持，希望助手可以使用https页面或可以让用户选择是否使用https。谢谢。

**Comment by jjj201200** [comment]
主站已经全部https了没错，不过直播区还没有，应该不用等太久之后就可以完全还过去了。

**Comment by JorenBai** [comment]
直播区也是目前也是支持https的，只是没有强制跳转
