### ISSUE TITLE
【改进】直播界面左侧 - 我的关注 高度自适应

### ISSUE THREAD

**Issue by a253208088** [zacyu/bilibili-helper#380]
![qq 20170609171354](https://user-images.githubusercontent.com/29302427/26969150-51e99a62-4d37-11e7-85e1-d4e0c5723a1f.png)
# 能不能改成这样
![qq 20170609171436](https://user-images.githubusercontent.com/29302427/26969204-7ccdc118-4d37-11e7-84ca-347bb2307334.png)

**Comment by jjj201200** [comment]
空白确实怪怪的。不过你发现没有，里面的滚动条到底部之后再滚动是不会带动外层的滚动条一起滚动的。所以在不知道有多少条目的情况下，就是用固定较小的高度比较合适，不然你还要小心翼翼的将鼠标移动到外层，先将外层也滚动到底部才能看到里面的底部内容。

**Comment by jjj201200** [comment]
不过。我应该会考虑让他自适应最合适的高度吧。。以后再说，现在无伤大雅。

**Comment by jjj201200** [comment]
已经不复存在了
