### ISSUE TITLE
仅仅下载视频的音乐

### ISSUE THREAD

**Issue by kalinshakalin** [zacyu/bilibili-helper#381]
以前的版本有这个功能，最新版没有了。建议添加，非常重要！！！！！！

**Comment by jjj201200** [comment]
你好，这项功能在哪个版本去掉我忘记了。。。由于该功能是调用了第三方提供的服务，而该第三方此前宣布停止相关网站和服务的维护，所以我们也就删除了该功能，因为无法再继续使用了，还请您谅解。
