### ISSUE TITLE
最新版本的插件无法下载

### ISSUE THREAD

**Issue by haneu123** [zacyu/bilibili-helper#387]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Chrome
3. 扩展版本:

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
最新版本的插件（下载地址为https://dl.guguke.net/Bilibili_Helper_0_8_16_29.crx）无法下载，显示404 Not Found

**Comment by jjj201200** [comment]
你好，我这里安装是可以的。如果一直无法从该地址下载，可以从github上下载，是一样的。
https://github.com/zacyu/bilibili-helper/releases
这里会有每个商店版本。

**Comment by zacyu** [comment]
https://dl.guguke.net/Bilibili_Helper_0_8_16_29.crx 确实是 404 啊. @jjj201200 这个是需要手动上传的.
