### ISSUE TITLE
视频下载提示 Forbidden

### ISSUE THREAD

**Issue by coderfox** [zacyu/bilibili-helper#388]
### 环境信息

1. 操作系统: macOS
2. 浏览器版本: Chrome Version 60.0.3112.90 (Official Build) (64-bit)
3. 扩展版本:v0.8.16.31

### 重现步骤/尝试的解决方案

在<https://www.bilibili.com/video/av12921890/>视频下，尝试通过「助手拓展菜单」下载视频，浏览器提示「Failed - Forbidden」。

其他视频，如<https://www.bilibili.com/video/av4061568/>，也存在同样的问题。

**Comment by zacyu** [comment]
已经和 B 站沟通了这个问题, 我们会在近期修改非版权影视/番剧视频的下载方式.

**Comment by jjj201200** [comment]
@coderfox 请再尝试一下，目前应该可以正常下载了

**Comment by YikSanChan** [comment]
https://www.bilibili.com/video/av12640558/index_41.html#page=41

Same question here. Thanks

**Comment by AnneYudi** [comment]
楼主最初报错的https://www.bilibili.com/video/av12921890/视频仍然无法下载，error code: Failed-Forbidden

操作系统：OS X El Capitan 10.11.6
浏览器版本：Chrome 56.0.2924.87 (64-bit)
扩展版本：0.8.16.30

**Comment by coderfox** [comment]
曾经可以正常下载，现在又继续出现问题了。

**Comment by lzy26fate** [comment]
现在下载视频还是提示“已被禁止”，测试视频：http://www.bilibili.com/video/av15766216/

**Comment by zacyu** [comment]
Fixed  in 1f7ab3bf1315b68185e05c7df77a26fcf5a400b2
