### ISSUE TITLE
“开播推送”的消息能不消失，并显示得更显眼一点么？

### ISSUE THREAD

**Issue by gzevenli** [zacyu/bilibili-helper#389]
一般情况下，我是用网页全屏看直播的。

希望能看到特别关注的主播开播后切换去看，但现在的情况是推送消息只闪几秒就消失。一般看直播都不是100%专心的，一不留神就错过了推送消息。

全屏时好像不会显示推送消息？（我很少这样看直播，不确定）。

**Comment by jjj201200** [comment]
可以可以，当然可以~
