### ISSUE TITLE
bilibili.guguke.net ping不通？

### ISSUE THREAD

**Issue by cnbeining** [zacyu/bilibili-helper#39]
恩最近想在Biligrab里面丢几个新的黑科技。

试了一些，结果发现黑科技服务器 bilibili.guguke.net ping不通？

P.S：我把Bilibili风格的ABPlayer merge进https://github.com/cnbeining/ABPlayerHTML5-Py  了，干完了才想起来忘记要授权了。。。所以求个MIT左右的授权。。。

**Comment by zacyu** [comment]
噗... 那个服务器已经被用作他用了, 然而我当时写的那段 node.js 服务端本地没有备份 (同时丢掉的还有一个高权限 access_token 可以用来获取没有通过/未审核或者因为版权被限制的视频信息以及 cid) 我之后想想看怎么处理吧. 至于 [zacyu/ABPlayerHTML5-bilibili-ver](https://github.com/zacyu/ABPlayerHTML5-bilibili-ver), 本身就是 MIT 授权了, 所以没关系, 放心用吧.

**Comment by cnbeining** [comment]
也许我们可以用这个神token做点啥。

先关issue吧。

**Comment by zacyu** [comment]
@cnbeining bilibili.guguke.net 修复了, 目前是在香港, 我之后会通过 DNS 做成自动解析大陆 IP 到香港 (用于 mimi.gg) 港澳以及国外 IP 解析到大陆 (用于 B 站在大陆的正版番)

**Comment by cnbeining** [comment]
漂亮啊。

考不考虑加一个appkey 防止过度抓取？（虽然估计也没用

**Comment by zacyu** [comment]
暂时没必要吧, 服务器那边防火墙限制一下就好了.
