### ISSUE TITLE
【直播功能】清空礼物包裹时如果存在不能赠送的道具则确认对话框不会消失

### ISSUE THREAD

**Issue by AnnAngela** [zacyu/bilibili-helper#392]
### 环境信息

1. 操作系统 (Windows/macOS/Linux): Windows 10 Version 1703 (15063.540)
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 55.0.2883.87
3. 扩展版本: v0.8.16.30

### 重现步骤/尝试的解决方案

清空礼物包裹时如果存在不能赠送的道具（如过期道具或限定房间使用道具）则确认对话框不会消失：

0. 道具包裹内有不能赠送的道具（之前活动特别道具（啥茶来着）或者过期的道具）；
1. 打开道具包裹 ；
2. 点击【清空】；
3. 弹出的确认对话框点【确认】；
4. 对话框不会消失，但可以赠送的道具的确赠送出去了。

**Comment by shiroringo** [comment]
我有时候显示失败但是其实送出去了，刷新礼物包裹才发现

**Comment by AnnAngela** [comment]
@jjj201200 能看一下吗……

**Comment by jjj201200** [comment]
@AnnAngela emmmmmm.抱歉啊，才看到。下礼拜我抽空弄下吧，最近事情比较多。

**Comment by shiroringo** [comment]
对的，一般对话框不消失是不能赠送的礼物（比如说特定直播间才能赠送，已不存在的礼物缓存还在），偶尔提示赠送失败。我失败的时候对话框是消失了的，然后提示失败（英语提示一小行字）。赠送成功的时候有时候有英语提示，有时候没有提示。

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，同时由于利用率低助手将不再提供礼物包裹功能
