### ISSUE TITLE
希望增加默认使用flash播放器的功能

### ISSUE THREAD

**Issue by caoli5288** [zacyu/bilibili-helper#393]
### 重现步骤/尝试的解决方案
默认使用h5播放器，而h5播放器在播放某些视频时会出现一些问题，
- 音频延迟。某些视频例如https://www.bilibili.com/video/av13656985/ 随着播放进度不同步问题会越来越严重，测试了多台电脑多个浏览器都可以复现。
- 视频闪烁。这个暂时只在我的openSUSE笔记本上有出现问题，推测跟显卡驱动有关。

手动切换到flash播放器可以解决，但是希望插件可以增加默认使用flash播放器的选项，谢谢。

**Comment by zegzhi** [comment]
flash播放器只要设置一次就可以了吧，不需要插件来设置。

**Comment by caoli5288** [comment]
@zegzhi 我这里并不，每个视频都是默认h5的，需要手动调整到flash，跟bilibili有关的插件只装了助手一个，应该不存在其他干扰。

**Comment by zegzhi** [comment]
我试了一下，就是这个插件设置的Html5播放器。
只要关闭插件就可以保存Falsh播放器了。
 
 
------------------ Original ------------------
From: "Zhang"; 
Date: 2017年8月24日(星期四) 晚上6:16
To: "zacyu/bilibili-helper"; 
Cc: "曾志"; "Mention"; 
Subject: Re: [zacyu/bilibili-helper] 希望增加默认使用flash播放器的功能 (#393)

 

@zegzhi 我这里并不，每个视频都是默认h5的，需要手动调整到flash，跟bilibili有关的插件只装了助手一个，应该不存在其他干扰。

**Comment by caoli5288** [comment]
@zegzhi 那我来这反馈好像没什么问题。。

**Comment by zacyu** [comment]
@jjj201200 这边最近的修改我不是很清楚, 你看一下?

**Comment by v-Kiri** [comment]
v0.8.16.29还是更早版本有默认播放器选项来着，v0.8.16.30就没了，看个直播等半天加载

**Comment by lieEve** [comment]
@v-Kiri
直播的话，在直播间下面有个 直播帮助中心，然后 我是观众→常见问题→H5播放器

**Comment by jjj201200** [comment]
@caoli5288 当使用自动宽屏功能时，助手会强制切换到HTML5播放器，请关闭该功能。下个版本会取消强制切换，并在宽屏设置处显示提示文字。

**Comment by caoli5288** [comment]
@jjj201200 THX

**Comment by jjj201200** [comment]
已经在后续版本中改了
