### ISSUE TITLE
直播去污粉不能完全屏蔽舰队成员入场提醒

### ISSUE THREAD

**Issue by S-H-Y-GitHub** [zacyu/bilibili-helper#395]
Cent Browser 版本 2.8.5.75（正式版本） （64 位） (Chromium 60.0.3112.113)
助手版本是应用商店最新版，版本： 0.8.16.30，最后更新日期： 2017年7月29日

舰队成员入场时会出现船员的昵称，独占一行

**Comment by jjj201200** [comment]
谢谢您的反馈，目前新版本0.9.1已经在商店发布，应该是可以完全屏蔽的，请及时更新
