### ISSUE TITLE
请加一个弹幕开关弹快捷键

### ISSUE THREAD

**Issue by NicholasStone** [zacyu/bilibili-helper#397]
现在 B 站弹幕动不动就撕起来了，虽然屏蔽了好多但是防不胜防。请加一个按一下键盘某个键就能关闭弹幕弹功能吧。（虽说可以动鼠标但还是快捷键来的方便）

**Comment by jjj201200** [comment]
emmmmm.谢谢您的建议，其实之前有人提过快捷键的功能，但是一直没有时间加。我会尽快安排时间表的。非常抱歉

**Comment by xmcp** [comment]
可以参考 https://github.com/jeayu/bilibili-quickdo

**Comment by jjj201200** [comment]
#382

**Comment by hanguokai** [comment]
我做了一个 [Chrome 扩展](https://chrome.google.com/webstore/detail/turn-off-bullet-screen-fo/ffoljpljalicgkljioegejmigkkkincm)，支持了如下快捷键：
∙ D 键：开启或关闭弹幕。
∙ F 键：开启或关闭全屏模式。
∙ T 键：开启或关闭宽屏模式。
∙ J 键：后退。
∙ K 键：播放/暂停。
∙ L 键：快进。
