### ISSUE TITLE
很多分P的情况下，不能全部显示下载分段内容

### ISSUE THREAD

**Issue by ExHours** [zacyu/bilibili-helper#398]
## 问题反馈
例如在av14080602视频中有78段分P，然而助手不能**全部显示**
![img](http://wx4.sinaimg.cn/mw690/005ZXRL7gy1fjqavpz0yvj30970bdwga.jpg)
在别的视频中貌似也存在这种问题

### 环境信息
1. 操作系统 (Windows/macOS/Linux): Windows 10 专业 x64
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): 版本 61.0.3163.91（正式版本） （64 位）
3. 扩展版本: 哔哩哔哩助手：bilibili.com 综合辅助扩展 0.8.16.30

### 重现步骤/尝试的解决方案
1.打开含有多分P的视频
2.点击助手扩展菜单

**Comment by zacyu** [comment]
Hi @ExHours! 分段和分 P 是两个不同的概念. 视频分段是某一个视屏在上传到服务器后被**自动**分成了多个视频, 以方便下载和 CDN 更高效地缓存. 分 P 是视频上传者在上传时分多次上传 (通常是不同的) 内容. 目前「哔哩哔哩助手」的分队知识仅限于分段. 如需要下载其他分 P 的视频请进入该页面下载.
