### ISSUE TITLE
话说有上架火狐AMO的计划吗

### ISSUE THREAD

**Issue by OneWizard** [zacyu/bilibili-helper#401]
我昨天改了扩展id（改成了哔哩哔哩助手：bilibili.com 综合辅助扩展自己瞎试试Fx57）自己签了一份（火狐57），除了右键功能，其他功能都正常使用的

**Comment by jjj201200** [comment]
emmm，好，再推进一次进度吧，虽然已经被打回来很多次了。。。

**Comment by xmcp** [comment]
只要自动审核不出什么warning，AMO的reviewer一般不会随便拒吧

**Comment by jjj201200** [comment]
上了上了上了
