### ISSUE TITLE
关於逼哩逼哩助手使用问题

### ISSUE THREAD

**Issue by staf97531** [zacyu/bilibili-helper#403]
可以请问一下吗
有时候逼哩逼哩助手出现
弹幕查询失败，可能用户已被删除
这是什麽意思呢
应该不会是用户真的被删除了吧
因为有时候都还是一两天前发的弹幕而已
而且ｂ站应该是不会主动删除掉用户的吧

**Comment by xmcp** [comment]
问题应该不是用户被删除（即使用户被删除UID也不会消失，理论上也是可以查到的），而是注册时间比较新，[相关数据库](biliquery.typcn.com) 没有收录。

个人感觉这里的提示信息是错的。

**Comment by jjj201200** [comment]
0.9.1版本已经发布在商店和github的release中，其中修复了这项问题，请及时更新:)
