### ISSUE TITLE
B站直播开启了新的页面，希望可以跟进

### ISSUE THREAD

**Issue by sweetasaki** [zacyu/bilibili-helper#404]
旧：https://live.bilibili.com/3
新：https://live.bilibili.com/neptune/3
新旧对比，暂时不清楚是否网址中加入neptune作为测试用还是说以后都这样，希望能够匹配一下。
新版没有礼物屏蔽功能真难受。

**Comment by S-H-Y-GitHub** [comment]
目前旧版页面已经会强制跳转到新版，助手直播相关所有功能全部失效

**Comment by nnez140814** [comment]
没错，不能自动领瓜子了我很难受

**Comment by mooger** [comment]
求Dalao继续更新。。。

**Comment by shiroringo** [comment]
嗯嗯，这次直播间是版面大更新，估计助手要有比较多的变动了……希望不要下架自动领瓜子！

**Comment by jybdpy123** [comment]
用了302重定向 肯定是临时的 之后估计会改回去 但是新的UI这边很多都改了 估计助手更新会需要点时间吧

**Comment by li19910529** [comment]
现在还没有更新吗？

**Comment by wtfdsy** [comment]
现在自动领瓜子可以用这个https://greasyfork.org/zh-CN/scripts/31994-bilibili直播间自动领便当/

**Comment by li19910529** [comment]
已经下载了脚本插件，可以使用了，竟然时时更新了，非常感谢！

发送自 Windows 10 版邮件应用

发件人: zao
发送时间: 2017年11月2日 20:31
收件人: zacyu/bilibili-helper
抄送: li19910529; Comment
主题: Re: [zacyu/bilibili-helper] B站直播开启了新的页面，希望可以跟进 (#404)

现在自动领瓜子可以用这个https://greasyfork.org/zh-CN/scripts/31994-bilibili直播间自动领便当/

**Comment by zanewayne78** [comment]
还没写好么，新版页面都已经完全启用了，扩展的聊天信息屏蔽设置和包裹一键赠送很好用

**Comment by jjj201200** [comment]
缓慢。。更新中。。抱歉。对不起。实在没时间。。我加油。尽量。。

**Comment by Ldcr993519867** [comment]
楼上自动领瓜子脚本的,这下好,作者删除脚本了
闷声发大财不好么?

**Comment by zanewayne78** [comment]
那个脚本都上网站排行前20左右,火成这样闷声有用?那个作者不是也说早晚会删吗,这也能迁怒

**Comment by xiahantian** [comment]
现在只求能更新自动领瓜子_(:з」∠)_ 好难过

**Comment by Saver233** [comment]
作者已经将脚本删除了，哎

**Comment by ddok520** [comment]
Bilibili挂机助手，安全便捷好用简单的APP，全自动签到并领取签到奖励，自动挂机获取直播时长攒银瓜子和经验，自动参与小电视抽奖，自动参与活动抽奖，B站小伙伴的好帮手：https://app.tuuz.cn

**Comment by xiahantian** [comment]
上面那个……用不起来啊_(:з」∠)_ 而且没有ios的很难过

**Comment by ddok520** [comment]
@xiahantian 我可是找了好半天才找到这个软件做代替，目前PC版和安版都能用，我已经用了差不多一个小时了，一切正常。ios没有不知道

**Comment by ddok520** [comment]
我去，上面那个助手的安卓版还是云挂机，不过抽奖效果不好，挂了一晚上才抽了不到10辣条，只能当挂经验的备用了。
要抽奖的还是用这个吧：https://github.com/MoeHero/BilibiliHelper  短号房间才能抽活动和小电视，其它房间只能抽小电视，通知功能没有用

**Comment by li19910529** [comment]
这个怎么用？小白不懂，求指点~

**Comment by ddok520** [comment]
直接下载解压，拖到谷歌浏览器的扩展里面去就行了

**Comment by ddok520** [comment]
是我搞错了，扩展程序在这里 https://pan.baidu.com/s/1i5zT5B3

**Comment by yangke9** [comment]
日常催更

**Comment by jjj201200** [comment]
路上各位，请更新到0.9.1版本，该版本中，有直播区常用的三个功能，其中包括了领瓜子。
