### ISSUE TITLE
本地查询弹幕发送者

### ISSUE THREAD

**Issue by xmcp** [zacyu/bilibili-helper#406]
B站“加密”弹幕发送者用的CRC32算法很弱，可以在本地以足够小的时间代价（初始化<300ms + 此后每次查询几乎不占时间）完成hash的逆运算的工作。

所以不需要用在线的API了，可以把查询弹幕发送者的功能直接在 content script 里实现。

相关的代码可以参考：
- https://github.com/xmcp/pakku.js/blob/master/pakkujs/tooltip/crc32-crack.js **(GPL)**
- https://github.com/esterTion/BiliBili_crc2mid/blob/master/crc32.htm **(GFUL)**

**Comment by zacyu** [comment]
Looks promising :) 我这周末改一下.
