### ISSUE TITLE
插件界面显示有更新16.31版本但是官网和GitHub上都没有

### ISSUE THREAD

**Issue by whynotjinx** [zacyu/bilibili-helper#407]
那么哪里能下到呢~
另外火狐上好像搜不到呀，看前面的贴半年前就在审核了不知道是不是还没上架

**Comment by zacyu** [comment]
火狐后来排到了, 但是因为使用了 minified 的代码没有过. 准备在之后重构并精简 dependency 后再提交审核. 目前如果有需要可以手动加载.

**Comment by whynotjinx** [comment]
最近收到邮件好像自动审核过了，没仔细看不知道是本身过了还是Chrome插件转火狐过了

**Comment by nibuhuiba** [comment]
希望加快跟进速度

**Comment by jjj201200** [comment]
已经更新到0.9.1版本，请及时更新
