### ISSUE TITLE
什么时候辅助领瓜子功能才会继续有效？

### ISSUE THREAD

**Issue by xiahantian** [zacyu/bilibili-helper#408]
自从B站页面更新之后，辅助领瓜子的功能似乎一直都没有再回来？
以及，关于开播通知，原本不是在直播间里可以特别关注的么？现在设置开播通知的东西到哪去了？

**Comment by nibuhuiba** [comment]
不要着急，好东西都是慢慢来的

**Comment by ddok520** [comment]
已经测试到16.33版了，正式版应该快了吧

**Comment by jjj201200** [comment]
@xiahantian @nibuhuiba 0.9.1中该功能可以正常运作，请及时更新
