### ISSUE TITLE
助手box被tag遮挡

### ISSUE THREAD

**Issue by zodiacg** [zacyu/bilibili-helper#41]
B站更新了新的tag系统后，tag的点赞图标和文字会漂浮在哔哩哔哩助手弹出的下载/切换播放器的box的上方，如图：

![screenshot](http://r.loli.io/Br2MVf.png)

**Comment by zacyu** [comment]
Fixed in 063520b2e3e51c34b90ecc09fe1a198bc85896e1 and will be included in the next release.
已在 063520b2e3e51c34b90ecc09fe1a198bc85896e1 中修复, 下个发行版本中将包含这个变更.
