### ISSUE TITLE
助手更新了，不过一开礼物包裹增强，包裹就变得很奇怪了，关了可以恢复正常

### ISSUE THREAD

**Issue by xiahantian** [zacyu/bilibili-helper#410]
我的包裹就只剩下下面这一大串文字

道具包裹
一键清空
满亲密度清空
清空本类
6天
10
6天
50
14天
11919
26天
42
27天
164
28天
128
29天
276
30天
50
清空本类
永久
1
清空本类
29天
3
清空本类
6天
5
清空本类
14天
748

**Comment by li19910529** [comment]
感觉极端不友好啊，不能换回原来那种吗？

**Comment by jouiymo** [comment]
+1

**Comment by jjj201200** [comment]
应该再0.9.1修复了，之前存在一些小问题
@li19910529 @jouiymo @xiahantian 请更新
