### ISSUE TITLE
360极速浏览器无法安装v0.9.1

### ISSUE THREAD

**Issue by zkh971220** [zacyu/bilibili-helper#411]
环境信息：
1. 操作系统：WIn10 1703
2. 浏览器版本：9.0.1.154
3. chrome内核版本：55.0.2883.87
3. 扩展版本：v0.9.1

双击打开v0.9.1的crx文件就会提示：程序包无效：CRX_VERSION_NUMBER_INVALID（crx版本号无效）
v0.8.16.29及其之前的版本都能安装
安装v0.9.1前已将旧版本卸载
截图请见：https://pan.baidu.com/s/1nuPog3n

**Comment by xmcp** [comment]
https://www.v2ex.com/t/413130

**Comment by zacyu** [comment]
@xmcp 你方便帮忙下载一个兼容旧版的发到这边来吗? 谢谢.

**Comment by xmcp** [comment]
chromefor.com 下载的好像就是兼容版本

**Comment by zacyu** [comment]
已更新 (Ｔ▽Ｔ)

**Comment by zkh971220** [comment]
@xmcp 感谢提供！
