### ISSUE TITLE
屏蔽直播播放区域的礼物全站通告弹幕

### ISSUE THREAD

**Issue by std4453** [zacyu/bilibili-helper#412]
直播区域经常有全站通告的礼物弹幕，一般由送礼物的高能预警触发，但是他的开关和所有弹幕是一起的，不能单独选择关闭，而且占地很大，因此如果想看弹幕的话会被影响到。
有没有可能提供这样一个功能，选择是否屏蔽这些礼物全站通告的弹幕呢？

平台：bilibili直播网页版（新版页面）
系统：win10
浏览器：chrome 63.0
（虽然以上内容似乎意义不大）
bilibili助手版本：0.9.1

一个简单的实现方法是直接加入一个开关控制div.bilibili-live-player-video-gift的显示与否，直接在样式里面加上visibility=hidden即可。

**Comment by jjj201200** [comment]
我的理解中，高能预警触发会在播放器上方飞过高能弹幕
而助手仅仅只是屏蔽了右侧聊天框中的内容及其2233娘
另外，如果说要单独屏蔽的话其实很多都应该分开来了，但是这么做会导致过滤选项列表太长
最后，介于您的反馈，我考虑将他归类为“礼物信息”的屏蔽中，后续版本中将会看到该项更新

**Comment by jjj201200** [comment]
我的理解中，高能预警触发会在播放器上方飞过高能弹幕
而助手仅仅只是屏蔽了右侧聊天框中的内容及其2233娘
另外，如果说要单独屏蔽的话其实很多都应该分开来了，但是这么做会导致过滤选项列表太长
最后，介于您的反馈，我考虑将他归类为“礼物信息”的屏蔽中，后续版本中将会看到该项更新
