### ISSUE TITLE
直播的开播推送不作用

### ISSUE THREAD

**Issue by z791382465** [zacyu/bilibili-helper#414]
## 问题反馈
如標題，關注中的主播開播不會出現通知

### 环境信息
1. 操作系统: Windows 10 Pro 1709
2. 浏览器版本: Chrome 63.0.3239.108
3. 扩展版本: 0.9.1

### 重现步骤/尝试的解决方案
設置如下圖
https://i.imgur.com/YLlKh1Q.png
若開啟 检查"我的关注"更新，會正常跳出視頻的更新通知，但此功能開啟與否都不會出現开播推送的通知

**Comment by jjj201200** [comment]
直播区的开播推送和我的关注中的视频更新通知是两件事情
直播区功能目前只有老三样：领瓜子，礼物包裹，去污粉，可能还要加上自动签到吧
其他的还没有进行测试，后续会继续，请耐心等待

**Comment by z791382465** [comment]
感謝您的回覆
另，目前直播自動簽到是有正常作用的
不過網頁內容不會刷新，點擊簽到會顯示已簽到的錯誤，實質上已完成簽到
