### ISSUE TITLE
直播礼物包裹会出现的小问题。

### ISSUE THREAD

**Issue by Fireblossom** [zacyu/bilibili-helper#415]
![bili](https://user-images.githubusercontent.com/16226671/34453314-5fbc3ee2-ed8c-11e7-8f3e-cd89856b629d.gif)
这样就比较困扰2333

**Comment by Fireblossom** [comment]
![bili](https://user-images.githubusercontent.com/16226671/34453337-3a4641ca-ed8d-11e7-97d0-ccdfc72a7b5f.gif)
比较难受

**Comment by jjj201200** [comment]
=,=行吧，不知道你是什么浏览器，样式都是错的，还请用一下靠谱点的浏览器吧，这个问题我会再调整以下的

**Comment by Fireblossom** [comment]
我用的是Chrome啊。。。。

**Comment by jjj201200** [comment]
@Fireblossom 那怕是要更新了
