### ISSUE TITLE
Cannot load extension with file or directory name…

### ISSUE THREAD

**Issue by 805447391** [zacyu/bilibili-helper#417]
修复：把_metadata前面的下划线去掉就可以了。。

**Comment by xmcp** [comment]
你是把CRX手动解压了再加载的吗？

- 如果是的话，那就是正常现象；
- 如果不是的话，可能是你的浏览器比较奇怪。

**Comment by 805447391** [comment]
@xmcp 直接安装crx没反应。不得已手动加载，报该错误。

**Comment by 805447391** [comment]
使用compat版没毛病。谢谢！

**Comment by xmcp** [comment]
直接安装crx没反应 这就已经很奇怪了……

**Comment by jjj201200** [comment]
@xmcp 拖拽到扩展程序页面
