### ISSUE TITLE
[BUG]番剧页面助手按钮消失

### ISSUE THREAD

**Issue by rosekc** [zacyu/bilibili-helper#422]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):63.0.3239.84（正式版本） （64 位）
3. 扩展版本:0.9.2

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
如图
![image](https://user-images.githubusercontent.com/17542574/34677789-2cabac26-f4cc-11e7-8c3a-cde632c095e2.png)
另外在正常页面，和充电按钮有错位。
![image](https://user-images.githubusercontent.com/17542574/34677735-fdd4bc62-f4cb-11e7-8cac-e852983e7c70.png)

**Comment by zacyu** [comment]
感谢反馈. 番剧页面已经在 e6b57a8d4a4963ae2c97b948c734563bd8ca62f5 中修复, 我们将会在即将发布的 v0.9.3 版本中修复. 此外我也会对样式稍作调整.
