### ISSUE TITLE
助手常驻占用内存过大，望优化。

### ISSUE THREAD

**Issue by LaserUFO** [zacyu/bilibili-helper#423]
1. 操作系统 (Windows/macOS/Linux):win10 1709
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Chrome DEV x64 65.0.3311.3
3. 扩展版本:0.9.2

不打开任何B站相应页面，助手插件的内存占用便可以达到139,512K（在chrome资源管理器中可以看到），即使强制重启扩展程序也一样。如图，由于本人电脑内存较小 有时不得不关闭该扩展，对使用造成了一定的不便，希望作者大大能在百忙之中进行一些优化。
![image](https://user-images.githubusercontent.com/19631046/34678320-bd37c436-f4cd-11e7-880f-3eeaaf9b19a6.png)

**Comment by xmcp** [comment]
逆向CRC32应该不需要这么多内存才对。
![image](https://user-images.githubusercontent.com/6646473/34830295-6e94cb82-f71e-11e7-8342-8430efaf4bf5.png)
你看 [这个 _crc32_cracker](https://github.com/xmcp/pakku.js/blob/master/pakkujs/injected/crc32-crack.js) 才占2.5MB内存。

**Comment by LaserUFO** [comment]
我也不是很明白这是什么原因，有条件测试一下其他版本chrome内核浏览器
