### ISSUE TITLE
辅助领瓜子和左下角是“点击抽奖”冲突

### ISSUE THREAD

**Issue by lanmaoaiwo** [zacyu/bilibili-helper#426]
打开辅助领瓜子，会每5秒左右自动刷新页面，关闭就好了。
![111](https://user-images.githubusercontent.com/24777853/35181504-cec1cd30-fdfd-11e7-9b56-f1b16073717d.jpg)

**Comment by jjj201200** [comment]
抱歉回复晚了，请问这是什么活动或者特殊直播间才有的吗？现在还有吗？

**Comment by lanmaoaiwo** [comment]
没了，一般是有官方做活动，这里可以抽奖。

**Comment by jjj201200** [comment]
emmmm，一后这种就不管他了，指不定什么时候又改成什么样子了

**Comment by lanmaoaiwo** [comment]
http://live.bilibili.com/91233

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新
