### ISSUE TITLE
B站搜索部分URL模式改变

### ISSUE THREAD

**Issue by AnnAngela** [zacyu/bilibili-helper#427]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows 10.0.16299.125
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 63.0.3239.132
3. 扩展版本: v0.9.3

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案

选中任意字词右键点击【用 哔哩哔哩 搜索】即可。

原因是因为B站的搜索网址从`https://www.bilibili.com/search?keyword=%s`变成`https://search.bilibili.com/all?keyword=encodeURIComponent(%s)`。将相关URL模式修改一下即可。

**Comment by jjj201200** [comment]
谢谢反馈

**Comment by AnnAngela** [comment]
感谢修复
