### ISSUE TITLE
html5播放器卡顿无法观看

### ISSUE THREAD

**Issue by kuuki00** [zacyu/bilibili-helper#428]
请填写以下信息:
1. 操作系统 Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):360极速浏览器9.01和chrome 63.0
3. 扩展版本:0.9.3

为什么使用看直播时使用html5播放器会卡顿而且还会一直转圈圈无法播放，flash播放器可以，当然也可以只用flash，但是嘛，就是反馈一下
用chrome卸载拓展后，播放无问题，这是我个人的问题还是？？

**Comment by jjj201200** [comment]
请问现在还有这个问题吗，这么多天过去了暂时没有收到其他类似的反馈
