### ISSUE TITLE
有些视频下面菜单栏没有助手选项

### ISSUE THREAD

**Issue by xiuya0226** [zacyu/bilibili-helper#429]
1. 操作系统 Windows
2. 浏览器版本 Google Chrome  64.0.3282.140
3. 扩展版本:0.93
我是b站一个up主，有时会有一些人在视频里捣乱发一些恶意弹幕，今天想查某个视频的弹幕发现没有助手选项，能解决吗？

**Comment by zacyu** [comment]
应该是遇到了正在 A/B 测试的新版播放页, 在 43ad3507309cd1f70d6da7b334f45a8742a8e388 中已添加支持, 会在 B 站正式部署新版后发布一个更新.

**Comment by xmcp** [comment]
@zacyu 请问新版播放页的 DOM 结构有很大改变吗？

我这里没有找到手动进入测试版的方法。
似乎新版播放页的hash是 `41eb959c`（旧版是 `835d1ef1`），但看起来毫无区别？

我是不是进了假的测试？……
