### ISSUE TITLE
请问用助手怎么下载B站视频？

### ISSUE THREAD

**Issue by hui305** [zacyu/bilibili-helper#430]
请问用助手怎么下载B站视频？

怎么下啊？没找到下载的方式啊～～，需要登录吗？

**Comment by hui305** [comment]
我安装了chrome插件，可是还是没找到下载的位置！
你给我链接～我看看。我是PC。@jjj201200

**Comment by jjj201200** [comment]
最近有些页面在测试，等稳定下来了我们会更新

**Comment by akimusume** [comment]
我的一直显示“视频地址获取中，请稍等…”，试了好几个视频，没有能用的。

**Comment by zacyu** [comment]
Might also be related to #432 (fixed in 349b55b4c222ef36080f58574a22215874fc54cb).

**Comment by jjj201200** [comment]
@akimusume @hui305 现在还有问题吗？

**Comment by akimusume** [comment]
@jjj201200 谢谢，能用了

**Comment by hui305** [comment]
@jjj201200 现在一个视频是分段下载的吗？能否合在一起？谢谢～
