### ISSUE TITLE
直播里的自动领宝箱有的有BUG

### ISSUE THREAD

**Issue by choyike** [zacyu/bilibili-helper#431]
只针对部分官方直播间。
就是有的带抽奖的那种。
会一直刷新啊刷新，关了助手就正常了。
蛮影响直播使用的

**Comment by xmcp** [comment]
#426

**Comment by jjj201200** [comment]
可以在设置界面把领瓜子功能单独关掉，
话说不停刷是指？可以提供一下目前有效的房间号吗
