### ISSUE TITLE
直播 - 聊天信息屏蔽 失效

### ISSUE THREAD

**Issue by Skimige** [zacyu/bilibili-helper#433]
### 环境信息
1. 操作系统 : Windows
2. 浏览器版本 : Chrome 64.0.3282.119
3. 扩展版本 : 0.9.3

### 重现步骤/尝试的解决方案
打开任意直播间。去污粉图标已经消失了。

**Comment by jjj201200** [comment]
谢谢反馈

**Comment by Skimige** [comment]
其他很多直播相关的功能可能也失效了。
顺便问问新版啥时候出 = = B站这一波不让人安心过年啊

**Comment by jjj201200** [comment]
@Skimige 已经推送了更新代码，再观察几天看有没有新变化，之后会推送商店
