### ISSUE TITLE
希望视频下载分段能够自动合并

### ISSUE THREAD

**Issue by Canscx** [zacyu/bilibili-helper#434]
1. 操作系统 Windows
2. 浏览器版本：Google Chrome
3. 扩展版本:0.9.3

作者大大 表示现在似乎有很多视频下载地址一直显示正在获取中
并且希望作者大大能加上一个功能：下载的视频分段能够自动合并

**Comment by xmcp** [comment]
不如试试 http://www.jijidown.com/ ？

**Comment by Canscx** [comment]
嗯 好的 谢谢

**Comment by jjj201200** [comment]
#385
