### ISSUE TITLE
chrome66中快捷菜单异常

### ISSUE THREAD

**Issue by asoulist** [zacyu/bilibili-helper#435]
## 问题反馈
![image](https://user-images.githubusercontent.com/15167940/36128118-9d008056-109b-11e8-8623-41c90c672f08.png)
如图所示，在浏览器顶栏点击图标不能正常呼出快捷菜单，并且在宽窄两种外框之间快速闪动
（但是右键菜单是正常的）

### 环境信息
请填写以下信息:
1. 操作系统 (Windows 10 Pro Insider Preview Build 17074.rs_prerelease_flt.180116-1539):
2. 浏览器版本(Chrome Canary 66.0.3345.0 64位):
3. 扩展版本(v0.9.3.2):

**Comment by zacyu** [comment]
Not reproducible with Chrome Canary 66.0.3346.0 on macOS 10.13.3.
