### ISSUE TITLE
弹幕发送者再出bug

### ISSUE THREAD

**Issue by NJC6115HD4** [zacyu/bilibili-helper#436]
![image](https://user-images.githubusercontent.com/32643397/36148903-968dc974-10f8-11e8-88b6-b39b49e64a02.png)
选择弹幕内容后，解析出来只显示用户的UID
有时甚至会解析出两个用户的UID（如图）

**Comment by xmcp** [comment]
前者这是正常现象
后者是B站本身的缺陷

**Comment by zacyu** [comment]
解析用户昵称在最新版中应该是没问题的; 出现多个用户 UID 是因为 hash collision 因 B 站本身的 implementation decision 决定的.

**Comment by jjj201200** [comment]
@zacyu 要不要把另一个按照简单规则过滤掉，我看了下好像全部都是0级的
