### ISSUE TITLE
v0.9.4 疑似无法点击节奏风暴小标志

### ISSUE THREAD

**Issue by Skimige** [zacyu/bilibili-helper#437]
### 环境信息
1. 操作系统: Windows
2. 浏览器版本: 64.0.3282.167 x64
3. 扩展版本: v0.9.4 weibo crx

### 重现步骤/尝试的解决方案
1. 碰上一个节奏风暴（这已经很困难了，我也只遇到两次所以不太确定）
2. 点击节奏风暴小图标，没有验证码弹窗也没有领取提示。

可能和油猴脚本有冲突，或者是油猴脚本导致的，观察中。

**Comment by jjj201200** [comment]
这。。。。。怕是只能你们自己测一测了，去一个没人的直播间发个节奏风暴测试测试

**Comment by Skimige** [comment]
@jjj201200 成本有点高 = =
我今天开着油猴和插件，又领到一次，所以不知道到底什么毛病，可能要输验证码的时候就弹不出窗。
这个不是很重要的 bug 可以先放放。

**Comment by pickmeup12345** [comment]
**环境信息**
操作系统: Windows 10
浏览器版本: 很早以前一直到现在的64.0.3282.186 x64
扩展版本: 几个版本以前一直到v0.9.4 weibo crx
**重现步骤/尝试的解决方案**
与1L相同，不过前前后后已经几十次了可能，遇到节奏风暴点击图标无任何响应/反馈
目前还未测试过关闭tempermonkey是否能正常领取，不过不是很重要的bug，可以放一放

**Comment by jjj201200** [comment]
嗯，这个问题我昨晚无意间也发现了，点了毫无反应，会找时间排查一下的

**Comment by jjj201200** [comment]
目前已经正常了
