### ISSUE TITLE
希望bilibili-helper能推出firefox版本

### ISSUE THREAD

**Issue by orange1423** [zacyu/bilibili-helper#438]
希望能推出firefox版本。现在只有Chrome浏览器可以使用，我们这些firefox党早已对bilibili-helper垂涎欲滴了...... [据firefox所说](https://developer.mozilla.org/zh-CN/Add-ons/WebExtensions/Porting_from_Google_Chrome)，Chrome插件转firefox插件非常简单。利用[Chrome Store Foxified](https://addons.mozilla.org/zh-CN/firefox/addon/chrome-store-foxified/)甚至可以直接把Chrome组件转为firefox组件。所以......希望尽快推出firefox插件哦。祝新年快乐！

**Comment by xmcp** [comment]
#401

**Comment by jjj201200** [comment]
啊，秒过了，去看看吧。。惊了简直

**Comment by xmcp** [comment]
https://blog.mozilla.org/addons/2017/09/21/review-wait-times-get-shorter/

理论上应该是秒过的

**Comment by jjj201200** [comment]
之前是17年4月份的时候提交的，排队排了个把月
