### ISSUE TITLE
希望增加快捷键开关弹幕功能

### ISSUE THREAD

**Issue by LimonTT** [zacyu/bilibili-helper#439]

**Comment by LimonTT** [comment]
八嘎, 某个按键打不出来

**Comment by LimonTT** [comment]
谢谢, 找到快捷键的js了[https://greasyfork.org/zh-CN/scripts/26939-bilibili-h5%E6%92%AD%E6%94%BE%E5%99%A8%E5%BF%AB%E6%8D%B7%E6%93%8D%E4%BD%9C](url)

**Comment by xmcp** [comment]
#397

**Comment by LimonTT** [comment]
感谢 [GreasyFork](https://greasyfork.org/zh-CN/scripts/26939-bilibili-h5%E6%92%AD%E6%94%BE%E5%99%A8%E5%BF%AB%E6%8D%B7%E6%93%8D%E4%BD%9C)
