### ISSUE TITLE
右键菜单上的一点小小建议

### ISSUE THREAD

**Issue by peterwang1996** [zacyu/bilibili-helper#44]
如果能自动识别在浏览器中选中的[ac/av/sm+数字]这样的字符串然后再右键菜单里添加‘跳转收看’选项，会极大提升用户体验。

**Comment by zacyu** [comment]
经测试, 因为 Chrome 本身对有条件的 context menu 没有较好的支持, 目前没有有效的实现方式, 决定暂时搁置这个建议. 选中 av 号之后直接点搜索选项也可以跳转至视频.

**Comment by peterwang1996** [comment]
哦是这样啊……不过还是谢谢你哟~辛苦啦~
