### ISSUE TITLE
请问现在获取视频的playurl是如何进行sign的呢.

### ISSUE THREAD

**Issue by dongshimou** [zacyu/bilibili-helper#440]
`https://interface.bilibili.com/v2/playurl`
web端似乎启用了V2的接口.然后发现以前的sign方式一直返回 checksum error

chrome抓取了一个正确的请求.
https://interface.bilibili.com/v2/playurl?cid=32253539&appkey=84956560bc028eb7&otype=json&type=&quality=0&qn=0&sign=0d1b3ad4dd857c060d28a31a05d13835

尝试不排序,按照以往的方式md5,依旧是checksum error.请问该怎样sign呢?

**Comment by jjj201200** [comment]
emmmmmmm我们并没有算sign呢

**Comment by dongshimou** [comment]
方便回答是怎么做的么? 我想做一个bilibili相关的桌面插件.然而目前只获取到了弹幕文件.

**Comment by zacyu** [comment]
我们现在是直接用 chrome.webRequest API 抓浏览器本身发出的请求 :) 虽然大概没有帮上你的需求.

**Comment by myfreeer** [comment]
桌面可以考虑直接调用[you-get](https://github.com/soimort/you-get)或者[youtube-dl](https://github.com/rg3/youtube-dl)
