### ISSUE TITLE
FireFox版本哔哩哔哩助手辅助领瓜子有Bug

### ISSUE THREAD

**Issue by orange1423** [zacyu/bilibili-helper#442]
![default](https://user-images.githubusercontent.com/36698236/36603350-6b45fa02-18f5-11e8-8915-cd02b034aa70.png)
就像这样，无法正常领取......只有FireFox版本有这个问题，谷歌浏览器没有此问题

**Comment by orange1423** [comment]
一直卡在 08：57 不动

**Comment by jjj201200** [comment]
emmmmm已经修复了，等待下个版本吧
