### ISSUE TITLE
显示视频封面原图

### ISSUE THREAD

**Issue by hardywen** [zacyu/bilibili-helper#443]
很多时候，up主们都用一张很吸引人的图作为封面，但封面图显示很小。所以弹幕里经常出现“交出封面”之类的话。这是背景。
进入视频详情页面的时候，其实封面原图就在里面，只是要通过查看原代码拿地址，但一般用户并不懂这个。所以如果做成一个按钮之类的，直接显示封面原图就好了。

**Comment by jjj201200** [comment]
要是可以把分段视频合并一下就好了呢233333

**Comment by AnnAngela** [comment]
其实我写了个油猴脚本来着……https://greasyfork.org/zh-CN/scripts/33411-bilibilicover
