### ISSUE TITLE
直播间自动领宝箱似乎炸了

### ISSUE THREAD

**Issue by std4453** [zacyu/bilibili-helper#447]
环境：Win10, chrome 64 x64
直播间：528
问题描述：进入直播间页面后宝箱开始倒计时，（一般）从3:00开始，然后计时器大概走4~5秒左右（也就是到2:55/2:56，测试中均有出现过）便停止，然后不会自动领宝箱，点击宝箱图标也不会跳出来窗口。有一个特别的变化是宝箱图标下面的计时器在停止的时候会突然变大一些，不过原因不确定，不保证能复现。
复现方法：直接进入直播间即可，不要动任何其他东西。
问题原因我试着排查一下。

**Comment by std4453** [comment]
首先在测试的所有其他直播间均可复现，无论是否已关注。
然后原因我大概有一个猜想。
理论上宝箱是在div.treasure-box中，而这个div应该仅存在一个，但是在出现bug的时候（就是看到的计时器停止更新的那一刻）多出来了一个，导致存在两个div.treasure-box。第一个中的div.count-down会正常更新，而第二个则不会，会停在多出来第二个的那一刻。
奇怪的是两个div.treasure-box的id名并不一样，第一个（也就是在更新但是看不到的那个）是#originTreasurePanel，而第二个（也就是不更新但是看的到的那个）是#helperTreasurePanel。因此我怀疑helper指的是bilibili Helper，而最近前端更新了他的id名称导致bilibili helper的脚本中匹配错误。
然后div#originTreasurePanel的几乎所有内容都和div#helperTreasurePanel一样，除了带有一个style="display:none"导致它不会显示出来。
然后为什么倒计时的框会变大呢？我发现原因是因为bilibili helper提供的live.min.css中存在一条#helperTreasurePlanel.count-down{padding: 3px 4px}，覆盖掉了原有的.count-down{padding: 2px 3px}，因而比原来大一些。当然#originTreasurePanel的div.count-down不受其影响，这也令我相信是前端更新了id然后并helper没有跟进。

另一条线索：
在倒计时停止前选中元素，发现这个元素在看的到的倒计时停止时其实还在走，意思是最初在走的倒计时成为了后来的div#originTreasurePanel，#helperTreasurePanel是多出来的那个。
但是在倒计时停止之前实际上这个div.treasure-box实际上是没有id的，在倒计时停止的瞬间拥有了#originTreasurePanel，而之后0.5秒左后内又带上了style="display:none"，目前不确定激活这一事件的是bilibili直播自己的前端js还是helper的js。

**Comment by std4453** [comment]
线索3：保持哔哩哔哩助手运行但仅关闭”辅助领瓜子”时，运转正常，因此问题应该是出在helper的js里面。并且在此时刻`div.treasure-box`并没有`#originTreasurePanel`或者`#helperTreasurePanel`并且`div.treasure-box`也仅有一个。
线索4：在计时器停止运转之前也只有一个`div.treasure-box`。
（顺便纠正一下之前所有的"helperTreasurePanel"和"originTreasurePanel"都应该替换为“helperTreasurePlanel"和"originTreasurePlanel"，似乎是手滑了呢）
然后恕我才疏学浅，开发者页面的Sources里面只能看到一个live-content-script.min.js，好短啊，没看懂是怎么实现这么多功能的（捂脸），所以似乎不太能进一步分析下去了呢。

**Comment by std4453** [comment]
另外一点就是似乎在直播开始后会疯狂请求http://api.live.bilibili.com/FreeSilver/getCurrentTask和http://api.live.bilibili.com/freeSilver/getCaptcha?ts=<当前时间>，后者的initiator似乎是bilibili自己的js，前者则是jquery，可惜我前端水平不行，不知道实际上是谁调用的，不过似乎还是bilibili_live.min.js？似乎直播开始之前则不会，不知道这个跟这个情况有没有关系。没来得及验证关了helper会怎样，吃完饭再来啦。

**Comment by std4453** [comment]
我胡汉三又回来啦！
进一步研究表明，不是因为前端改了id，实际上id全部都是helper加上去的，原来并没有id。

一个可能的问题在于，`http://api.live.bilibili.com/FreeSilver/getCurrentTask`现在只会返回一个”维护中“的内容，并且格式是`text/html`，导致`$.get('//api.live.bilibili.com/FreeSilver/getCurrentTask', {}, () => {}, 'json').promise()`（`src/bilibili_live.js:953`）直接进入failed，导致`checkNewTask()`（`src/bilibili_live.js:821`)中直接跳过了`donw()`中的代码而进入`fail()`的代码，也就是循环执行`Live.treasure.checkNewTask()`，从而继续请求`http://api.live.bilibili.com/FreeSilver/getCurrentTask`而无限循环。

解决方法为：
1. src/bilibili_live.js:845的`fail()`中在`checkNewTask()`之前添加一句`console.error()`，这样会把这种类型的情况报错出来，方便调试。
2. src/bilibili_live.js:953的`getCurrentTask()`中将
``` javascript
return $.get('//api.live.bilibili.com/FreeSilver/getCurrentTask', {}, () => {}, 'json').promise();
```
改为
``` javascript
return $.get('//api.live.bilibili.com/lottery/v1/SilverBox/getCurrentTask', {}, () => {}, 'json').promise();
```
这是最新可用的getCurrentTask地址。

其他过会儿再补充，我先fork试一下，可以的话提PR吧。

**Comment by std4453** [comment]
所有原来的`//api.live.bilibili.com/FreeSilver/`下的链接都需要改成`//api.live.bilibili.com/lottery/v1/SilverBox/*`，主要都在bilibili_live.js下面。

**Comment by jjj201200** [comment]
=,=哇哦，辛苦了，虽然我昨晚下班后改过了。不过有劳了，后续我会跟进的~

**Comment by jjj201200** [comment]
如果可以的话，希望可以查找一下html5播放器的各功能接口，他们都打成模块进行混淆了，不能很方便的调用了，类似于30字数限制分段发送之类的功能还是有接口比较好一些
