### ISSUE TITLE
直播 - 清空多个辣条时，不能一次清空完

### ISSUE THREAD

**Issue by Skimige** [zacyu/bilibili-helper#449]
### 环境信息
1. 操作系统: Windows 10 Pro x64
2. 浏览器版本: 65.0.3325.146 x64
3. 扩展版本: v0.9.4 weibo ver.

### 重现步骤/尝试的解决方案
1. 道具包裹中有六个不同有效期的辣条
2. 点击清空，发现有两个有效期的辣条消失了，其他的还在
3. 重复以上步骤，4 个 -> 2 个

**Comment by jjj201200** [comment]
谢谢反馈，我会找时间检查一下

**Comment by Skimige** [comment]
经测试该 bug 在 0.9.6 依旧存在 = = 不过无关大雅。

**Comment by liushengqi000** [comment]
`sendLineAjax(a:id,c:giftArr,d:dom)
  always(function(){
    b.giftpackage.sendPanel.sendLineAjax(a-1, c)
  })

sendLineAjax(a:id,c:giftArr,d:undefined)
  e=b.giftpackage.sendPanel.sendAjax(f:gift, d:undefined);

sendAjax: function(a:gift, c:undefined, d:undefined)
  b.giftpackage.sendPanel.successCallback(a:gift, e:store, c:undefined, d:undefined)

successCallback: function(a:gift, c:store, d:undefined, e:undefined)
  b.liveToast(d:undefined, "送出去啦～诶嘿嘿" + b.randomEmoji.helpless(), "success"),

b.liveToast = function d(a:undefined, b, c, d)
  !a.className && !a.attributes)throw new Error(i + " 传入 element 不是有效节点.");

Uncaught TypeError: Cannot read property 'className' of undefined 
a.className(a:undefined)
`
循环送礼时第二次的节点参数为空,导致post callback 调用的 liveToast 函数内部出现 undefined.className

**Comment by liushengqi000** [comment]
- 

> 
122
>

**Comment by liushengqi000** [comment]
bilibili_live.min.js

`
sendLineAjax(a:id,c:giftArr,d:dom)
  always(function(){
    b.giftpackage.sendPanel.sendLineAjax(a-1, c)
  })

sendLineAjax(a:id,c:giftArr,d:undefined)
  e=b.giftpackage.sendPanel.sendAjax(f:gift, d:undefined);

sendAjax: function(a:gift, c:undefined, d:undefined)
  b.giftpackage.sendPanel.successCallback(a:gift, e:store, c:undefined, d:undefined)

successCallback: function(a:gift, c:store, d:undefined, e:undefined)
  b.liveToast(d:undefined, "送出去啦～诶嘿嘿" + b.randomEmoji.helpless(), "success"),

b.liveToast = function d(a:undefined, b, c, d)
  !a.className && !a.attributes)throw new Error(i + " 传入 element 不是有效节点.");

Uncaught TypeError: Cannot read property 'className' of undefined
a.className(a:undefined)
`
循环送礼时第二次的节点参数为空,导致post callback 调用的 liveToast 函数内部出现 undefined.className

**Comment by jjj201200** [comment]
@liushengqi000 啊万分感谢。我在写新版本，现在的0.9.9不打算更新了，在新版本中会解决你反馈到的这个bug

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，由于目前b占对白嫖党不友好，新版中将不再增加礼物包括功能
