### ISSUE TITLE
直播 - 产生大量验证码/领宝箱的请求

### ISSUE THREAD

**Issue by Skimige** [zacyu/bilibili-helper#450]
### 环境信息
1. 操作系统: Windows 10 Pro x64
2. 浏览器版本: 65.0.3325.146 x64
3. 扩展版本: v0.9.4 weibo ver.

### 重现步骤/尝试的解决方案
今天的宝箱已经领完了
![image](https://user-images.githubusercontent.com/9017470/37209905-c4453f22-23e1-11e8-8bc7-7f6c0563c3c3.png)

**Comment by xfl03** [comment]
已经在 https://github.com/zacyu/bilibili-helper/commit/2f6bd85f2b46c4d13552c4e424f732a978cdabc6 中修复
与 #447 #448 重复

**Comment by Skimige** [comment]
@xfl03 确实如此，谢谢提醒。
