### ISSUE TITLE
无法自动领取宝箱了

### ISSUE THREAD

**Issue by zx53770** [zacyu/bilibili-helper#451]
在直播间第一个宝箱倒数到2分56秒左右就卡住不动了，最开始以为是改版没管，过了半个小时看，第一个宝箱也没有领取成功，请问下这个自动领宝箱的功能是不是出问题了？
1. 操作系统 :Windows 10
2. 浏览器版本:Chromium53.0.2785.104

**Comment by kenyeson** [comment]
同上

1.操作系统 :Windows 7
浏览器版本:Chromium55.0.2883.87

**Comment by MZZZZZ** [comment]
B站改验证码了，等插件更新吧

**Comment by jjj201200** [comment]
会以0.9.5发布，等待b站更新完api
