### ISSUE TITLE
观看直播开启辅助领瓜子吃cpu的问题

### ISSUE THREAD

**Issue by potenzh** [zacyu/bilibili-helper#453]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): win10专业版 1709 16299.309
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Google Chrome  64.0.3282.140（正式版本） （64 位）
3. 扩展版本:v0.9.4

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

观看直播时若开启辅助领瓜子功能chrome的cpu占用率能达到20~30%(cpu型号为i7-7700hq 只开启直播一个页面)使用F12开发者工具network查看1秒内会有10几个requests时  cou的占用率也达到50~60% 

若关闭辅助领瓜子功能 占用率10%左右不超过15% 使用F12开发者工具查看 达到150左右requests后 10秒左右增加一个requests cpu的占用率一般不超过25%

狂刷的requests 有两类
1：
Request URL:http://api.live.bilibili.com/freeSilver/getCaptcha?ts=1521030883450
Request Method:GET
Status Code:200 OK
Remote Address:58.222.35.205:80
Referrer Policy:no-referrer-when-downgrade

大小334B

2：
Request URL:http://api.live.bilibili.com/FreeSilver/getCurrentTask
Request Method:GET
Status Code:200 OK
Remote Address:58.222.35.205:80
Referrer Policy:no-referrer-when-downgrade

大小1.3KB

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by xmcp** [comment]
#450

**Comment by jjj201200** [comment]
@xmcp 首先谢谢xmcp
然后，我再说一下吧，这个问题已经有好多天了，目前我们等待api更新，要是这周5下班前还是没有动静我就决定推到商店了，不能再等了，还请留意我和咕咕微博
