### ISSUE TITLE
充電被擠出去了，然後排版就亂了。

### ISSUE THREAD

**Issue by i9602097** [zacyu/bilibili-helper#454]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows 10 Ver.1709 Pro Workstation (64 位元)
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Chrome 64 (正式版本) (64 位元)
3. 扩展版本:0.9.4

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
如圖
![screenshot-www bilibili com-2018 03 17-06-15-20](https://user-images.githubusercontent.com/18757629/37547207-2fb73412-29ab-11e8-8877-9ed26a8d5091.png)
補個沒開助手的正常排版
![screenshot-www bilibili com-2018 03 17-06-18-25](https://user-images.githubusercontent.com/18757629/37547230-4ea0f1a6-29ab-11e8-9f19-339a3529ede4.png)

**Comment by jjj201200** [comment]
谢谢反馈~

**Comment by i9602097** [comment]
呃！這改得有點簡單粗暴吧！
連原本沒問題的沒有充電投稿
![screenshot-www bilibili com-2018 03 18-00-44-36](https://user-images.githubusercontent.com/18757629/37557881-3aa35de2-2a46-11e8-88f5-4df3a26ca1de.png)
現在也變成空蕩蕩一片
![screenshot-www bilibili com-2018 03 18-00-45-18](https://user-images.githubusercontent.com/18757629/37557890-60a7f62e-2a46-11e8-9bf8-031aba5fd3a7.png)
下載也要按多一次不能一掃即下了

本人魔改了一下CSS強行把充電放回去
又不需隱藏其他功能
![screenshot-www bilibili com-2018 03 18-00-46-06](https://user-images.githubusercontent.com/18757629/37557935-f772f540-2a46-11e8-99fe-6a095961ea48.png)
文字部份改為快顯形式
![screenshot-www bilibili com-2018 03 18-00-46-54](https://user-images.githubusercontent.com/18757629/37557948-19c07fdc-2a47-11e8-959a-5aa4bb323a5f.png)
CSS如下：
```
.video-toolbar-module .elec-btn {
    width: 60px;
}
.video-toolbar-module .elec-btn > span {
    visibility: hidden;
    line-height: initial;
    background-color: black;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px;
    position: absolute;
    z-index: 1;
    bottom: 100%;
    margin-left: -55px;
    opacity: 0;
    transition: opacity 1s;
}
.video-toolbar-module .elec-btn:hover > span {
    visibility: visible;
    opacity: 1;
}
```
不過為了避免B站之後又增加什麼新功能
還是把助手選單放在少改動的地方為佳
好像播放器右上角放回報播放問題和幫助那裏
基本上不用擔心放那的按鈕會擠出外
不用像現在要隨B站改版而改版

**Comment by jjj201200** [comment]
![image](https://user-images.githubusercontent.com/3397549/37564810-6b47f934-2ad8-11e8-8d69-440b57604090.png)
好像没毛病呀，简单点就好了，不需要特地那么改，毕竟你没发现这两个二维码功能几乎是重复的吗
至于将按钮挪到改动少的地方确实挺好的，不过右上角感觉并不是工具按钮应该出现的位置呢，你说呢？

**Comment by i9602097** [comment]
我的理解是開發助手的目的並沒有移除手機下視頻二維碼
那手機下視頻二維碼就不應被移除
舉例說移除廣告是開發目的之一
那助手把頁面中的廣告去除掉正常不過
但是助手移除手機下視頻二維碼不是因為開發目的如此
只是因為助手新增選單需要佔用此按鈕的空間
那就應該需可能做到兼容而不是隨意把原有功能去掉
無論是該功能是如何多餘它也是B站功能之一
除了開發目的之外的操作應該以保留B站原有功能為主
好像我的建議也沒把充電按鈕除去而是把排版微調讓充電按鈕能放回空間內

而我所說放在右上角只是舉例
放在少改動的地方才是建議
甚至直接在播放器下方新增div元素撐開頁面把所有選單項目都放進去也可以
而且也有腳本把設定介面放在這些地方
好像[嗶哩嗶哩（bilibili.com）播放器調整](https://greasyfork.org/scripts/21284)就是放在播放器右上角
![screenshot-www bilibili com-2018 03 18-19-37-52](https://user-images.githubusercontent.com/18757629/37565407-eee35daa-2ae3-11e8-9675-02d6cc4004c4.png)
[解除B站區域限制](https://greasyfork.org/scripts/25718)放在回到最頂提示按鈕區上(mini OFF下面那個按鈕)
![screenshot-www bilibili com-2018 03 18-19-38-16](https://user-images.githubusercontent.com/18757629/37565408-f33ca46a-2ae3-11e8-9b82-00835c0387dc.png)
當然如何放置才是最符合使用者習慣也是需要思考的部份
不過安放在經常修改的地方只會白白増加工作量
不見得是理想的選擇

**Comment by jjj201200** [comment]
我觉得你把问题想的太复杂了。咕咕没有提过什么原则性的话语，而我的话，大概也就是在添加功能的时候斟酌一下是否非常有必要，也要看时间怎么安排。如果兄台觉得我们做的不够好，欢迎提交合并请求。
只兄台提到的那些，我认为并不是很要紧，毕竟b站就算改，也不会很夸张（直播区那种除外），而助手喵在这个位置已经很久了，所以不考虑去改他，等到实在放不下了再考虑其他的吧。

**Comment by i9602097** [comment]
唔唔，你言重了
本人只是說一點個人看法給一點意見
沒要一定要跟本人的說法去做
作者你有自己的想法沒有問題
至於提交Pull request
本人只是略懂CSS
不可能找出助手中修改頁面的代碼
上面那段CSS我也是用Stylus加進頁面中而不是解包助手修改
要交Pull request還早了十萬八千年
所以只能在issue中說一下自己的意見

**Comment by zacyu** [comment]
其实我也认为直接移除一个功能按钮确实有一些太过粗暴, 不过鉴于功能与另一个按钮近乎重复所以我觉得也可以接受. @i9602097 你提出的那个修改建议的问题在于之后如果 B 站对那个部分再修改的话, 我们这边需要更改的部分也会很多. 你提出的对于位置的考虑一点还是有意义的 – 但是也如 @jjj201200 所说, 「助手喵在这个位置已经很久了」, 所以我也不倾向于移动这个按钮的位置. 我目前的态度和 @jjj201200 比较接近, 如果之后 B 站对这个位置改动过于频繁或者再增加/替换新的相对更重要的功能到时空间不够时, 我们可以再重新讨论助手喵位置的问题.

**Comment by zacyu** [comment]
这个 issue 本身的问题已经解决了, 先关了. 之后如果需要讨论助手喵位置的时候再开一个新的 issue 讨论吧.

**Comment by i9602097** [comment]
@zacyu 
了解，就先這樣吧
