### ISSUE TITLE
辅助领瓜子功能异常

### ISSUE THREAD

**Issue by xxkknn** [zacyu/bilibili-helper#456]
### 环境信息
1. 操作系统 (Windows 10):
2. 360极速浏览器，内核版本55.0.2883.87
3. 扩展版本:0.9.4

问题：开启辅助领瓜子后，直播间宝箱倒计时会在 页面加载完成后 大约3s后停止，之后无法领取瓜子且点击宝箱无响应。

**Comment by jjj201200** [comment]
0.9.5出了，请更新一下
