### ISSUE TITLE
[页面跳转]关于"我的关注"按钮跳转页面的建议

### ISSUE THREAD

**Issue by GitPopcorn** [zacyu/bilibili-helper#457]
##主问题区
目前哔哩哔哩助手“我的关注”按钮指向的页面是旧版的个人动态默认页面，即：
https://www.bilibili.com/account/dynamic
希望能在助手设置中，添加跳转至新版个人动态首页的选项，即：
https://t.bilibili.com/
主要是因为Bilibili老版本动态首页的“稍后再看”功能已经不太稳定，经常会失效无法点击；

##注释信息
无

**Comment by jjj201200** [comment]
emmmmm新版很棒诶，想问一下这个地址的入口在哪里？哪里可以手动点进这个页面？
我想不出意外我们会采纳你的建议的~谢谢~

**Comment by GitPopcorn** [comment]
现在点击右上角“动态”链接，默认进入的就是新版地址了：
![snipaste_2018-03-25_00-43-21](https://user-images.githubusercontent.com/31797624/37866483-3522bf7c-2fc6-11e8-821f-eff1f74c96a3.png)

在新地址右上角点击“返回旧版”即可返回旧版本动态首页：
![snipaste_2018-03-25_00-45-19](https://user-images.githubusercontent.com/31797624/37866518-94d3315e-2fc6-11e8-8bdc-3c76a4cc937c.png)

非常感谢您的及时回复和技术支持，不过还是建议保留旧版本动态首页的可选选项，因为可能部分哔哩哔哩助手的忠实用户还不太习惯新版动态首页；

**Comment by jjj201200** [comment]
emmmmm，那就改成可配置的好了，在设置页面设置默认跳转的是新版还是旧版，开关默认关闭，打开即会默认跳转到新版页面

**Comment by GitPopcorn** [comment]
我觉得海星.jpg
那就多谢啦:D
