### ISSUE TITLE
海外用户H5播放器下载的卡顿问题

### ISSUE THREAD

**Issue by uyx6345** [zacyu/bilibili-helper#46]
尽管不使用代理H5播放器可以正常播放受版权限制的视频。但使用过Unblock Youku之后原版Flash播放器也可以流畅播放，但H5播放器还是依然存在卡顿。希望知道怎样针对H5播放器进行代理。

**Comment by fqj1994** [comment]
unblock youku不会代理视频的，即使对于flash播放器。只会代理那几个会检查IP的页面。
你卡顿的时候是否是无论怎么点都无用，而不是等网络加载好了就能继续？
如果是，在命令行手动起chrome，你卡顿的时候终端里面是否有 `MediaEvent: PIPELINE_ERROR pipeline: read error ` 类似的输出。
如果是，请降级到chrome 44再试试。

**Comment by zacyu** [comment]
已修复.

**Comment by uyx6345** [comment]
谢谢
