### ISSUE TITLE
辅助领瓜子无法正常运行

### ISSUE THREAD

**Issue by jioujiou2018** [zacyu/bilibili-helper#460]
### 环境信息
操作系统 Windows 7
谷歌chrome 63.0.3239.108
扩展版本:0.9.4

开启辅助领瓜子后不管进入哪个直播间瓜子宝箱会在倒计时4秒后卡住不动不再计时，并且过了相应宝箱时间瓜子不能被正常领取。刷新以及重装助手均系无效。关闭该功能则可正常倒计时。
截图
![qq 20180330225554](https://user-images.githubusercontent.com/37934956/38142250-307cd8ac-346e-11e8-8129-09a31340f1aa.png)

**Comment by xmcp** [comment]
#456
