### ISSUE TITLE
使用扩展后，直播间弹幕设置在刷新网页后失效

### ISSUE THREAD

**Issue by epsgerry02** [zacyu/bilibili-helper#461]
作者好=-=
透明度、字体缩放、同屏密度等弹幕设置会在刷新网页后失效，是这样的吗？请问有解决办法么

**Comment by jjj201200** [comment]
你好，你可以在关闭助手的状态下确认是否由助手导致的问题
另外，助手并没有在提供已公布的功能外做多余的工作或修改，你都能在设置页面进行修改或者查看到

**Comment by epsgerry02** [comment]
了解，谢谢
关闭助手后偶尔也会还原成默认弹幕设置，但开启助手后每次刷新页面都会还原= =
之前用http://live.bilibili.com域名是好像就没这种问题，最近换https之后就这样了
我猜是和其他扩展或者油猴脚本冲突的关系吧

**Comment by jjj201200** [comment]
那说明是b站方面的处理有问题，你可以去和他们客服反馈一下问题，或者去他们的论坛反馈
