### ISSUE TITLE
是否考虑推出命令行工具？

### ISSUE THREAD

**Issue by Kimi-Arthur** [zacyu/bilibili-helper#462]
很多助手的功能并不能在别的工具内得到，比如领瓜子，比如下载视频（如官方电视剧，https://www.bilibili.com/bangumi/play/ss23769/），比如下载弹幕。

**Comment by jjj201200** [comment]
你好，请问是否想表达对批量获取（视频下载链接等）数据的需求？
如果是的话，我本人可能暂时不会有这个考虑，原因如下：
我们一定程度上提供单个视频的下载功能，之后会加上分段合并。但应该不会考虑多集的批量下载。只提供一定程度上的便利，而非绝对的便利（想加什么就加什么）。
还需要考虑官方可能会有的态度，毕竟官方在移动设备上是有提供下载功能的，而为何pc端没有设置直接的下载方式，肯定是有原因的。
不知@zacyu  觉得如何

**Comment by Kimi-Arthur** [comment]
下载的话以前用youtube-dl的，但是有一些类型的链接不支持，而这个插件支持，只是不能在命令行下使用。

其实不需要支持批量，能下一个就行了。其他的让使用者来自动化就行了。

其实在这个项目里提就是感觉这些功能已经实现的挺好的，而且还经常更新。能直接把同样的功能提供到命令行就完美了。

**Comment by jjj201200** [comment]
@Kimi-Arthur 项目中的接口和实现方法可以拿去参考咯，欢迎实现~

**Comment by zacyu** [comment]
其实有一个关键的问题是这个扩展依赖于浏览器中 - 如用户的 session (cookie), HTML5 播放器获取视频地址的 request, etc. 如果单独实现的话虽然也可以做 (e.g. via a headless browser) 但是感觉并不现实. 因此我认为命令行工具对于这个项目是 out-of-scope 的. 如果需要的话可以考虑去 contribute 到 youtube-dl 那边.

**Comment by jjj201200** [comment]
@Kimi-Arthur 你可以去找找那些挂机用客户端，有可以挂机领经验，签到，领瓜子的，然后可以参考助手的方式获取视频地址，实现是肯定可以的。但是和本项目的关系就像我和咕咕说的那样，并不适合加进去。
