### ISSUE TITLE
直播间宝箱在自动领取完成后消失

### ISSUE THREAD

**Issue by Tansc161** [zacyu/bilibili-helper#463]
## 问题反馈
插件自动领取完成所有直播间宝箱后宝箱消失，建议保留宝箱，宝箱不见了感觉那边空空的，，
![1-capture](https://user-images.githubusercontent.com/37703689/38676404-7f0b4eee-3e8d-11e8-8be8-952d5562c6d6.gif)

### 环境信息
1. 操作系统: Win10 Home (Build16299.309)
2. 浏览器版本: 64.0.3282.140 (正式版本) （64 位） (cohort: 64_140_win)
3. 扩展版本: v0.9.5

### 重现步骤/尝试的解决方案
待插件自动领取所有宝箱后，宝箱会被插件去除。

**Comment by Tansc161** [comment]
@xmcp 不是，把插件关掉后是会显示宝箱的（只不过点击宝箱后下面会有“今天已经木有宝箱惹 ●ω●”这段文字），可以测试看看。

**Comment by jjj201200** [comment]
emmmmm
可以考虑，之前b站是会把宝箱隐藏掉的，所以我也这么做的，现在不会隐藏的话，我也改成一样的好了
