### ISSUE TITLE
下載助手不見了

### ISSUE THREAD

**Issue by richarddwang** [zacyu/bilibili-helper#464]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [ y] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [y ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [y ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ y] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Linux
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Firefox 最新 Chrome 最新
3. 扩展版本: 都剛下載的

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
隨便load 一個視頻
本來在收藏旁的吃零食貓助手不見了
想要下載視頻和彈幕啊
(推測是b站的更新？)

**Comment by thevenomsnake** [comment]
我今天也发现了，估计b站做了更新。。
