### ISSUE TITLE
LICENSE冲突

### ISSUE THREAD

**Issue by std4453** [zacyu/bilibili-helper#467]
在助手的相关信息页面中写道：
> 本项目中使用的本地 CRC32 反查脚本修改自 xmcp 以 GPL 许可协议 发布的开源项目 pakku.js 中的部分代码。

其中的GPL指向的链接是[GPL 3.0](https://www.gnu.org/licenses/gpl-3.0.en.html)，然而GPL 3.0要求所有使用了 使用GPL 3.0的软件 的软件都必须使用GPL 3.0协议。
而助手似乎是MIT，不与GPL 3.0兼容。

**Comment by xmcp** [comment]
我觉得按照 GPL 的 Section 7，我可以加一个 Exception 来允许用 MIT 协议发布 CRC32 Cracker。我试试 [在 OpenSSL Exception](https://stackoverflow.com/questions/1156556/how-do-i-write-an-exception-under-section-7-of-the-gplv3) 的基础上改一下。

**Comment by jjj201200** [comment]
![image](https://user-images.githubusercontent.com/3397549/39052281-0f847bde-44de-11e8-9900-d1fbbc95a2f4.png)
谢谢
