### ISSUE TITLE
小问题和建议（签到、礼物、窗体、宝箱）

### ISSUE THREAD

**Issue by Tansc161** [zacyu/bilibili-helper#468]
## 问题反馈
由于都是一些小问题和建议所以就整合一起发了
1.首次打开直播间签到成功后，签到栏的签到按钮还存在，并且点击后会显示 `-500` 错误。（刷新页面解决）
![image](https://user-images.githubusercontent.com/37703689/39115905-9d070d1c-4715-11e8-93e3-3e897fd3af3c.png)

2.在礼物包裹增强开启的状态下，当鼠标悬停在礼物包裹窗口， `清空本类` 按钮显现得不自然：会让窗口下增加一个滑动栏，如果礼物较多的话还会导致礼物位置向右偏移（用户体验问题）。
![4-capture](https://user-images.githubusercontent.com/37703689/39095989-ec1aeb66-467b-11e8-9777-9a64555a9f45.gif)

3.建议当鼠标悬停在哔哩哔哩助手按钮时打开窗口。（与其他哔哩哔哩原生选项形式一致）
![2-capture](https://user-images.githubusercontent.com/37703689/39095954-6d4facae-467b-11e8-8406-c22cd91cbe59.gif)
![3-capture](https://user-images.githubusercontent.com/37703689/39095955-6ef412b6-467b-11e8-832a-d17ffbc9bd89.gif)

4.领完宝箱有时会出现 `今天已经木有宝箱惹 (●'◡'●)ﾉ♥` 的提示窗口，过后窗口不能关闭，情形与后面一致；领完宝箱状态下，刚进入直播间页面时宝箱窗口可开启（助手还没启动），过后窗口就不能操作了，点击宝箱还会出现undefined轮的字样。（建议保持宝箱可点）
领完宝箱状态下，进入直播间：
![1-capture](https://user-images.githubusercontent.com/37703689/39095948-4b93b6fa-467b-11e8-8128-42260684b152.gif)
单个领完宝箱状态下的：
![capture](https://user-images.githubusercontent.com/37703689/39095963-95957b3a-467b-11e8-9a2a-88a20fc277d1.PNG)

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): W10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 65.0.3325.181
3. 扩展版本: 0.9.6

### 重现步骤/尝试的解决方案
啊啊都写在上面了。。。

**Comment by jjj201200** [comment]
谢谢~

**Comment by jjj201200** [comment]
第三条是刻意这么设计的

**Comment by jjj201200** [comment]
本issu而相关问题会在下个版本 被修复。
1. 现在会正确显示签到信息；
2. 增大了道具包括框的宽度；
3. 不存在问题，不予处理，我们就是这么设计的；
4. 由于助手需要知道宝箱是否领完，如果没有领完的话就开始领取，所以我仍然在领完后将宝箱设计为不可点击，但是现在不会再显示助手载入之前打开的窗口。

**Comment by jjj201200** [comment]
0.9.7已经发布，如仍旧有什么问题请重新开一个issue
