### ISSUE TITLE
可不可以加入bilibili全局关闭弹幕的功能呢QaQ

### ISSUE THREAD

**Issue by Justicebox** [zacyu/bilibili-helper#471]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): N/A
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): N/A
3. 扩展版本: master

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
N/A
请具体描述, 谢谢 :)

**Comment by zacyu** [comment]
我印象里现在的播放器是设置 (包括弹幕关闭状态) 是保存在本地的? 全局关闭弹幕具体指的是?

**Comment by xmcp** [comment]
全局弹幕状态不在设置里。需要去click关闭弹幕那个按钮。

**Comment by jjj201200** [comment]
我理解的可能是默认关闭视频弹幕显示的功能
现在是一打开视频就会飞弹幕出来，该用户希望默认就是关闭的，如果是的话，请回复一下谢谢
@Justicebox

**Comment by NandaParbat** [comment]
是的，B站视频默认开启弹幕，而且只能看视频的手动关闭，不能设置为默认关闭弹幕，所以希望助手能更新这个功能，默认关闭B站弹幕

**Comment by jjj201200** [comment]
1.1.4版本中添加了该功能，请及时更新
