### ISSUE TITLE
今天刚刚出现自动领瓜子一直弹出访问被拒绝

### ISSUE THREAD

**Issue by mylongdays** [zacyu/bilibili-helper#472]
如题，两种浏览器都试用过了，全都有这种问题，应该不是浏览器自身的问题，最大可能性是b站又开始新一轮的封锁了。
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
3. 扩展版本:

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by mylongdays** [comment]
今天突然又没这毛病了，不知道是b站自己鬼畜回去了还是怎么了。

**Comment by jjj201200** [comment]
请问你有使用别的脚本软件吗

**Comment by mylongdays** [comment]
为了试验是不是只有助手的情况下也有问题我专门安装了一个只用助手的猎豹浏览器，发现和开了别的脚本的chrome一样，都不能自动宽屏，手头没有好用的第二台电脑所以就没验证卸掉猴脚本时chrome的情况了，因为猴的脚本太多重下太麻烦。

**Comment by jjj201200** [comment]
自动宽屏？？？？你的重点不应该是有没有被封吗？和自动宽屏有关系吗，我们就一个问题进行讨论可以吗？如果有其他问题请再开一个issue进行反馈~

**Comment by kenyeson** [comment]
应该是别的插件造成的，昨天试着把别的插件全关了今天没有被人封号

**Comment by jjj201200** [comment]
@kenyeson 据我了解的情况是一些使用自动参与节奏风暴和小电视抽奖的脚本会造成被封禁的结果

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新

**Comment by mylongdays** [comment]
谢谢提醒，已经自动更新了。
