### ISSUE TITLE
自动领瓜子提升访问被拒绝

### ISSUE THREAD

**Issue by melongteng** [zacyu/bilibili-helper#473]
左下角从助手接管倒计时开始就一直提升访问被拒绝。
倒计时结束后会不停刷新验证码（答案正确但是不能领取，不停刷新）
更换好几个直播间都是这样。

Window10 1803(17134.1)
360极速9.5.0.128(Chrome内核:63.0.3239.132)
助手0.9.6
![360 -1994937](https://user-images.githubusercontent.com/28689955/39451215-7721e428-4d00-11e8-8b8a-346ad67f5fdf.jpg)

**Comment by kenyeson** [comment]
4月29日也出现过同样情况，但30日莫名其妙好了，今天5月1日又出现了

Window10
360极速9.0.1.162（Chrome内核：55.0.2883.87）
助手0.9.6

**Comment by jjj201200** [comment]
@kenyeson 请问你有使用其他脚本吗

**Comment by mylongdays** [comment]
我之前的问题和这个一样，但是过了一天后重启电脑发现就没这毛病了，至今没重犯。

**Comment by jjj201200** [comment]
@MrPlugy @mylongdays @melongteng 问题的重点是为什么会被封，既然是在此进行反馈的问题了，那么就有必要确定是不是助手导致的问题，对么。如果在没有使用任何其他相关脚本的情况下被封了，那我有责任再进一步确认，甚至暂停这些功能。

**Comment by jjj201200** [comment]
重复问题 #472
