### ISSUE TITLE
检查"我的关注"更新的通知中番剧更新的up主为undefined

### ISSUE THREAD

**Issue by rosekc** [zacyu/bilibili-helper#475]
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):win10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): 66.0.3359.139（正式版本） （64 位）
3. 扩展版本:0.9.6

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
检查"我的关注"更新的通知中番剧更新的up主为undefined。

**Comment by mylongdays** [comment]
好像官方番剧的UP都是显示undefined吧，之前几个版本就这样了

**Comment by jjj201200** [comment]
@rosekc @mylongdays 谢谢反馈并提供有用讯息，我们应该将他改的更好

**Comment by jjj201200** [comment]
0.9.7已经发布
