### ISSUE TITLE
获取字幕下载失败

### ISSUE THREAD

**Issue by evollu** [zacyu/bilibili-helper#479]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): macOS
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 66.0.3359.139
3. 扩展版本: 0.9.6

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
访问
https://www.bilibili.com/bangumi/play/ep101761
<img width="319" alt="screen shot 2018-05-13 at 10 32 59 pm" src="https://user-images.githubusercontent.com/9213224/39975645-d995d90a-56fd-11e8-8ca6-73769ff53536.png">

**Comment by msg7086** [comment]
Hello,
This was already fixed in #478.

**Comment by jjj201200** [comment]
@Phillaw Yes, i'm preparing for this feature. This feature will be added in version 1.0.9 (beta). But i not know when we world publish the official version. May be in these two weeks.
