### ISSUE TITLE
.ABP-Unit.ABP-FullScreen中的z-index可以改到10011以上吗？

### ISSUE THREAD

**Issue by huhuime** [zacyu/bilibili-helper#48]
z-index:9999未知原因不够，"返回顶部"按钮在"网页全屏"时依然显示出来
![image](https://cloud.githubusercontent.com/assets/6631239/9697636/dee3b400-53c6-11e5-8e34-9e18c34598c9.png)
![image](https://cloud.githubusercontent.com/assets/6631239/9697637/f5fb8816-53c6-11e5-9bc5-a54cb90ea631.png)

**Comment by zacyu** [comment]
Fixed in 5b96471e799e9fe4a49cb3a104db3a8ec7e6b354
