### ISSUE TITLE
直播间瓜子领取问题与投喂留言小问题

### ISSUE THREAD

**Issue by Tansc161** [zacyu/bilibili-helper#481]
### 环境信息
1. 操作系统: WIndows 10 v1803
2. 浏览器版本: 65.0.3325.181
3. 扩展版本: 0.9.6

### 问题描述
1. 每日第一次进入直播间时会看到一连串的“验证码错误”等提示，在“领取时间未到，请销后再试”的提示出现后才会停止。（可能是误判引起）
2. 助手详情页->投喂记录 的留言栏边还有大半空间，留言却截了一半。
![image](https://user-images.githubusercontent.com/37703689/40268769-7a5a3cf8-5ba6-11e8-85c5-72c8bca38d90.png)
把宽度增加就好了。（650px左右）
![image](https://user-images.githubusercontent.com/37703689/40268832-8d9d0fd8-5ba7-11e8-913d-a575f9b5fabb.png)

### 重现步骤/尝试的解决方案
Mentioned above.

**Comment by jjj201200** [comment]
1. 现在b站的领瓜子，我感觉会累计时间，所以有的时候会在刚开直播间的时候就领取成功，你可能会问这怎么可能呢，但事实就是这样。所以每开一个直播间都会先重新获取一下，看看能不能先领取了。直到直到计时器还没有计时完才会停下来。另外这也无伤大雅，毕竟并不想在能够领取的情况下再等几分钟吧。
2. 加大宽度左边的不就没地方了吧，用户留言的长度都是随机的。另外我有设置text属性，那把鼠标光标移到过长的文字上面等1秒就会显示完整的内容。
