### ISSUE TITLE
HTML5播放器全屏时右边“弹幕列表”那个不会自动隐藏

### ISSUE THREAD

**Issue by LoogCP** [zacyu/bilibili-helper#482]
具体描述：在B站看视频的时候，使用HTML5播放器，全屏的时候，右侧“弹幕列表”、“推荐视频”、“屏蔽设定”那一栏不会自动隐藏，使用Flash播放器没问题，请问该怎么解决。
OS：ArchLinux 64bit
Browser：Chrome Dev版本 68.0.3432.3（正式版本）dev （64 位）
UA：Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3432.3 Safari/537.36

**Comment by LoogCP** [comment]
sry,这个好像是B站本身的布局，不是助手的，

**Comment by jjj201200** [comment]
那我就关掉这个issue了哈~
