### ISSUE TITLE
助手不显示了。。。。

### ISSUE THREAD

**Issue by HuxiaoRoar** [zacyu/bilibili-helper#483]
应该不是我操作的问题吧，我放截图吧，win10，chrome 
试了几个视频都这样

![Uploading QQ截图20180524172909.png…]()

然后我的设置....
![Uploading QQ截图20180524172844.png…]()

**Comment by jjj201200** [comment]
你的图没有传上来
然后，你应该把自己所使用的助手版本发一下，我们已经在商店发布了0.9.8版本，如果还没有更新请去更新一下吧，我们已经修复了很多问题。

**Comment by Horace486** [comment]
我的v0.9.9也不显示助手QAQ

**Comment by Horace486** [comment]
Win10 浏览器是360极速 其实后来第二天打开就又显示了……打扰了不好意思！谢谢！

发送自 Windows 10 版邮件应用

发件人: jjj201200
发送时间: 2018年6月4日 21:25
收件人: zacyu/bilibili-helper
抄送: Horace486; Mention
主题: Re: [zacyu/bilibili-helper] 助手不显示了。。。。 (#483)

@Horace486 请把你的基本信息说一下，比如系统版本，浏览器种类和内核版本等。光说不能用是无助于问题的解决的

**Comment by jjj201200** [comment]
有问题的话再重新开一个issue吧，谢谢您的反馈
