### ISSUE TITLE
【2018605】v0.9.9 【BUG反馈】

### ISSUE THREAD

**Issue by ZinHian** [zacyu/bilibili-helper#485]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): **Windows10**
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): **Chrome v65.0.3325.181（正式版本） （64 位）**
3. 扩展版本: **0.9.9**

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

问题反馈 :
①解析视频地址失败，但在选项页中设置 " **视频下载地址格式** " 为 " **MP4优先** "后能直接获取下载地址或是能通过改变视频清晰度后获得下载地址，但**只能获取480P**的下载地址，点其他清晰度时，页面中的**插件logo动画**出现卡顿现象；
②弹幕文件无论是xml格式或ass格式，在下载时弹出的保存窗口均不含有后缀名 ( 另在多台win7机上也发现这问题 )，情况仍然跟之前在群里反馈的一样。

反馈完毕，大佬们辛苦了 ! (๑•̀ㅂ•́)و✧

**图1：切换分辨率前的情况**
![_20180605002556](https://user-images.githubusercontent.com/39918666/40929574-c64c6c18-6857-11e8-87ac-841bba116579.png)
----------分割线----------
**图2：切换分辨率后的情况**
![_20180605002614](https://user-images.githubusercontent.com/39918666/40929596-d451a44a-6857-11e8-9c13-6f5e0b913431.png)

**Comment by wesleywing** [comment]
對，我也遇上上述的情怳，需要改變清晰度才可以下載，但不能選擇高清晰度的下載

**Comment by ZinHian** [comment]
我现在将插件的版本退回0.9.8版本就能解析1080P了，但有时会解析失败，估计是B站前端又搞鬼搞怪了，耐心等待开发者那边看看

**Comment by Tansc161** [comment]
问题同上~
![image](https://user-images.githubusercontent.com/37703689/41223591-cb401950-6d9c-11e8-9d3d-a5d788fcf068.png)

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新

**Comment by jjj201200** [comment]
新版播放页面中，功能仍然不稳定，目前我个人建议的做法是，打开心播放页面后，切换清晰度然后来回切换视频，有时能够获取到，原理未知
