### ISSUE TITLE
v0.9.9的bug反馈

### ISSUE THREAD

**Issue by 6Bpencle** [zacyu/bilibili-helper#486]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Chrome v65.0.3325.181（正式版本） （64 位）
3. 扩展版本:0.9.9

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
1.B站把辣条道具放入了道具包裹，当开启礼物包裹增强时无法赠送辣条

开启前
![1](https://user-images.githubusercontent.com/31346958/41153603-c59162f2-6b49-11e8-972b-6b527810621d.PNG)
开启后
![2](https://user-images.githubusercontent.com/31346958/41153609-cbe83a68-6b49-11e8-9afe-a829d8c25055.PNG)

2.无法下载视频
当点击分段x下载时无法下载视频，显示无法访问此网站
![3](https://user-images.githubusercontent.com/31346958/41192130-0e676f8e-6c2c-11e8-9951-45769453b67c.PNG)

**Comment by ZinHian** [comment]
我现在将插件的版本退回0.9.8版本就能解析1080P了，但有时会解析失败，估计是B站前端又搞鬼搞怪了，耐心等待开发者那边看看

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新
