### ISSUE TITLE
B 站开始测试新版视频播放页

### ISSUE THREAD

**Issue by AnnAngela** [zacyu/bilibili-helper#492]
![qq 20180629171533](https://user-images.githubusercontent.com/9762652/42084373-0d13a8ca-7bc0-11e8-9bb9-210252aef34b.png)
观察源码得知开启方式为在 cookie 中设置 `stardustvideo` 值为 `1`：
![image](https://user-images.githubusercontent.com/9762652/42084425-2beec630-7bc0-11e8-9de6-9d53af6f290b.png)
希望能够适配

**Comment by xmcp** [comment]
@AnnAngela 
新版播放器的页面是拿vue写的，vue在更新DOM的时候发现多了一个元素自然就报错了。

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新
