### ISSUE TITLE
希望能添加默认关闭弹幕功能

### ISSUE THREAD

**Issue by NandaParbat** [zacyu/bilibili-helper#495]
B站弹幕开关默认是打开的，而且手动关闭只对当前视频有效，不能设置为全局默认关闭，所以希望助手能添加一个全局默认关闭弹幕功能，非常感谢

**Comment by xmcp** [comment]
duplicate of #471 

https://github.com/xmcp/pakku.js/blob/32723df55fd3e3ebdfb55c198547cf723903049f/pakkujs/injected/do_inject.js#L73-L83

**Comment by jjj201200** [comment]
1.1.3版本中添加该功能了
