### ISSUE TITLE
suggestion: 希望添加几个跳转功能

### ISSUE THREAD

**Issue by JockeyWang** [zacyu/bilibili-helper#501]
在输入av号的地方，除了av以外，对开头的字符增加几个跳转逻辑：
1、输入"ss"开头的话，跳转到: "https://www.bilibili.com/bangumi/play/ss" + sid
2、输入"s"开头的话，跳转到: "https://bangumi.bilibili.com/anime/" + sid
3、输入"md"，跳转到: "https://www.bilibili.com/bangumi/media/md" + mdid
4、输入"u"，跳转到: "https://space.bilibili.com/" + uid

**Comment by jjj201200** [comment]
这个建议非常好！但是种类有点多啊，怎么足够方便的做切换呢。如果有模式可以用于自动识别就好了

**Comment by JockeyWang** [comment]
@jjj201200 通过前置字符判断就行了，就像你输入avXXXXX就跳转到视频一样

**Comment by xmcp** [comment]
正则表达式就可以

我之前做了一个 https://github.com/xmcp/GOTO 就是类似的功能

**Comment by JockeyWang** [comment]
@jjj201200 再加两组：
输入"cv"，跳转到: "https://www.bilibili.com/read/cv" + cvid
输入"au"，跳转到: "https://www.bilibili.com/audio/au" + auid

**Comment by qstdnx** [comment]
新版输av的地方直接没了还行

**Comment by qstdnx** [comment]
> 这个建议非常好！但是种类有点多啊，怎么足够方便的做切换呢。如果有模式可以用于自动识别就好了

新版输av的地方直接没了(ಥ_ಥ)

**Comment by jjj201200** [comment]
1.1.2版本已经上架更新了此功能

**Comment by qstdnx** [comment]
> 1.1.2版本已经上架更新了此功能

我这没看到，而且动态更新下面是一片空白，需要在哪里设置打开吗？
http://wx4.sinaimg.cn/mw690/0060lm7Tly1fxffnmmiqbj30ds0990sv.jpg

**Comment by jjj201200** [comment]
@qstdnx 卸载重新安装

**Comment by qstdnx** [comment]
> @qstdnx 卸载重新安装

ok，出现了

**Comment by jjj201200** [comment]
默认会保留，如果觉得不好，可以优化一下交付，获取鼠标焦点时已有内容会被全选

**Comment by jjj201200** [comment]
@JockeyWang 能不能给下具体的例子？s的是什么样的视频？ep有是怎样的？

**Comment by JockeyWang** [comment]
好吧。。我解释一下吧：
B站的番剧专题，有个sid（season_id）和mid（media_id），目前来看是一对一关系，它们都可以唯一地确定一个番剧（当然也可能是电视剧之类的）
其中：
s那个是旧版专题，现在访问的话会强制重定向到media专题。（但还是有用处的）
md则是现在使用的media专题，根据mid来识别专题号。
ss那个，根据sid识别，点进去以后会直接进入播放页面，根据用户的观看进度而决定具体进入哪一个单集。
ep则是番剧内一个单集的id，与cid一对一关联。

说实话……这些看起来有些乱。。我给几个链接吧，以紫罗兰为例：
s（旧版专题）： https://bangumi.bilibili.com/anime/21542
md（新版专题）：https://www.bilibili.com/bangumi/media/md8892
ss（专题播放页面）：https://www.bilibili.com/bangumi/play/ss21542
ep（单集播放页面）：https://www.bilibili.com/bangumi/play/ep173286

**Comment by jjj201200** [comment]
@JockeyWang 我次奥，万分感谢

**Comment by jjj201200** [comment]
1.1.6版本已经上架，请及时更新，之后的问题请重新开一个issue
