### ISSUE TITLE
无法打开视频

### ISSUE THREAD

**Issue by chenghuang-mdsol** [zacyu/bilibili-helper#502]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):chrome 68.0.3440.106
3. 扩展版本:v0.9.9

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
打开任意视频。打开控制台(F12)

![image](https://user-images.githubusercontent.com/13528118/44957889-cacbf080-aea5-11e8-8add-e6bef2ad0f87.png)

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by jjj201200** [comment]
你好，助手当前不兼容b站的新版播放页面，请关闭“自动调整播放器位置”功能，就可以解决这个问题

**Comment by iVoldemort** [comment]
我也同样的问题，但是关闭 “自动调整播放器位置” 功能之后，问题没有被解决。
这个播放器消失的问题只在单 P 的视频里出现，多 P 的视频，不会播放器消失，或者点一下右边分 P 列表的某一 P，播放器就会出现了。
macOS 10.13.6，Chrome 68&69
![image](https://user-images.githubusercontent.com/7200516/45147282-2cb68e00-b1f7-11e8-8759-8833d22f0595.png)

**Comment by jjj201200** [comment]
@iVoldemort 你好，你的问题和楼主不是同一个，请重新开一个issue来跟踪问题。另外请问是否还同时开启其他插件？如果有，请先关闭后看看还有此类问题吗

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新
