### ISSUE TITLE
助手不支持新版的 B 站

### ISSUE THREAD

**Issue by season19840122** [zacyu/bilibili-helper#503]
## 问题反馈
助手不支持新版的 B 站，新版 B 站不会出现助手

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 69
3. 扩展版本: 0.9.9

**Comment by jjj201200** [comment]
#492
