### ISSUE TITLE
新版界面下单 P 视频的播放器消失

### ISSUE THREAD

**Issue by iVoldemort** [zacyu/bilibili-helper#504]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): macOS High Sierra 10.13.6
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Chrome 69 stable
3. 扩展版本: 0.9.9

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
打开一个B 站网址→网页载入→载入完毕的瞬间、播放器正常出现但是马上消失，网页直接没了播放器。
关闭 “自动调整播放器位置” 功能之后，问题没有被解决。
这个播放器消失的问题只在单 P 的视频里出现。多 P 的视频，不会播放器消失，或者如果消失的话，点一下右边分 P 列表的某一 P，播放器就会出现了。
![image](https://user-images.githubusercontent.com/7200516/45218279-a161f900-b2d9-11e8-8cd8-7799827c1173.png)
之前我也在开发者工具里见到过里面显示有 error 是带有本扩展的 ID，就像 #502 的截图里这部分一样的
![image](https://user-images.githubusercontent.com/7200516/45218646-f4887b80-b2da-11e8-9c3c-0df01edba0c4.png)
下图这是我刚截图的，关闭了 uBlock，没有上图的带本扩展 ID 的 error，但是播放器也没有。
![image](https://user-images.githubusercontent.com/7200516/45218747-4204e880-b2db-11e8-8f3a-eeff8dd0d181.png)

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新
