### ISSUE TITLE
弹幕查询相关问题

### ISSUE THREAD

**Issue by sxinxins** [zacyu/bilibili-helper#505]
1. 操作系统 (Windows/macOS/Linux):win8.1
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):chrome64.0.3282.140和Chromium 67.0.3396.99
3. 扩展版本:v0.9.9

弹幕查询比实际弹幕少，有些弹幕查不到。
比如这个视频https://www.bilibili.com/video/av29695736 ，目前1p有五条弹幕，但是在弹幕查询里一条也查不到
![r foe5z en pwt4 n ca2](https://user-images.githubusercontent.com/30524883/45613410-cd7b3800-ba98-11e8-945b-7e1ef259fa1f.png)
下载下来的xml和ass记事本打开也看不到弹幕

请问是我自己的问题吗，怎么解决？

**Comment by jjj201200** [comment]
1.1.1版本已经在商店发布，请及时更新

**Comment by sxinxins** [comment]
谢  已更新  辛苦鸟~
