### ISSUE TITLE
无法领取瓜子，提示访问被拒绝

### ISSUE THREAD

**Issue by zzz8307** [zacyu/bilibili-helper#508]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows 10 1803
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Google Chrome 70.0.3538.67（正式版本）（64 位）
3. 扩展版本:0.9.9

### 重现步骤/尝试的解决方案
打开直播间插件加载完成后会一直提示访问被拒绝，时间到了手动点开领瓜子会自动输入验证问题答案，但是点击领取会无反应
https://imgur.com/TbQmaOB

**Comment by jjj201200** [comment]
你好，访问被拒绝的问题，原因是你进了小黑屋，请确认原因
