### ISSUE TITLE
关于火狐版下架问题

### ISSUE THREAD

**Issue by datou1996** [zacyu/bilibili-helper#509]
## 问题反馈
火狐版因下架而无法安装，或许可以考虑重新上架或者直接在Github提供下载吗

### 环境信息
Windows10 1809
Firefox Quantum 63.0 (64 位)
N/A

### 重现步骤/尝试的解决方案
如上

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by zacyu** [comment]
目前计划在下一次更新后同步上架 :-)
