### ISSUE TITLE
能不能支持通过稍后再看的播放页面

### ISSUE THREAD

**Issue by u2shana** [zacyu/bilibili-helper#510]
稍后再看点击出来的页面助手无效

**Comment by jjj201200** [comment]
请问您使用的助手是什么版本？我最近已经在测试群里发布了测试版本，其中已经完成了部分功能，包含支持新播放页面的视频弹幕查寻功能

**Comment by jjj201200** [comment]
很抱歉，我看了一下稍后再看页面，这个页面很有可能会被新版页面替代，所以暂时不对这个页面进行处理
