### ISSUE TITLE
新版的右下角推送通知似乎不显示up主和视频封面了，能否恢复显示？

### ISSUE THREAD

**Issue by LzNOHentai** [zacyu/bilibili-helper#520]
现在只有标题了，展示的信息感觉不太够，能否恢复旧版那样会显示up主与视频封面？

**Comment by jjj201200** [comment]
1.1.4本版已经上架，请及时更新

**Comment by LzNOHentai** [comment]
> 1.1.4本版已经上架，请及时更新

感谢恢复封面显示功能！但是还是希望能够把显示up主的功能一并恢复，因为关注的多了，有时候同一分类的视频光看标题封面并不能区分出来是谁投稿的，还是希望能够快速鉴别一下。
