### ISSUE TITLE
一些改善UX的小建议（通知缩略图、设置选项卡、默认跳转）

### ISSUE THREAD

**Issue by Tansc161** [zacyu/bilibili-helper#521]
## 功能建议
- 新版视频更新通知里的视频缩略图消失了（只有助手的icon）
- 设置页有二次菜单的选项只能点击灰色部分展开选项，希望整个选项卡都能点击（“关于”部分下的公告则无此问题）
![image](https://user-images.githubusercontent.com/37703689/48848011-ee844000-eddd-11e8-953f-0859c953fee2.png)
- 建议跳转框在只输入数字的情况下能默认跳转到/识别为视频(av xxx)。

### 环境信息
1. 操作系统 : Win10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 67
3. 扩展版本: 1.1.3

**Comment by jjj201200** [comment]
1.1.4本版已经上架
