### ISSUE TITLE
反查弹幕发送者似乎会查到Lv0用户

### ISSUE THREAD

**Issue by xmcp** [zacyu/bilibili-helper#522]
http://link.acg.tv/forum.php?mod=viewthread&tid=19410&extra=page%3D1

据我所知哔哩哔哩助手在处理一个hash对应多个UID的情况时，会输出不满足 `isRobotUser` 的其中一个，所以会出现结果不准确的情况。
而且 `isRobotUser` 的判断条件也过于严格，只要一个用户有 `name`，即使是 Lv0 也会被认为不是机器人用户，而事实上 Lv0 的用户根本不能发弹幕。

我的建议是：在输出结果时过滤掉 Lv0 的用户；有多个可能性时全部显示出来。

**Comment by jjj201200** [comment]
确实应该显示全部的可能性
之前我不确定0级是否能发弹幕所以屏蔽的时候比较谨慎，既然可以确定不能发弹幕的话，那我直接去掉吧，之后版本修复这个bug
