### ISSUE TITLE
我的插件不显示‘我的关注’选项了！

### ISSUE THREAD

**Issue by IsChengxy** [zacyu/bilibili-helper#524]
1. 操作系统 (Windows/macOS/Linux): Windows10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):70.0.3538.102（正式版本） （64 位）
3. 扩展版本: 1.1.4

![snipaste_2018-11-22_19-11-52](https://user-images.githubusercontent.com/37395169/48899407-7cb60000-ee8a-11e8-80aa-33a694327dbb.png)

**Comment by IsChengxy** [comment]
今天清除浏览器缓存了，没登录。。。。
把问题关闭了吧。

**Comment by jjj201200** [comment]
登陆之后就有了
