### ISSUE TITLE
字幕下载失效

### ISSUE THREAD

**Issue by wlkz** [zacyu/bilibili-helper#528]
RT
![image](https://user-images.githubusercontent.com/42271092/48946488-e3115000-ef68-11e8-8cb8-7592573ae59b.png)

**Comment by wlkz** [comment]
扩展版本 1.1.4

**Comment by jjj201200** [comment]
字幕下载失败原因是助手出了一个bug，导致发送大量请求，已经被b站禁了，等1.1.5就好

**Comment by wlkz** [comment]
1.1.5测试版貌似也不太行

**Comment by wlkz** [comment]
看起来开了pakku弹幕发送者查询好像也获取不了弹幕了（虽然可以在pakku里看）

**Comment by jjj201200** [comment]
@wlkz b站仍在拦截，所以还是下载不了，什么时候好了我会通知一下

**Comment by jjj201200** [comment]
@wlkz 兼容pakku的哦

**Comment by wlkz** [comment]
嗯的确是不是pakku的锅，有次弹幕能加载出来了，不过成功率不太高不知道是那个环节出了问题
