### ISSUE TITLE
360急速无法安装.

### ISSUE THREAD

**Issue by chls1** [zacyu/bilibili-helper#529]
![qq 20181124011748](https://user-images.githubusercontent.com/45295323/48955028-e61b3900-ef86-11e8-9bf7-2d3f85de82b0.jpg)
![qq 20181124001458](https://user-images.githubusercontent.com/45295323/48955043-f6331880-ef86-11e8-8b0e-6cf411767dad.jpg)

**Comment by jjj201200** [comment]
请更换更新版本的浏览器，确保内核版本高于56
