### ISSUE TITLE
台港澳版新番动画的观看似乎失效了。

### ISSUE THREAD

**Issue by ljxfstorm** [zacyu/bilibili-helper#53]
![image](https://cloud.githubusercontent.com/assets/7077478/9995326/20ad2426-60b4-11e5-9a02-fa558b3343b3.png)
![image](https://cloud.githubusercontent.com/assets/7077478/9995332/243d10f6-60b4-11e5-8a66-8854f77390b1.png)
![image](https://cloud.githubusercontent.com/assets/7077478/9995337/2f3a3a1a-60b4-11e5-921b-5670ea25efb4.png)
以上。

**Comment by zacyu** [comment]
<img width="1001" alt="screen shot 2015-09-21 at 12 26 25 pm" src="https://cloud.githubusercontent.com/assets/1730305/9997778/03f54bcc-605c-11e5-9cb1-caf2c01b305b.png">
我这边测试并没有遇到问题, 此外麻烦您尝试一下替换 HTML5 播放器是否可以播放. 谢谢 :)

**Comment by zacyu** [comment]
@ljxfstorm 事实上, 我发现一个可能导致台港澳替换失败的问题. 已经在最新的 commit 中修复, 下次更新中将包含.

**Comment by zacyu** [comment]
v0.7.3 中已修复.
