### ISSUE TITLE
在美国突然不能打开网页，显示unsupported protocol

### ISSUE THREAD

**Issue by bashang03** [zacyu/bilibili-helper#530]
打开b站主页的时候，不能成功加载，显示
![image](https://user-images.githubusercontent.com/35508406/48956305-5b9fee80-ef20-11e8-889c-b7a1c4fb7d21.png)
使用chrome的ultrasurf插件后可以解决

**Comment by jjj201200** [comment]
您好，请问是在仅启用助手时无法打开吗？关闭助手后可以打开吗？

**Comment by bashang03** [comment]
> 您好，请问是在仅启用助手时无法打开吗？关闭助手后可以打开吗？

不是，不管是否启用助手都无法打开，感觉应该是b站的问题？

**Comment by jjj201200** [comment]
@bashang03 确实，如果是b站的问题的话，还请向b站客服反馈。
