### ISSUE TITLE
1.1.5 新打开的标签页的视频如果不是直接激活在后台的情况下，再激活时自动宽屏失灵，需要在页面刷新

### ISSUE THREAD

**Issue by llconan** [zacyu/bilibili-helper#531]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):win10 64x
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):360浏览器10.0.1508.0
3. 扩展版本:1.1.5

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)

**Comment by jjj201200** [comment]
您好，自动功能仅仅是作为一种默认设置作用。不是很清楚您描述的“直接激活在后台的情况”指的是什么，他们的作用原理可简单描述为检测视频的地址是否变化，如果变了（如刚打开页面时播放器会初始化，赋予新的视频源地址、切换视频分P或者新版页面切换别的视频时）就会进行所谓自动设置的默认行为。

**Comment by jjj201200** [comment]
如果有什么播放页面不支持，请提供一下视频连接，谢谢

**Comment by llconan** [comment]
打开新标签也不是有两种情况吗，一种是打开直接显示切换到打开的标签，另一种是打开了不切换停留再当前页面的，如果是不切换那种，等视频页面打开了加载结束之后切换到新开的页面，就不会自动宽屏

**Comment by jjj201200** [comment]
@llconan 了解了，谢谢反馈问题

**Comment by jjj201200** [comment]
1.1.6版本已经上架，请及时更新

**Comment by llconan** [comment]
还是不行啊，现在正常的直接激活的情况宽屏模式都没了

**Comment by jjj201200** [comment]
@llconan 请您换一个浏览器试试

**Comment by llconan** [comment]
卸载了重新安装之后好了
