### ISSUE TITLE
快速跳转无法跳转到<=1000的id

### ISSUE THREAD

**Issue by Tansc161** [zacyu/bilibili-helper#532]
## 问题反馈
快速跳转在输入少于1001的id时框框会变成红色无法跳转。
例如：输入 `2`、`av314`、`cv1`、`au9` 等皆无法跳转。
### 环境信息
1. 操作系统: W10
2. 浏览器版本: Chrome 70
3. 扩展版本: 1.1.5
### 重现步骤/尝试的解决方案
1. 点击插件图标，快速跳转框
2. 输入<=1000的任何id尝试跳转

更新：暂时可用 `<prefix>000<id>` 进行跳转。（如`cv0001`、`av0314`）

**Comment by jjj201200** [comment]
是的，纯数字默认为avid，所以cvid请带上前缀
关于cv1这种。。。我之后将大于1000这个限制改成仅为用于判断avid好了

**Comment by jjj201200** [comment]
1.1.6版本已经上架，请及时更新
