### ISSUE TITLE
无法下载外挂字幕

### ISSUE THREAD

**Issue by Z-fly** [zacyu/bilibili-helper#533]
![image](https://user-images.githubusercontent.com/10470892/48975071-cded0c00-f0a3-11e8-9a07-d793d9500d97.png)

https://www.bilibili.com/video/av35346701

**Comment by jjj201200** [comment]
#528 该问题是由于b站屏蔽相关接口导致的。之前由于助手在后台发送了大量请求导致b站采取了相关措施进行了屏蔽。所以该问题等到助手版本更迭后，即可得到解决，请勿重复提交。

**Comment by jjj201200** [comment]
1.1.6版本已经上架，请及时更新
