### ISSUE TITLE
最新版本无法下载视频

### ISSUE THREAD

**Issue by YFTX2015** [zacyu/bilibili-helper#534]
## 问题反馈
在您提交问题前, 请检查以下项目:
- [ ] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [ ] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [ ] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [ ] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):
3. 扩展版本:

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)

## Feedback
Before submitting your issue, please check to make sure of the following:
- [ ] You are reporting a bug or making a feature request. If you are looking for general support, please contact us directly or comment at our project homepage.
- [ ] Your issue is not a duplicate of an existing issue. If there is an open issue of the same topic, please just comment under it.
- [ ] If you are reporting a bug, please make sure it can be reproduced in the latest release or master branch. Also, please specify detailed procedures to reproduce the bug (screenshots would be greatly appreciated).
- [ ] You have filled out your system environment info.

### Environment Info
Please fill out the following:
1. Operating System (Windows/macOS/Linux):
2. Chrome Version (You can check this under [Menu/Help/About]):
3. Extension Version:

You can see this on extension options page. You can also put the latest commit ID here if you are reporting about the master branch. 

### Steps to Reproduce / Attempted solution
Please be specific here, thanks :)
最新版本：v1.1.3下载视频功能退化了，完全当不到上个版本。上个版本还能至少还能下载大会员视频，而这个版本则不断显示需要改变清晰度以获取视频，然后当我改变清晰度后，助手显示却没有任何改变，还是显示要改变清晰度以获取视频，真令人失望！

**Comment by jjj201200** [comment]
你好，助手已经更新到1.1.5版本，请尽快更新。
另外，请问您是否是在老版本的播放页面下载的？

**Comment by YFTX2015** [comment]
对啊

**Comment by jjj201200** [comment]
补充一下，助手对新版播放页面的支持还在开发中，目前尚不理想，所以请需要下载的话请切换到旧版播放页面

**Comment by jjj201200** [comment]
@YFTX2015 请发一下没有办法获取到下载地址的视频链接，
并提供一下您的浏览器版本信息，谢谢

**Comment by YFTX2015** [comment]
https://www.bilibili.com/bangumi/play/ep250493/?spm_id_from=333.334.b_62696c695f62616e67756d69.18
115浏览器

**Comment by YFTX2015** [comment]
最新版

**Comment by YFTX2015** [comment]
我觉得番剧页面从来没变过，上个版本就能在番剧页面正常下载。倒是其他UP主单独投稿视频的页面风格发生了改变。

**Comment by jjj201200** [comment]
@YFTX2015 请问助手更新到1.1.5后还有问题吗

**Comment by YFTX2015** [comment]
主页看到还是1.1.3。我现在用的是jjdown
