### ISSUE TITLE
1.版本点击图标响应很慢啊

### ISSUE THREAD

**Issue by Oborozukiyo** [zacyu/bilibili-helper#535]
点击图标快速跳转是我用的最多的功能，因此升1之后响应时间太长变得十分难受
即使关闭掉一些新功能但是响应时间还是没变
暂时回退到0.9.9，但是老会自动更新。。。
有关闭0.9.9自动更新的办法吗，或者关闭掉某些功能后能达到0.9.9的响应时间
快速跳转用惯了回不去了，拜托🙏

**Comment by jjj201200** [comment]
请问您用的助手是什么版本？是什么浏览器？内核版本是什么？请根据issue模板填写相关信息，然后再清楚描述您的问题。如您说的“点击图标快速跳转”是指扩展菜单的助手喵的图标点击后菜单弹出的速度慢，还是点击跳转按钮后打开跳转页面的速度慢?

**Comment by jjj201200** [comment]
关于这个问题我之前有意识到，之后想办法优化一下。

**Comment by Oborozukiyo** [comment]
不好意思啊，是我没有说清楚
跳转慢指的是点击图标后菜单弹出比较慢

操作系统 :macOS 10.13.6
浏览器版本:Chrome Version 66.0.3359.181 (Official Build) (64-bit)
扩展版本: 用的谷歌商店版本，一直在自动更新，v1之后的几个版本基本都用过吧，前几个版本很慢有时要等好几秒，今天自动更新为1.1.6后，虽比不上0.9.9的速度，不过基本上比前面几个版本快了不少，不过有时候点击会卡住，重新再点两下能恢复。
也不知道是不是我Chrome好久不更新的缘故
（有时会卡在这里）
![image](https://user-images.githubusercontent.com/9562905/49146488-34d92200-f33d-11e8-8105-e4a03458e5e7.png)

**Comment by Oborozukiyo** [comment]
0.9.9我自己找办法阻止自动更新了，就不麻烦您了，期待您之后的更新

**Comment by jjj201200** [comment]
@Oborozukiyo 您好，其实由于新版本的页面都是根据不同的情况动态构建的，所以会有一个加载过程，我已经优化了这个过程。
