### ISSUE TITLE
消息推送变成WIN10系统消息推送，能改回去吗？

### ISSUE THREAD

**Issue by CatSamaaa** [zacyu/bilibili-helper#536]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):  WIN10 1809 工作站专业版
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):  Chromium 70.0.3538.110
3. 扩展版本:1.1.6

![image](https://user-images.githubusercontent.com/34727840/49148662-e2026900-f342-11e8-9364-d411eeb62b6c.png)

以前推送消息都是页面内推送的，现在改成WIN10系统消息推送了， 是Chromium 70的锅吗？有改回去的办法吗？

**Comment by jjj201200** [comment]
@CatSamaaa 是的，从chrome 68 开始使用系统的通知功能
你可以使用chrome打开[link](chrome://flags/#enable-message-center-new-style-notification)来禁用
![image](https://user-images.githubusercontent.com/3397549/49149153-4d006f80-f344-11e8-818c-851049f33824.png)
