### ISSUE TITLE
csrf_token 有问题？

### ISSUE THREAD

**Issue by mycraftmw** [zacyu/bilibili-helper#537]
https://github.com/zacyu/bilibili-helper/blob/3af44204a80c01b618a2a07ba2b14d275234dab1/src/js/modules/silver2coin/index.js#L34

csrf_token应该是用的cookie里的bili_jct字段。

**Comment by jjj201200** [comment]
您再仔细看一下？没错啊

**Comment by mycraftmw** [comment]
对哦。那我这里这个功能自动兑换好像不太成功。。。emmm，您是设置了每天固定时间兑换还是每天第一次打开B站时兑换？

**Comment by jjj201200** [comment]
打开浏览器会试一次，如果一直没关到第二天也不会

**Comment by jjj201200** [comment]
和自动签到一样，大多数人会每天开启浏览器，所以没有做定时任务

**Comment by jjj201200** [comment]
确实有问题，下个版本修复这个问题，然后为期增加一个至少每天一次的时钟好了

**Comment by mycraftmw** [comment]
好的！辛苦！感谢开发！
