### ISSUE TITLE
去污粉失效了？

### ISSUE THREAD

**Issue by x-Mercy** [zacyu/bilibili-helper#539]
1. 操作系统 Windows
2. 浏览器版本: 70.0.3538.110
3. 扩展版本:1.1.6

**Comment by jjj201200** [comment]
1.1.7刚刚上架了，去更新一下吧

**Comment by Qixingchen** [comment]
1.1.7 依旧失效  
chrome  70.0.3538.110 64bit   
Win 10 64 bit   

附 console:  
![image](https://user-images.githubusercontent.com/4182240/49289551-14e16400-f4df-11e8-985d-449021f613fe.png)

**Comment by jjj201200** [comment]
请卸载后重新安装，即可解决问题
