### ISSUE TITLE
无法安装和更新

### ISSUE THREAD

**Issue by ForeverBRS** [zacyu/bilibili-helper#540]
安装或更新时出现“CRX_VERSION_NUMBER_INVALID”

环境信息：
1.系统：Windows 10 1809
2.浏览器版本：UC浏览器6.2.4094.1
3.插件版本：1.1.7&1.1.6

![2018-12-01 134436](https://user-images.githubusercontent.com/43440593/49324752-443fb180-f56f-11e8-90c1-75dc0a3cfc06.jpg)

**Comment by jjj201200** [comment]
请更换更新浏览器版本或者更换其他其他浏览器（浏览器的webkit内核需大于等于56）。
