### ISSUE TITLE
解决一个强迫症问题

### ISSUE THREAD

**Issue by Z-fly** [zacyu/bilibili-helper#541]
跳转后清空此文本框
![image](https://user-images.githubusercontent.com/10470892/49334565-f3ce5f80-f613-11e8-926f-e9cc9993c64a.png)
<br>
![image](https://user-images.githubusercontent.com/10470892/49334570-11032e00-f614-11e8-8308-f330a89e7d0b.png)
建议在这里加个清空搜索框的开关

**Comment by Z-fly** [comment]
> 暂时不会考虑添加这个选项。

文本框能清空吗？

**Comment by jjj201200** [comment]
会保留上一次的查询id，不会默认清空，该行为暂时不做更改。
