### ISSUE TITLE
diy去污粉

### ISSUE THREAD

**Issue by sxinxins** [zacyu/bilibili-helper#542]
1. 操作系统 (Windows/macOS/Linux): win10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):chrome68.0.3440.106
3. 扩展版本:1.1.7

请问直播间版聊右下角的去污粉还会添加么，我卸载重装了扩展也没看到。想单独设置某个直播间的

**Comment by jjj201200** [comment]
以前的去污粉已经改的成了编辑框上面的禁止图标，如果没有看到，请尝试卸载助手再重新安装。

**Comment by jjj201200** [comment]
![image](https://user-images.githubusercontent.com/3397549/49376730-393d7a80-f743-11e8-8cf4-e96eeef6e439.png)

**Comment by sxinxins** [comment]
哦哦  谢谢提醒  看到啦~
