### ISSUE TITLE
同一TAB页面切换分P后视下载的频源仍旧是切换之前的

### ISSUE THREAD

**Issue by WildDagger** [zacyu/bilibili-helper#543]
這個影片分成四個段落
https://www.bilibili.com/video/av37474819/?p=2

但我用助手下載的時候載前兩個發現都只載到第一個段落
不知道是發生甚麼狀況(或者是BUG？)

助手版本編號是1.1.7
Chrome版本是70.0.3538.110 (正式版本) (64 位元)

因為急著想要載第二個段落所以想請問是否為BUG
或者只是有什麼地方設定出錯了

**Comment by jjj201200** [comment]
啊，这确实是一个没有被反馈过的bug。谢谢您的反馈。暂时的解决办法是切换分P后刷新页面，助手将重新获取页面视频数据。

**Comment by jjj201200** [comment]
1.1.8已经上架，请及时更新
