### ISSUE TITLE
求助 最近两天插件失效了

### ISSUE THREAD

**Issue by hxcrab** [zacyu/bilibili-helper#55]
本人在西雅图地区  最近两天莫名的无法观看B站了

进入页面后 先是插件正常运作 ->正在尝试替换播放器
随后跳转到小电视，再然后又跳转到版权问题页
![image](https://cloud.githubusercontent.com/assets/3356153/10269500/5aa5b1be-6a8e-11e5-87e9-037ff57d026d.png)

//
![image](https://cloud.githubusercontent.com/assets/3356153/10269503/7069e2c2-6a8e-11e5-9fd6-0f0b910f3bfd.png)

**Comment by zacyu** [comment]
嗯, 我的代理服务器 IP 被 B 站那边 blacklist 了. 我会在近两日内推送一个更新版本解决此问题.

**Comment by zacyu** [comment]
v0.7.3 中已修复.
