### ISSUE TITLE
哔哩哔哩在近期改变了视频传输方式【说法貌似不恰当】

### ISSUE THREAD

**Issue by starxjys** [zacyu/bilibili-helper#554]
它把原来的多个分段文件改为.m4s串流来加快速度，应该只对最近1周新上传的视频有效
旧版的视频没有影响
还有就是新版界面不能解析视频地址

**Comment by starxjys** [comment]
https://www.2cto.com/kf/201712/703558.html
可以参考一下，亲测可行

**Comment by jjj201200** [comment]
谢谢反馈，issue重复，#553
