### ISSUE TITLE
猎豹浏览器无法安装1.1.8版本，提示程序包无效

### ISSUE THREAD

**Issue by lyp0454** [zacyu/bilibili-helper#555]
猎豹浏览器无法安装新版本（1.1.8），提示 程序包无效 CRX_VERSION_NUMBER_INVALID 。
按照教程，使用开发者模式并加载解压文件夹也没有反应。
系统版本win10 1803，猎豹版本6.5.115.18629.8004

**Comment by jjj201200** [comment]
请更新您的浏览器版本或更换其他浏览器，该错误说明表示您目前使用的浏览器不支持新的扩展版本CRX3

**Comment by lyp0454** [comment]
已升级到最新的6.5.115.19211.8001版本，仍无法使用。只能等猎豹自己更新内核版本是吗？

**Comment by jjj201200** [comment]
@lyp0454 建议更换浏览器
