### ISSUE TITLE
在哔哩哔哩电影页面无法正确显示UI

### ISSUE THREAD

**Issue by molingyu** [zacyu/bilibili-helper#559]
## 问题反馈
b站 神奇动物：格林德沃之罪 使用了一个全新的播放页面，使得页面无法正确显示助手的UI
![tim 20190216162524](https://user-images.githubusercontent.com/8806796/52896821-e0d92d80-3207-11e9-930c-b73fe5d05321.png)

console报错：
![tim 20190216162721](https://user-images.githubusercontent.com/8806796/52896855-7b397100-3208-11e9-81d6-62980750d9a1.png)

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Google Chrome 版本 72.0.3626.109（正式版本 64 位）
3. 扩展版本:version 1.1.8（正式版）

### 重现步骤/尝试的解决方案
[b站 神奇动物：格林德沃之罪](https://www.bilibili.com/bangumi/play/ep262628/) 在该页面观看则会发现UI失效

**Comment by jjj201200** [comment]
你好，请使用加入测试群使用测试版。

**Comment by jjj201200** [comment]
duplicate #552
