### ISSUE TITLE
HTML5播放器似乎不支持乐视云源视频了？

### ISSUE THREAD

**Issue by 872517414** [zacyu/bilibili-helper#58]
以前支持，但是不支持清晰度选项，就是流畅画质并非原画画质。

**Comment by zacyu** [comment]
麻烦给一个样例?

**Comment by 872517414** [comment]
http://acg.tv/av2538519

**Comment by zacyu** [comment]
Fixed in bd41da1169605c4c125825262de4d17d14426f5c
