### ISSUE TITLE
0.7.4版本和unblock youku插件冲突？

### ISSUE THREAD

**Issue by HongyiZhu** [zacyu/bilibili-helper#59]
更新完插件后chrome插件管理unblock youku项提示Warning:This extension failed to modify the request header "X-Forwarded-For" of a network request because the modification conflicted with another extension (Bilibili Helper: Bilibili.com Auxiliary). bilibili助手是否与unblock youku的功能有重叠？

**Comment by zacyu** [comment]
更新新版 (v0.7.4) 后, 如果您同时安装了 Unblock Youku, 可能会出现如图的提示. 如果出现该警告, 并不用担心, 因为 Bilibili 助手只会修改 bilibili.com 下的 request header, 针对部分仅限台港澳的番租需要覆盖掉 Unblock Youku 写的大陆 IP. 对 Unblock Youku 的正常使用并无影响.
![Unblock Youku Conflict Warning](https://cloud.githubusercontent.com/assets/1730305/10317235/72fb7aba-6c31-11e5-8ce0-760709d4456b.png)

**Comment by zacyu** [comment]
issue 我先关了, 如果有疑问可以继续提出.

**Comment by HongyiZhu** [comment]
Cool. 和我的猜想一致～多谢！



—
通过 Mailbox 发送
