### ISSUE TITLE
自带循环的弹幕失效

### ISSUE THREAD

**Issue by shuangzhijinghua** [zacyu/bilibili-helper#60]
栗子：http://www.bilibili.com/video/av820807/
另外弹幕文字字号大小和flash版的差别在于flash版的弹幕字号是固定大小的，而HTML5的弹幕是相对大小，播放窗口增大字体也增大，不知算不算BUG？
画质方面有差别，HTML5播放器会选择到低画质的视频源，而FLASH播放器则不会。
栗子：http://www.bilibili.com/video/av1289013/

**Comment by zacyu** [comment]
在之后的版本中可能会加入代码弹幕支持.

**Comment by cnbeining** [comment]
除非上游CCL支持，否则下游不会也不应该支持。

随便运行任何人都可以插入的JS是作死的行为。

**Comment by zacyu** [comment]
@cnbeining CCL 那边支持的 https://github.com/jabbany/CommentCoreLibrary/tree/master/build/scripting
