### ISSUE TITLE
有空的话希望能增加直播页面的支持，谢谢

### ISSUE THREAD

**Issue by ruizhipeng** [zacyu/bilibili-helper#62]

**Comment by cnbeining** [comment]
之前有可能，但是上个星期开始，不可能。

之前Safari是有HTML5版本的。（虽然我没有能够播放，海外速度问题）

我也写过一个本地的版本：https://github.com/cnbeining/ABPlayerHTML5-Py ```live.py```

目前API开放。

但是，我没有想到任何办法使用HTML5处理```xmlsocket```. 这代表浏览器无法加载弹幕。

如果有可能，请不吝赐教。

**Comment by zacyu** [comment]
`xmlsocket ` 目前应该是没有纯 HTML5 的解决方案, 但是可以考虑 haxe? 即嵌入一个 swf 用来提供 API 给 JavaScript.
