### ISSUE TITLE
与unblock youku有扩展程序冲突错误

### ISSUE THREAD

**Issue by laurencedu** [zacyu/bilibili-helper#63]
虽然不管哪边生效结果都是好的，但是有那么个错误挂着总不是好事……助手的设置页没有看到相关的选项，如果能做一下兼容性修复就好了。
毕竟unblock youku那边支持范围要广的多。

**Comment by zacyu** [comment]
您好, 问题重复. #59 中我提到过, Bilibili 助手只会修改 bilibili.com 下的 request header, 针对部分仅限台港澳的番租需要覆盖掉 Unblock Youku 写的大陆 IP. (如 http://www.bilibili.com/video/av2965263/) 如果我这边不覆盖 Unblock Youku 写的大陆 IP 的话会导致播放地址加载失败.
此外, 这个警告并不是错误, 不会导致任何额外的问题, 且目前由于 Chrome 的扩展冲突管理机制, 并没有办法做兼容. 如果想要人为兼容的话也是需要 Unblock Youku 那边做出修正而不是我这边做出修正.

**Comment by zacyu** [comment]
issue 我先关了, 如果有疑问可以继续提出.
