### ISSUE TITLE
HTML5解析播放清晰度不如原生Flash

### ISSUE THREAD

**Issue by Sg4Dylan** [zacyu/bilibili-helper#64]
比如（
http://www.bilibili.com/video/av113205/index_6.html

插件为 Chrome Web Store 上最新版本
Chrome版本 47.0.2526.5 dev-m (64-bit)

以上

**Comment by zacyu** [comment]
少数使用新浪源的远古视频不存在 mp4 高清版本, 目前没有较好的解决方案.

**Comment by cnbeining** [comment]
Just saying:

如果。。。。。。。只是完全的如果。。。。。

我们自行在浏览器里面 调用ffmpeg 自行混流 就达到同样的清晰度了。

当然浏览器有可能爆炸就是了～

**Comment by zacyu** [comment]
如果是说用 Emscripten 编译出来的那个的话, 真心会爆炸的吧 😂 以及如果用它的话直播也是可以转换的吧? 你要是有空的话可以去试试看.

**Comment by cnbeining** [comment]
直播并不用这么麻烦。

对于Safari，可以直接调用；

对于其他新浏览器，直接https://github.com/dailymotion/hls.js 就是。

然而因为跨域问题，以及我不想实现一个反代，我没有直接调用，而是用ffmpeg本地编码。

CORS坑死人。。。。

**Comment by zacyu** [comment]
B 站现在用的不是类似 http://live-play.acgvideo.com/live/live_9336_332_c521e483.flv 这种 flv 封装的 h.264 直播的吗?

**Comment by cnbeining** [comment]
还有一个HLS版本，在一个其他API。

然而我忘记地址了（

**Comment by 5wcx** [comment]
> 少数使用新浪源的远古视频不存在 mp4 高清版本, 目前没有较好的解决方案.

请问 现在如何获取高清的mp4 接口是什么呢？
