### ISSUE TITLE
增加ass格式弹幕下载の可能性？

### ISSUE THREAD

**Issue by bsns** [zacyu/bilibili-helper#75]
xml在linux下似乎没有合适的转码工具，也没有播放器支持。

**Comment by FiveYellowMice** [comment]
[早就有了](https://github.com/m13253/danmaku2ass)，不过要在插件中加入这个功能的话，恐怕得把那个东西用 JS 重新实现一遍。

**Comment by tiansh** [comment]
@FiveYellowMice js的你试试 tiansh/us-danmaku ？
