### ISSUE TITLE
请求上架微软新版 Edge 应用商店

### ISSUE THREAD

**Issue by OlingCat** [zacyu/bilibili-helper#753]
## 功能需求
虽然新版 Edge 目前可以直接安装 Chrome 应用商店里的扩展，但还是有 Edge 商店的原生发布更好些，一方面方便更新，另一方面不用挂梯子，推广起来也容易些。

参考：[Porting an extension from Chrome to Microsoft Edge](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions)

**Comment by OlingCat** [comment]
唔..那么就在主页上加下连接吧XD

**Comment by jjj201200** [comment]
@OlingCat 恩啊~
