### ISSUE TITLE
频繁发送 IP 地理信息获取请求冲突

### ISSUE THREAD

**Issue by LenKiMo** [zacyu/bilibili-helper#76]
插件似乎是在使用时会向 http://www.telize.com/geoip 发送IP信息并进行查询的请求，有如下情况：
在使用拦截软件 Adguard 时，可能会将向上述网址发送信息时的请求拦截。而一旦拦截，插件将会继续不停地发送请求直至成功为止。每秒可能发送数次至十次，这将导致不断发送请求拉高系统的资源占用（虽然不一定来源于插件本身）。
如果这一地理信息的获取只运用于插件本身，建议增加一个判断，在数次未成功获取地理信息时，不再大量发送请求，而是弹窗提示用户无法获得相应的 IP 地理位置信息，请求用户关闭可能的拦截软件或者是允许用户自行选择自己 IP 地址的地理位置（提示如果有使用代理的话则输入代理所在地位置一类）。以免无限的发送请求导致其他的浏览体验受到影响，因为只要插件在后台运行即使没有访问 B 站也会不断地试图获取对应的地理位置信息，而这似乎并不是那么必要。

**Comment by zacyu** [comment]
0cb741ba7886886b67dd1e203fd5ac495bf94c20 中已修复. 更新已经提交到 Chrome Web Store. 造成的不便请谅.
