### ISSUE TITLE
求权限解释（申请所有网页内容相关）

### ISSUE THREAD

**Issue by pandabo** [zacyu/bilibili-helper#77]
最新的更新中注意到哔哩哔哩助手多了两个权限，分别是“管理下载内容”和“读取和更改访问网站上的所有数据”。我很好奇为啥需要一个针对所有访问的网站的权限，仅仅B站的内容不行么？？？
![b](https://cloud.githubusercontent.com/assets/8510422/11178127/ea7f505a-8c4a-11e5-91a7-a828bd1dc768.PNG)

**Comment by SilverBut** [comment]
Issue #33 中提到过该问题，且迄今并未加入Opt-out选项。

**Comment by zacyu** [comment]
这次更新新增的只有第二个权限, 用来更改下载视频的文件名 c7a80fe5ae2ab39cf9117a8244e8b22f0bdb0356. 针对全站的权限目前主要用作统计代码支持 (#33) 和 html5 播放器针对 CDN 跳转至 IP 地址 host 的权限应对 (#67). 不过不增加权限 header 会导致乐视源等 html5 内容无法播放.

**Comment by zacyu** [comment]
@SilverBut 现在已经不只是那个需求了, 还有 #67 中提到的权限问题.

**Comment by SilverBut** [comment]
@zacyu 多谢解释。下次还是放在更新说明里面吧，要不更新一个版本来一个人问，挺麻烦的……
