### ISSUE TITLE
为什么需要【管理我的下载内容】的权限呢？

### ISSUE THREAD

**Issue by Explorare** [zacyu/bilibili-helper#78]
![image01](https://c.hime.io/images/2015/11/16/2154765682671317.jpg)

请问为什么这个插件需要访问我的下载内容呢？是需要实现什么特殊功能么？

**Comment by zacyu** [comment]
为了替换下载视频的文件名.

**Comment by zacyu** [comment]
参见 c7a80fe5ae2ab39cf9117a8244e8b22f0bdb0356.

**Comment by Explorare** [comment]
那么能否只针对从 B站下载的视频，或者特定视频格式 进行重命名呢？不然势必会和别的 download manager 发生冲突。谢谢。

**Comment by zacyu** [comment]
cc: @carltonf

**Comment by carltonf** [comment]
这个listener本来就是只针对 bilibili 视频的，但是和文档中说的不一样：

**Comment by zacyu** [comment]
所以实际的 behavior 和 documentation 不同吗? 我对 documentation 的理解是如果直接 `suggest() ` 的话就没有 pass a `suggestion` object to `suggest`, 从而会让另一个 extension whose listener passes a `suggestion` win. 我还没有实际测试, 不过如果确实这样的话可以去 file 一个 bug 过去.
此外, 关于你提出的两个解决方案, 目前都并不是很满意. 第一个我也不能接受. 第二个相对好一些, 但是改变用户操作习惯也会相对影响用户体验.

**Comment by swj1442291549** [comment]
建议增加开关来使用此功能

**Comment by carltonf** [comment]
@zacyu 我认为这个地方 suggest 的行为确实是个 bug，过会儿细看下，去报一个去。
和我先前想的不同, 可以在 background 里调用下载函数，所以只需要点击下载链接时向后台发一个命令就好，已不需要改动UI了。

@swj1442291549 #82 里的实现，我认为已经好很多，作为默认应该没问题了。新 feature 确实应该加个开关，避免干扰正常功能。

另外 @zacyu 是否考虑弄个 nightly build? 这样也方便预先测试。
