### ISSUE TITLE
Html5 播放器的视频载入问题

### ISSUE THREAD

**Issue by uyx6345** [zacyu/bilibili-helper#84]
右击在新窗口播放视频没有任何问题，但嵌入的 Html5 播放器却无法 Loading，已经有几个版本存在这个问题了，想请教一下该如何解决。

**Comment by zacyu** [comment]
最新版中问题依然存在吗? Console 中有任何错误提示信息吗?

**Comment by uyx6345** [comment]
问题还是存在，Console里也有大量的错误。
Uncaught TypeError: Cannot read property 'length' of undefined(anonymous function) @ VM511:1
jquery.min.js:1 GET http://interface.bilibili.com/count?key=3129fa42057f88403ca8112e&aid=3319704&mid=6596647&_=1449213632600 send @ jquery.min.js:1f.extend.ajax @ jquery.min.js:1(anonymous function) @ jquery.min.js:1e.extend.each @ jquery.min.js:1f.fn.extend.domManip @ jquery.min.js:1f.fn.extend.append @ jquery.min.js:1f.fn.(anonymous function) @ jquery.min.js:1(anonymous function) @ VM485:1(anonymous function) @ VM485:1(anonymous function) @ count?aid=3319704&mid=6596647:1
stat.php?id=2724999&web_id=2724999&_=1449213632747:16 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
getHeader?typeid=0&is_article=0:9 Uncaught TypeError: Cannot read property 'style' of undefined(anonymous function) @ getHeader?typeid=0&is_article=0:9(anonymous function) @ getHeader?typeid=0&is_article=0:28
stat.php?id=2724999&web_id=2724999&_=1449213635920:16 Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by zacyu** [comment]
我这边还是无法重现这个问题, console 中也没有出现你提到的错误. 您目前使用的 Chrome 和扩展版本是?

**Comment by tianyikillua** [comment]
我也有过同样的问题，后来把 Unblock Youku 关闭就貌似好了...

**Comment by uyx6345** [comment]
好久不上B站了，今天才看到这个回复。试了一下发现光关闭 Unblock Youku 对我是没有用的，要彻底删除才行。回想了一下问题好像的确是 Bilibili Helper 更新了海外代理的服务后出现的。总之非常感谢，以后让大家把 Unblock Youku 都删了因该就不会有类似问题了。
