### ISSUE TITLE
登录提示"已注册"

### ISSUE THREAD

**Issue by xmt328** [zacyu/bilibili-helper#853]
请保留一种您需要的语言版本的报告模板

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Chrome 版本 91.0.4472.101（正式版本） （64 位）
3. 扩展版本:2.1.4

### 重现步骤/尝试的解决方案
1. 任意设置页面点击登录
2. 点击以<头像>注册bilibili账号(这个页面只有这个注册和取消按钮)
3. 输入QQ邮箱
4. 点击获取验证码

**Comment by jjj201200** [comment]
请尝试重启助手

**Comment by xmt328** [comment]
> 请尝试重启助手

可以了,没想到插件也能重启
