### ISSUE TITLE
最近一直跳出银瓜子自动兑换失败

### ISSUE THREAD

**Issue by brina60602** [zacyu/bilibili-helper#855]
不过我有一天换了2次
![image](https://user-images.githubusercontent.com/15816106/123187580-0740bf00-d4cd-11eb-8480-cb6a8cec479d.png)
![硬幣](https://user-images.githubusercontent.com/15816106/123187688-32c3a980-d4cd-11eb-8af9-edeea9a0e52b.JPG)

**Comment by jjj201200** [comment]
该功能已经在最新测试版本中修复，请留意助手公告推送
