### ISSUE TITLE
【功能建议】"自定义下载文件名"功能增加“分集标题”变量

### ISSUE THREAD

**Issue by wxsms** [zacyu/bilibili-helper#856]
![image](https://user-images.githubusercontent.com/5960988/123408791-0056a100-d5e0-11eb-9496-0235b525509c.png)

![image](https://user-images.githubusercontent.com/5960988/123408849-11071700-d5e0-11eb-9060-609a1e6239bc.png)

**Comment by jjj201200** [comment]
请留意我的b站账号「没睡醒的肉啊」或者官号「助手猫」，这个需求已经添加在最新的测试版
