### ISSUE TITLE
Edge 2.2.0版为什么需要mcbbs.net站点权限

### ISSUE THREAD

**Issue by Flandoll** [zacyu/bilibili-helper#858]
![QQ截图20210721030402](https://user-images.githubusercontent.com/16918689/126382791-4e281f2d-3594-40f4-a8f9-5af0b60eae5f.png)

自动更新到2.2.0后插件被自动禁用，需要允许新的权限才能启用。

**Comment by jjj201200** [comment]
请查收助手公告，已以公告形式通知

**Comment by Flandoll** [comment]
这权限变动公告不发布在网页里吗？
遇到权限变动首先想到去查看公告，结果公告只显示在插件里面，而插件处于禁用状态，网页公告又是很久之前的

**Comment by GalaxySnail** [comment]
在官网没有找到任何相关公告。如果真的在插件里，那么公告意义何在？必须同意许可才能看到公告，但看不到公告怎么同意？

**Comment by qshuage** [comment]
作者，抱歉，我完全不知道 mcbbs.net 网站是干嘛，第一时间是懵的，去了 chrome 的扩展详情页，没看到有公告，然后又打开详情页里面的官方网站 bilibilihelper.com ，但已经好久没有更新了。如果不是看到这个 issue ，我是想不到启用扩展，在里面看公告的

**Comment by jjj201200** [comment]
@Flandoll @qmzmdqs @GalaxySnail @msg7086 非常抱歉，公告是提前一天发的，并且十分抱歉的是我并不知道新增权限会导致助手被禁用再弹出提示框。之后我会设法解决这个无法告知新权限作用的局面，在更新内容中增加说明应该是合适的

**Comment by GalaxySnail** [comment]
知错能改就好。就是长个教训，changelog 这种东西一定要公开发布的，哪怕是闭源软件。尤其是不向后兼容的更新，一定要重点标注出来。权限更改算是一种很大的不向后兼容了

**Comment by jjj201200** [comment]
@GalaxySnail 在chrome的更新内容里是加了说明的哦，但是目前没有很好的办法进行提前说明
![image](https://user-images.githubusercontent.com/3397549/126657918-b25b746b-20e6-4049-85f2-2b078ad3c62f.png)
