### ISSUE TITLE
今天自动更新后个人空间打不开 哔哩哔哩助手：bilibili.com 综合辅助扩展 2.2.1

### ISSUE THREAD

**Issue by 1265578519** [zacyu/bilibili-helper#859]
哔哩哔哩助手：bilibili.com 综合辅助扩展
2.2.1
![image](https://user-images.githubusercontent.com/6442439/126509510-6bcbe6a4-17ae-4572-8bb0-72edddd9525d.png)

**Comment by jjj201200** [comment]
chrome已更新到2.2.2，该问题已经重复 #860
