### ISSUE TITLE
新版本为什么需要读取mcbbs呢？

### ISSUE THREAD

**Issue by 0000000O** [zacyu/bilibili-helper#860]
问题反馈

请填写以下信息:
1. 操作系统:Windows 10 21H1
2. 浏览器版本:Chrome 91.0.4472.164（正式版本） （64 位）
3. 扩展版本:2.2.1
重现步骤:北京时间2021/7/22刚打开电脑就发现了这个事情。。。觉得挺奇怪的
![QQ截图20210722000441](https://user-images.githubusercontent.com/86942399/126522359-28ab1809-33d9-4bab-a28a-d1e242a24d39.png)

**Comment by jjj201200** [comment]
请查收助手公告或者我的b站动态
<img width="652" alt="QQ20210721-201031@2x" src="https://user-images.githubusercontent.com/3397549/126648864-88d41635-2b2a-437c-a6e1-48c7f1272bb0.png">

**Comment by 1265578519** [comment]
![image](https://user-images.githubusercontent.com/6442439/126661984-6f29c163-445f-4a74-a892-f6cfb48ce918.png)
灰色无法禁用

**Comment by jjj201200** [comment]
先点开最上面的开关呀
