### ISSUE TITLE
在Edge中无法单独禁止mcbbs.net站点访问权限

### ISSUE THREAD

**Issue by Flandoll** [zacyu/bilibili-helper#861]
2.2.0公告中写到可以在权限栏中关闭该站点权限，但是Edge中并没有单独禁止特定站点权限的选项
![QQ截图20210722090823](https://user-images.githubusercontent.com/16918689/126578532-81ffd704-68a6-49d2-9b6d-eb56deabd211.png)

**Comment by imlinhanchao** [comment]
試了一下，可以選擇`在特定站點上`，然後填入 `*://*.bilibili.com/*`

**Comment by jjj201200** [comment]
edge的显示是有问题的
你可以单独添加一下host权限
`*://*.bilibili.com/*`
`*://*.bilibilihelper.com/*`
`*://bilibili-helper.github.io/*`
`*://*.hdslb.com/*`
`*://*.bilivideo.com/*`
