### ISSUE TITLE
随着我在直播间的刷新，聊天框正在不断的移出我的屏幕（而且我不能移动它）

### ISSUE THREAD

**Issue by yuijker** [zacyu/bilibili-helper#863]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x]  您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):edge 92.0.902.55
3. 扩展版本:2.2.0

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
随着我不断的重进直播间，开启聊天框显示，聊天框越来越靠近浏览器的底部，而且现在已经被下面的弹幕输入框挡住了，而且我不能移动它。

![screenshot-live bilibili com-2021 07 24-20_36_51](https://user-images.githubusercontent.com/72558803/126868640-b3cd251e-0ace-43a2-af8f-7043ce918332.jpg)

**Comment by jjj201200** [comment]
谢谢反馈，这个问题我们会先记录下来，在后续版本中修复
目前你可以通过清理浏览器缓存来解决这个问题
最后，如果之后有什么问题，请直接向b站「助手猫」反馈哦

**Comment by jjj201200** [comment]
该问题已经在2.2.2.2测试版本中修复，请移步至[下载文档](https://d.bilibilihelper.com/)
