### ISSUE TITLE
音频下载功能用不了。

### ISSUE THREAD

**Issue by wxsms** [zacyu/bilibili-helper#864]
Chrome 和 Edge 都一样，下载回来是个 m4s 文件，命名也和自定义的规则完全对不上。

视频地址：https://www.bilibili.com/video/BV1Jt4y1U7VT?p=3&t=12

定义的自定义命名是：`__CID__.__UPPER__.__DATE__.__FORMAT__`

下载回来的是 `177110025-1-30280.m4s`

版本：v2.2.2（public）

-------------

就是为了这个功能开的 VIP，这时候我是不是应该来一句，RNM 退钱 [doge]

**Comment by wxsms** [comment]
补充说明：2.1.4 是正常能用的，更新后的不行。

**Comment by jjj201200** [comment]
请向助手猫反馈问题哦，作为闭源软件我们不再于这里跟踪问题
请尝试安装最新测试板看看问题有没有解决哦，然后再检查一下是否安装了其他下载管理扩展或者广告屏蔽扩展。

**Comment by wxsms** [comment]
![image](https://user-images.githubusercontent.com/5960988/126979691-f46f27ca-6c05-4e39-8dd1-80bdb1160ecf.png)

@jjj201200 已跟助手猫反馈了同样的内容，如果这里不接受反馈麻烦把你的网站上的 github 反馈链接去掉。

另外，您都看见了就麻烦您处理一下嘛，这么着急关闭干啥呢，我的 edge 是干净的没有任何插件，装了新版本跟 chrome 一个德性。讲道理我好歹也是个付费用户，这个 bug 严重影响使用，该修的 bug 要修的啊，就这态度麻烦您退钱好吧。订单号 1627275456724_450472

**Comment by wxsms** [comment]
你自己在网站上贴 GitHub 反馈链接，自己又在这里说不接受反馈，一句话就关 issue，我真的是服了。

**Comment by jjj201200** [comment]
非常抱歉啊，已经帮你退款，并且保留了你的会员时长
网站我们还没有修改，这就去改一下，抱歉啊

**Comment by wxsms** [comment]
没关系，感谢你做了这个插件，还是很好用的。等这个bug修了我还是会续费的。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DrowsyFlesh ***@***.***&gt;
发送时间: 2021年7月26日 20:01
收件人: bilibili-helper/bilibili-helper-o ***@***.***&gt;
抄送: wxsm ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[bilibili-helper/bilibili-helper-o] 音频下载功能用不了。 (#864)





 
非常抱歉啊，已经帮你退款，并且保留了你的会员时长
 网站我们还没有修改，这就去改一下，抱歉啊
