### ISSUE TITLE
现在直播间的聊天框无法移动

### ISSUE THREAD

**Issue by yuijker** [zacyu/bilibili-helper#865]
请保留一种您需要的语言版本的报告模板
please leave only one kind of these template

## 问题反馈
在您提交问题前, 请检查以下项目:
- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux):windows 7
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看):Edge 92.0.902.55
3. 扩展版本:2.2.2.2

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案
请具体描述, 谢谢 :)
在 #863 中，我有说过，聊天框不只是在下移，而且是无法移动它。现在聊天框的位置就像是被锁死了一样，还是无法移动。

![screenshot-live bilibili com-2021 07 27-10_30_44](https://user-images.githubusercontent.com/72558803/127085951-06faa22e-0dd1-4d4b-96f4-c3fc439d97f7.png)

**Comment by jjj201200** [comment]
请问有安装其他扩展或脚本吗，我尝试过禁用他们吗

**Comment by jjj201200** [comment]
另外，如仍有任何问题请移步向b站「助手猫」进行反馈哈

**Comment by yuijker** [comment]
即使禁用了所有的扩展与脚本，甚至重启浏览器，也没有任何作用。

![捕获](https://user-images.githubusercontent.com/72558803/127113840-c355b8e7-f03a-42fc-b32b-fb7540a5b631.PNG)

**Comment by jjj201200** [comment]
已于2.2.2.3修复哈，如仍有任何问题请移步向b站「助手猫」进行反馈哈，不要以issue的方式反馈了哈
