### ISSUE TITLE
部分菜单显示为空白，开发者工具显示该部分无内容

### ISSUE THREAD

**Issue by laxtiz** [zacyu/bilibili-helper#866]
## 问题反馈

在您提交问题前, 请检查以下项目:

- [x] 您在报告一个 bug 或者提交一个功能请求. 如果您需要一般性的帮助, 请直接和我们联系或者在项目首页下留言.
- [x] 您的问题在与现有问题并不重复. 如果已有一个相同话题的问题, 请直接在其下留言.
- [x] 如果您在报告一个 bug 请确定它可以在最新的发行版或 master 分支下重现. 同时, 请详细说明重现问题的步骤 (如果有屏幕截图的话就更好了).
- [x] 您已填写了系统环境信息.

### 环境信息

请填写以下信息:

1. 操作系统 (Windows/macOS/Linux): `Fedora Linux 34` with `GNOME 40.3.0`
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): `Google Chrome 92.0.4515.131`
3. 扩展版本: `2.2.2`

您可以在扩展选项页中查看. 如果您在报告关于 master 分支的问题, 您也可以在此处填最新的 commit ID.

### 重现步骤/尝试的解决方案

请具体描述, 谢谢 :)

部分菜单内容无显示，已知部分为

- 扩展设置页面左侧菜单
- 扩展图标弹出窗口右侧菜单
- 直播间弹出窗口选项菜单

使用开发者工具查看元素，空白菜单对应HTML标签无内容

### 以下是截图

扩展设置页面截图
![Screenshot from 2021-08-14 09-26-27](https://user-images.githubusercontent.com/3883767/129430674-1fd1c3dc-5d30-449d-8254-c7bcc3e85445.png)

扩展图标弹出窗口截图
![Screenshot from 2021-08-14 09-25-45](https://user-images.githubusercontent.com/3883767/129430664-91a83436-23eb-4499-aee9-c1041c610931.png)

直播间弹出窗口截图
![Screenshot from 2021-08-14 09-25-29](https://user-images.githubusercontent.com/3883767/129430695-f0bfd85d-c89a-42c0-8e66-3b0d9d108d8a.png)

**Comment by jjj201200** [comment]
该问题已在2.2.2.7测试版中修复，请移步至[https://d.bilibilihelper.com/](https://d.bilibilihelper.com/) 下载测试版
注意文档中的红字及测试版的安装方法

![image](https://user-images.githubusercontent.com/3397549/129492720-849789ac-6151-45c0-8726-9156cb7820d4.png)

**Comment by laxtiz** [comment]
我的系统语言及浏览器首选语言确实是English 优先，
我等正式版更新好了，就不折腾测试版了
谢谢解答
