### ISSUE TITLE
缓存方案讨论

### ISSUE THREAD

**Issue by 1265578519** [zacyu/bilibili-helper#867]
切换四倍速为什么↑是0.25，↓时候是0.5，这设计好别扭
```
助手默认调节速度幅度是0.25，助手默认速度幅度调节需要开通助手会员
b站播放器自己的这个幅度就是那样的呀，你可以向b站客服反馈哦，助手的就是一致的0.25
```
还有照你上面说的，助手默认速度幅度是0.25，能不能改成0.5呢，这样就一致了
那可以为了非会员用户考虑下，把默认的倍速间隔统一改为0.5嘛？不然↑↓间隔不同步。。
是按下键盘快捷键shift+↑ shift+↓，这两个间隔不同步，你可以测试一下
![cede4797eb983c190a2b657aeead638f2deaf27c](https://user-images.githubusercontent.com/6442439/129640157-7f1bc121-ef34-45bb-8de4-f4e9d5afe2b4.gif)
我没有会员，是不是这个引起的呢？这是我的复现GIF动态截图
![image](https://user-images.githubusercontent.com/6442439/129640177-10469397-d348-4bc9-92db-8c590720ff31.png)
我找朋友试了下，他也是这个问题，请问这是BUG吗？后续版本会不会进行修复？

```
可能是的，我们会先尝试复现一下这个问题~谢谢你的反馈~
```
10分钟后。。。这效率太强了，马上就给修好了
```
您可以在下载文档中下载到最新2.2.2.8测试版，刚刚开发者修复了这个问题哦
另外还增加了其他内容，可以看一下文档里列出的更新内容哦
http://d.bilibilihelper.com/
```

话说，现在下载是flv格式的，能不能增加一个选项下载m4s格式呢？以便CDN缓存播放提速增强。有时候没缓存的时候播放会卡加载，这时候点击一下下载M4S视频轨道，挂着浏览器后台就可以持续性缓存了，毕竟视频播放不是调用FLV。。。

**Comment by qshuage** [comment]
其实我也建议下载格式能不能改成 mp4 ，或者加多一个格式。毕竟 Windows 默认播放不了 flv

**Comment by jjj201200** [comment]
@qmzmdqs 下载源是flv的，浏览器上不太好进行转码，所以只能是flv的，这不是想不想改的问题，是能不能改的问题。

**Comment by qshuage** [comment]
> @qmzmdqs 下载源是flv的，浏览器上不太好进行转码，所以只能是flv的，这不是想不想改的问题，是能不能改的问题。

这样啊，我是因为用 annie 下载的是 mp4 ，我以为 b 站都支持。
