### ISSUE TITLE
主站功能 - 快捷键 未登录账号情况下，明明是关闭的却能响应

### ISSUE THREAD

**Issue by qshuage** [zacyu/bilibili-helper#868]
## 问题反馈
主站功能 - 快捷键 属于 会员功能
理应默认关闭
但却响应了，但又因为没有登录账号，无法手动开启再关闭一次

（好像记得以前也有这个，后面没了，前几天突然又有，不太确定）

### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): Windows 10
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome 92.0.4515.131（正式版本） （64 位）
3. 扩展版本: version 2.2.5

**Comment by 1265578519** [comment]
啊这，不要啊！修复了不开会员就没快捷键切换倍速功能了

**Comment by qshuage** [comment]
> 啊这，不要啊！修复了不开会员就没快捷键切换倍速功能了

问题在于，装了其它扩展，快捷键干扰了啊。如果只是倍速调节，可以装一个扩展，这样其它视频网站也可以调节了

**Comment by 1265578519** [comment]
那你推荐一个可以给哔哩哔哩设置4倍速的插件，支持快捷键的那种

**Comment by jjj201200** [comment]
注意，「快捷键」不是会员功能，「修改快捷键」才是会员功能
你说的问题我会尝试复现一下

**Comment by jjj201200** [comment]
@qmzmdqs 你描述的「理应默认关闭」，快捷键在设置页面的开启状态是开的还是关的？
「快捷键」不是会员功能，「修改快捷键」才是会员功能。
我这边在设置页面关闭后并没有复现出你的问题。

**Comment by qshuage** [comment]
@jjj201200 在浏览器创建一个用户，重新安装试试，不用登陆任何账号。
因为我没登账号，无法切换开关状态，但我又不想要这个功能，因为冲突得有点多。
很多时候，除了自己的私人电脑，公司电脑这些，我会装这些扩展，但不想登账号。
如果重现不了，我录个 gif

**Comment by jjj201200** [comment]
你需要登录后才能开关设置 @qmzmdqs 无法复现你描述的情况，请检查一下你安装的助手下载来源是否是我们给出的

**Comment by qshuage** [comment]
我想先问一个问题，没登录情况，这个功能的开关默认是开的还是关的

**Comment by jjj201200** [comment]
最新版默认是关闭的。但是你们可能本地缓存了开启状态

**Comment by jjj201200** [comment]
该问题已被修复。
