### ISSUE TITLE
无法播放视频错误：No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by huhuime** [zacyu/bilibili-helper#87]
![image](https://cloud.githubusercontent.com/assets/6631239/11317065/ea0b5444-9059-11e5-99dc-b0f3dcf50cea.png)
Failed to execute 'write' on 'Document': It isn't possible to write into a document from an asynchronously-loaded external script unless it is explicitly opened.
改响应头的代码坏了？
Image from origin 'http://i2.hdslb.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.bilibili.com' is therefore not allowed access.
是不是跨域了无法加载视频

**Comment by zacyu** [comment]
这部分应该和哔哩哔哩助手无关. 你可以尝试禁用扩展之后看是否问题还存在.

**Comment by huhuime** [comment]
从原始播放器切html5就会报这个错
Image from origin 'http://i2.hdslb.com' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.bilibili.com' is therefore not allowed access.
在隐身窗口下只启用该扩展依旧如此
是该扩展html5播放器无法播放，原flash是可以得。。。。。

**Comment by huhuime** [comment]
直接看该扩展的背景页。也者错误，只是跨域不同了而已
![image](https://cloud.githubusercontent.com/assets/6631239/11317384/2f6d3972-9068-11e5-8d78-2e802d540cf7.png)

![image](https://cloud.githubusercontent.com/assets/6631239/11317412/0eea1cd2-9069-11e5-8f2b-56156355b172.png)


直接看这个扩展的background.html也是这个错误，是不是修改响应头的代码失效了。导致无法跨越加载数据？

**Comment by zacyu** [comment]
我这边测试是没问题的, 建议检查是否与其它扩展冲突.

**Comment by huhuime** [comment]
重装扩展后可用，和Chrono下载管理器下载冲突会导致播放不了？只能改优先级才行，这也太坑了吧

**Comment by zacyu** [comment]
应该和 Chrono 没关系.

**Comment by Aqours** [comment]
这是哔哩哔哩部分 CDN 的问题

**Comment by AnnAngela** [comment]
看到network图就知道你的视频被ISP缓存了还把header全删掉了=。=找ISP去吧
