### ISSUE TITLE
在Firefox上使用会出现设置页面无法关闭弹出的购买会员页面

### ISSUE THREAD

**Issue by TABRIS1412** [zacyu/bilibili-helper#871]
在未登录的情况下，可以通过点击支付跳转登录页面正常进入设置页面，但登录完成后下次打开就会无法关闭会员购买页面，已购买并完成支付情况下单击支付完成也会一直提示“收到来自支付页的订单确认请求，正在确认请稍候”

**Comment by TABRIS1412** [comment]
似乎莫名其妙自动修复了的说，在尝试复现中。

**Comment by jjj201200** [comment]
我们还没有在火狐上架哦，并且注意查看针对火狐的弹出公示。
