### ISSUE TITLE
自动全屏（非网页全屏）【'Improve YouTube!' (Video & YouTube Tools)🎧】最好还能有类似【pakku 哔哩哔哩弹幕过滤器】过滤弹幕的功能

### ISSUE THREAD

**Issue by k22725** [zacyu/bilibili-helper#873]
['Improve YouTube!' (Video & YouTube Tools)🎧](https://chrome.google.com/webstore/detail/improve-youtube-video-you/bnomihfieiccainjcjblhegjgglakjdd) 可自动让youtube视频全屏（不是网页全屏 是布满整个显示器屏幕的全屏）还能隐藏控制条

[pakku 哔哩哔哩弹幕过滤器](https://s.xmcp.ltd/pakkujs/?src=wext_homepage) 可把重复的弹幕合并，且让合并后的弹幕变大，并在字幕角落上显示 同样内容弹幕的数字

如果bilibili助手也能有类似功能 或许就是全网唯一一个实现bilibili自动全屏的解决方案 就NB大了 期望能实现这样的功能

**Comment by jjj201200** [comment]
感谢您提供的线索。
关于第一点，我会去看一下是否有可能的方案，之后会尝试优化一下。
关于第二点，我们和pakku是互推扩展。pakku在弹幕管理方面已经做的足够多足够好用，除非哪天pakku开发者不打算继续维护了，否则我这边不应该去重复做一遍哈，希望您能理解。

**Comment by jjj201200** [comment]
youtube的自动宽屏是扩展使用了youtube播放器本身的接口来实现的，而b站方面目前暂时没有发现全屏接口，我们代码层面被禁止主动发起全屏：
> Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.

或许可能会有一些特别的hack方案。

**Comment by k22725** [comment]
非常感谢大神恳切细致的回复 加油！
感谢你们的付出 方便我们广大网民 节省宝贵的时间
鄙人文化不高嘴笨 抱歉姗姗来迟的回复
