### ISSUE TITLE
选择器class名疑似有误

### ISSUE THREAD

**Issue by frankli0324** [zacyu/bilibili-helper#874]
### 环境信息
请填写以下信息:
1. 操作系统 (Windows/macOS/Linux): macOS
2. 浏览器版本(您可以在 [菜单/帮助/关于] 下查看): Chrome
3. 扩展版本: 2.5.13

### 重现步骤/尝试的解决方案

助手select的class名为：
![image](https://user-images.githubusercontent.com/20221896/200186403-e8747a8f-6b99-4788-abb1-a0aec1326695.png)
而播放器使用的class名为：
![image](https://user-images.githubusercontent.com/20221896/200186425-0507f8d8-c997-44a9-a3aa-3e7a5647408d.png)

**Comment by frankli0324** [comment]
因bilibili经常迭代变更相关参数，可否将类似这样的变量设置为可修改的参数？

**Comment by jjj201200** [comment]
感谢反馈，确实他们又又又又又改了，我会立刻发布修复版本。
远程修改此类参数是可行的，之后再安排。

**Comment by frankli0324** [comment]
期待可以在插件设置页面直接配置（

**Comment by jjj201200** [comment]
> 期待可以在插件设置页面直接配置（

是否允许配置得考虑一下，b站有时候会出现多个版本的视频页面使用不同命名，还是一件比较繁琐的事情。
让用户自己配置只能帮到极个别有能耐的用户。

我更倾向于提高反馈效率和降低迭代成本的普适性方案。

另外需要补充的是，这个bug是我的疏忽，其实自动切换画质功能里已经做了适配，但是这个函数在上次适配时并没有被考虑到。

**Comment by jjj201200** [comment]
修复版已经发布在官网，我关闭了哈，再次感谢您的反馈~
