### ISSUE TITLE
在下载东西的时候chrome会提示报错

### ISSUE THREAD

**Issue by popophu** [zacyu/bilibili-helper#88]
![bili](https://cloud.githubusercontent.com/assets/13128713/11324969/bd3de21a-917b-11e5-8d6e-5a270dc449e7.png)

**Comment by zacyu** [comment]
Duplicate of #78. 已经在 e5bd98696f57c6d2fb71cbe6e78926dcc63bf71a 中修复, 将在下一个版本更新到 Webstore.
