### ISSUE TITLE
与chrono扩展程序冲突？

### ISSUE THREAD

**Issue by tknw** [zacyu/bilibili-helper#89]
![qq 20151123093628](https://cloud.githubusercontent.com/assets/5712054/11328450/d5606c9c-91c5-11e5-9caa-d635efe03377.jpg)
警告：
此扩展程序无法将下载的文件命名为“mqdefault.jpg”，因为另一扩展程序 (哔哩哔哩助手：bilibili.com 综合辅助扩展) 已将此文件命名为“mqdefault.jpg”。

**Comment by zacyu** [comment]
Duplicate of #78. 已经在 e5bd98696f57c6d2fb71cbe6e78926dcc63bf71a 中修复, 将在下一个版本更新到 Webstore.
