### ISSUE TITLE
b站改版后，即使关闭“切换播放器”功能，依旧会自动切换

### ISSUE THREAD

**Issue by NekoYuuka** [zacyu/bilibili-helper#92]
使用的助手版本号为：0.7.9
 1. 今天b站对首页和播放页进行了大幅度的更改，但是在改版后，助手会对**所有播放页**进行播放器替换 
![3.png](https://ooo.0o0.ooo/2015/12/02/565fbe5071c06.png)
 * 由于新版界面个人感觉相比之前美观了一些，所以想关闭“播放器替换功能”
![1](https://cloud.githubusercontent.com/assets/13185633/11551452/651474c8-99b4-11e5-930c-82a3e1f1f154.png)
 * 但是结果是没有被关闭
![2.png](https://ooo.0o0.ooo/2015/12/02/565fbda19f268.png)

**Comment by FrogAC** [comment]
我刚刚也发现了想上来看看的，开视频过了几秒会刷新自动切换

**Comment by zacyu** [comment]
Fixed in 9b6be7910475bb045a80fff9a8a26aa6d58fae92.
