### ISSUE TITLE
b站新更新

### ISSUE THREAD

**Issue by code110** [zacyu/bilibili-helper#94]
国外党，看什么视频都是突然跳转，虽然能看，但看不见up主，看到一半再跳转也不舒服。
我喜欢关注推送功能，不想停用助手。大神，优化下呗。

**Comment by zacyu** [comment]
升级到最新版就可以了. 国外的话应该 Chrome 会自动推送. 如果没有的话可以卸载后到 https://chrome.google.com/webstore/detail/kpbnombpnpcffllnianjibmpadjolanh 安装更新.

**Comment by code110** [comment]
感谢
