### ISSUE TITLE
更新检查有问题,不停的弹出应用设置页

### ISSUE THREAD

**Issue by Qixingchen** [zacyu/bilibili-helper#95]
![image](https://cloud.githubusercontent.com/assets/4182240/11604845/eb045926-9b2c-11e5-8caf-3bf4bd6461a4.png)

于是一晚上之后就这样了..

**Comment by FrozenYogurtPuff** [comment]
同遇到这个问题

**Comment by zacyu** [comment]
您好, 该问题在 v0.8.2 中已经修复. 麻烦您之后发 issue 前确定您使用的是最新发行/开发版本.
