### ISSUE TITLE
强烈建议增加关闭自动更新的选项，或者移除该功能

### ISSUE THREAD

**Issue by ee0703** [zacyu/bilibili-helper#96]
新版本插件自带的自动更新有问题，老是不停弹出提示更新页面，但又无法关闭自动更新，神烦，只能禁用插件。
而且，插件自带的自动更新一般没人用吧，这一功能没有必要，因为chrome会自动更新的。
所以，建议添加关闭选项，或移除该功能。

**Comment by zacyu** [comment]
您现在使用的是 v0.8.2 版本吗? 这个问题在最新版本中修复了. 提醒更新的原因是因为墙内 Chrome 无法连接到 Google 检查更新, 导致很多用户保持在旧版本.

**Comment by ee0703** [comment]
更新以后已经没问题了，非常感谢
