### ISSUE TITLE
最近的b站页面有改动，貌似up主头像那一块出问题了

### ISSUE THREAD

**Issue by TwoAnts** [zacyu/bilibili-helper#97]
![4](https://cloud.githubusercontent.com/assets/5968383/11606282/02e8a34e-9b5f-11e5-8fbd-a4ab8eca7db3.png)

最近看视频，成这样了。
只能把bilibili助手关掉。

**Comment by zacyu** [comment]
您好, 该问题只需要更新到 v0.8.0 之后版本的扩展即可 (最新版本为 v0.8.2). 麻烦您之后发 issue 前确定您使用的是最新发行/开发版本.

**Comment by TwoAnts** [comment]
好吧，是插件没有更新，昨天还是这样的，今天什么都没干，就好了。
是更新推送的延迟吧。

**Comment by TwoAnts** [comment]
另外，感谢作者的辛勤劳作。
