### ISSUE TITLE
播放器替换

### ISSUE THREAD

**Issue by unlimitwhitenight** [zacyu/bilibili-helper#99]
没什么用，而且会把视频分段隐藏无法自主切换

**Comment by zacyu** [comment]
您好, 这个功能原本的作用是替换 B 站官方隐藏不在 Web 端播放的视频. 因为改版后的前端变化, 新版页面被认为是无效页面, 所以扩展对所有页面都进行的替换操作. 我已经与 3 天前进行适配并发布了更新. 该问题只需要更新到 v0.8.0 之后版本的扩展即可 (最新版本为 v0.8.2). 麻烦您之后发 issue 前确定您使用的是最新发行/开发版本.

**Comment by zacyu** [comment]
duplicate of #97
